import { artifactTargetsHarness } from './harness.ts';
import type { ResolvedRulebook } from './rulebook-deploy.ts';
import { renderRulebookBody, type ResolveRulebookContext } from './rulebook-transform.ts';
import { injectRulebook, injectSentinelBlock } from './sentinel-inliner.ts';
import type { HarnessId } from './types.ts';

/** A reference delivered into an ambient region: its name, its summary, and the path that its block names. */
export interface AmbientReference {
  readonly name: string;
  readonly summary: string;
  readonly displayPath: string;
}

/**
 * Renders the ambient rulebooks that target the harness, then the references, as concatenated sentinel blocks beneath
 * the generated-region note: the wholesale content of one harness's ambient region. The context is one harness's, so
 * the same rulebook yields that harness's own absolute paths. An empty result stays empty: The note belongs to
 * generated content, and callers read emptiness as "nothing to deliver here".
 */
export function renderAmbientBody(
  resolved: ReadonlyArray<ResolvedRulebook>,
  references: ReadonlyArray<AmbientReference>,
  harnessId: HarnessId,
  resolveRulebookContext: ResolveRulebookContext,
): string {
  let body = '';
  for (const rulebook of resolved) {
    if (!rulebook.ambient || !artifactTargetsHarness(rulebook, harnessId)) {
      continue;
    }
    const context = resolveRulebookContext(harnessId, rulebook.source);
    body = injectRulebook(
      body,
      rulebook.slug,
      renderRulebookBody(rulebook.body, rulebook.slug, context),
      rulebook.version,
    );
  }
  for (const reference of references) {
    body = injectSentinelBlock(
      body,
      'reference',
      reference.name,
      `${reference.summary.trim()}\n\nLocation: \`${reference.displayPath}\``,
    );
  }
  // Prepend rather than seed the loop: Seeding would pass the note through `injectRulebook`, which separates it from
  // the first block with a blank line and would leave the note standing as the whole body when nothing is ambient.
  return body === '' ? '' : `${ambientRegionNote}\n${body}`;
}

// region | Helpers

/**
 * The line with which an ambient region opens, so that a reader who finds generated guidance knows an edit there is
 * lost.
 */
const ambientRegionNote =
  '<!-- Generated by `codeassembly sync` from the rulebooks and references named below. Edits inside this region are overwritten. -->';

// endregion | Helpers
