import { lstat, readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

/**
 * Git ref used in Source: URLs of provenance markers. Hardcoded until
 * version-pinning lands (tracked in williamthorsen/codeassembly#444).
 */
export const SOURCE_REF = 'main';

const REPO_BLOB_BASE = `https://github.com/williamthorsen/codeassembly/blob/${SOURCE_REF}/packages/agents/content`;

const LINE_1_TEXT = 'GENERATED FILE - Do not edit this file.';
const LINE_3_TEXT =
  'Edits to this file are overwritten on the next install/sync. Edit the source and re-run `codeassembly-agents install`.';

const YAML_MARKER_PREFIX = '# ';
const HTML_MARKER_OPEN = '<!-- ';
const HTML_MARKER_CLOSE = ' -->';

const FRONTMATTER_OPEN = '---';

/**
 * Build the GitHub URL pointing to a source file under `packages/agents/content/`.
 * `contentRelativePath` is the path relative to that directory (e.g., `skills/collaboration/SKILL.md`).
 */
export function buildSourceUrl(contentRelativePath: string): string {
  return `${REPO_BLOB_BASE}/${contentRelativePath}`;
}

/**
 * Inject a provenance marker into a Markdown file's content. Files starting with `---\n`
 * receive three YAML comment lines immediately after the opening delimiter; all other
 * files receive three HTML comment lines at the top followed by a blank line.
 *
 * Idempotent: if the expected marker (any existing marker in the correct position) is already
 * present, it is replaced with the marker computed from `sourceUrl`, leaving the surrounding
 * content unchanged. A repeat call with the same `sourceUrl` returns identical content.
 */
export function injectProvenanceMarker(content: string, sourceUrl: string): string {
  if (hasYamlFrontmatter(content)) {
    return injectYamlMarker(content, sourceUrl);
  }
  return injectHtmlMarker(content, sourceUrl);
}

/**
 * Walk a directory tree and apply `injectProvenanceMarker` in place to every `.md` file found.
 * `resolveSourceUrl` is called with each file's path relative to `rootDir` and must return the
 * canonical source URL for that file.
 */
export async function injectMarkersInDirectory(
  rootDir: string,
  resolveSourceUrl: (fileRelPath: string) => string,
): Promise<void> {
  await walkAndInject(rootDir, rootDir, resolveSourceUrl);
}

/**
 * Apply `injectProvenanceMarker` in place to a single file.
 */
export async function injectMarkerInFile(filePath: string, sourceUrl: string): Promise<void> {
  const content = await readFile(filePath, 'utf8');
  const updated = injectProvenanceMarker(content, sourceUrl);
  if (updated !== content) {
    await writeFile(filePath, updated, 'utf8');
  }
}

function hasYamlFrontmatter(content: string): boolean {
  return content.startsWith(`${FRONTMATTER_OPEN}\n`);
}

function injectYamlMarker(content: string, sourceUrl: string): string {
  const lines = content.split('\n');
  // lines[0] is `---`. Strip any pre-existing marker lines immediately after it.
  const afterOpen = stripExistingYamlMarkerLines(lines.slice(1));
  const markerLines = [
    `${YAML_MARKER_PREFIX}${LINE_1_TEXT}`,
    `${YAML_MARKER_PREFIX}Source: ${sourceUrl}`,
    `${YAML_MARKER_PREFIX}${LINE_3_TEXT}`,
  ];
  return [FRONTMATTER_OPEN, ...markerLines, ...afterOpen].join('\n');
}

function stripExistingYamlMarkerLines(rest: ReadonlyArray<string>): ReadonlyArray<string> {
  // An existing marker, if present, is three consecutive YAML comment lines whose first line
  // begins with "# GENERATED FILE". Remove them so we can write fresh marker lines. This also
  // handles the migration case of a different Source: URL.
  if (rest.length >= 3 && rest[0] === `${YAML_MARKER_PREFIX}${LINE_1_TEXT}`) {
    return rest.slice(3);
  }
  return rest;
}

function injectHtmlMarker(content: string, sourceUrl: string): string {
  const body = stripExistingHtmlMarkerBlock(content);
  const marker = [
    `${HTML_MARKER_OPEN}${LINE_1_TEXT}${HTML_MARKER_CLOSE}`,
    `${HTML_MARKER_OPEN}Source: ${sourceUrl}${HTML_MARKER_CLOSE}`,
    `${HTML_MARKER_OPEN}${LINE_3_TEXT}${HTML_MARKER_CLOSE}`,
    '',
  ].join('\n');

  if (body === '') {
    return marker;
  }
  return `${marker}\n${body}`;
}

function stripExistingHtmlMarkerBlock(content: string): string {
  const existingFirstLine = `${HTML_MARKER_OPEN}${LINE_1_TEXT}${HTML_MARKER_CLOSE}`;
  if (!content.startsWith(`${existingFirstLine}\n`)) {
    return content;
  }
  const lines = content.split('\n');
  // Drop the three marker lines plus the single blank separator line, if present.
  let dropCount = 3;
  if (lines[dropCount] === '') {
    dropCount++;
  }
  return lines.slice(dropCount).join('\n');
}

async function walkAndInject(
  currentDir: string,
  rootDir: string,
  resolveSourceUrl: (fileRelPath: string) => string,
): Promise<void> {
  const entries = await readdir(currentDir);

  for (const entry of entries) {
    const fullPath = path.join(currentDir, entry);
    const stats = await lstat(fullPath);

    if (stats.isSymbolicLink()) {
      continue;
    }

    if (stats.isDirectory()) {
      await walkAndInject(fullPath, rootDir, resolveSourceUrl);
    } else if (entry.endsWith('.md')) {
      const fileRelPath = path.relative(rootDir, fullPath).split(path.sep).join('/');
      await injectMarkerInFile(fullPath, resolveSourceUrl(fileRelPath));
    }
  }
}
