import type { ContentRootRef } from './content-root-manifest.ts';

const LINE_1_TEXT = 'GENERATED FILE - Do not edit this file.';
const LINE_3_TEXT =
  'Edits to this file are overwritten on the next install/sync. Edit the source and re-run `codeassembly install`.';

const YAML_MARKER_PREFIX = '# ';
const HTML_MARKER_OPEN = '<!-- ';
const HTML_MARKER_CLOSE = ' -->';

const FRONTMATTER_OPEN = '---';

/**
 * Builds the `Source:` reference in a deployed file's provenance marker, naming where its content came from: the
 * file's path within its source, the source's name, and the directory containing it. The name locates the declaration
 * entry, and the directory locates the file to edit, which a package source's `node_modules` path does not reveal on
 * its own.
 */
export function buildSourceReference(root: ContentRootRef, contentRelativePath: string): string {
  return `${contentRelativePath} in source "${root.name}" (${root.dir})`;
}

/**
 * Injects a provenance marker into a Markdown file's content. Files starting with `---\n`
 * receive three YAML comment lines immediately after the opening delimiter; all other
 * files receive three HTML comment lines at the top followed by a blank line.
 *
 * Idempotent: If the expected marker (any existing marker in the correct position) is already
 * present, it is replaced with the marker computed from `sourceUrl`, leaving the surrounding
 * content unchanged. A repeat call with the same `sourceUrl` returns identical content.
 */
export function injectProvenanceMarker(content: string, sourceUrl: string): string {
  if (hasYamlFrontmatter(content)) {
    return injectYamlMarker(content, sourceUrl);
  }
  return injectHtmlMarker(content, sourceUrl);
}

/** True when the content opens with a YAML frontmatter delimiter. */
function hasYamlFrontmatter(content: string): boolean {
  return content.startsWith(`${FRONTMATTER_OPEN}\n`);
}

/** Writes the marker as YAML comment lines immediately after the frontmatter's opening delimiter. */
function injectYamlMarker(content: string, sourceUrl: string): string {
  const lines = content.split('\n');
  const afterOpen = stripExistingYamlMarkerLines(lines.slice(1));
  const markerLines = [
    `${YAML_MARKER_PREFIX}${LINE_1_TEXT}`,
    `${YAML_MARKER_PREFIX}Source: ${sourceUrl}`,
    `${YAML_MARKER_PREFIX}${LINE_3_TEXT}`,
  ];
  return [FRONTMATTER_OPEN, ...markerLines, ...afterOpen].join('\n');
}

/** Drops an existing YAML marker from the lines following the frontmatter's opening delimiter. */
function stripExistingYamlMarkerLines(rest: ReadonlyArray<string>): ReadonlyArray<string> {
  // An existing marker is three consecutive YAML comment lines opening with "# GENERATED FILE", whichever `Source:`
  // URL it names.
  if (rest.length >= 3 && rest[0] === `${YAML_MARKER_PREFIX}${LINE_1_TEXT}`) {
    return rest.slice(3);
  }
  return rest;
}

/** Writes the marker as HTML comment lines at the top of the content, followed by a blank line. */
function injectHtmlMarker(content: string, sourceUrl: string): string {
  const body = stripExistingHtmlMarkerBlock(content);
  const marker = [
    `${HTML_MARKER_OPEN}${LINE_1_TEXT}${HTML_MARKER_CLOSE}`,
    `${HTML_MARKER_OPEN}Source: ${sourceUrl}${HTML_MARKER_CLOSE}`,
    `${HTML_MARKER_OPEN}${LINE_3_TEXT}${HTML_MARKER_CLOSE}`,
    '',
  ].join('\n');

  if (body === '') {
    return marker;
  }
  return `${marker}\n${body}`;
}

/** Drops an existing HTML marker block, along with the blank line separating it from the body. */
function stripExistingHtmlMarkerBlock(content: string): string {
  const existingFirstLine = `${HTML_MARKER_OPEN}${LINE_1_TEXT}${HTML_MARKER_CLOSE}`;
  if (!content.startsWith(`${existingFirstLine}\n`)) {
    return content;
  }
  const lines = content.split('\n');
  let dropCount = 3;
  if (lines[dropCount] === '') {
    dropCount++;
  }
  return lines.slice(dropCount).join('\n');
}
