import { describe, expect, it } from 'vitest';

import { buildSourceReference, buildSourceUrl, injectProvenanceMarker, SOURCE_REF } from '../marker-injector.ts';

describe(injectProvenanceMarker, () => {
  const sourceUrl =
    'https://github.com/williamthorsen/codeassembly/blob/main/packages/agents/content/skills/example/SKILL.md';

  describe('files with YAML frontmatter', () => {
    it('inserts three comment lines immediately after the opening `---`', () => {
      const input = ['---', 'name: example', 'description: an example skill', '---', '', '# Body', ''].join('\n');
      const result = injectProvenanceMarker(input, sourceUrl);

      expect(result).toBe(
        [
          '---',
          '# GENERATED FILE - Do not edit this file.',
          `# Source: ${sourceUrl}`,
          '# Edits to this file are overwritten on the next install/sync. Edit the source and re-run `codeassembly install`.',
          'name: example',
          'description: an example skill',
          '---',
          '',
          '# Body',
          '',
        ].join('\n'),
      );
    });

    it('preserves the body exactly', () => {
      const input = ['---', 'name: x', '---', '', 'Body line 1.', '', 'Body line 2.'].join('\n');
      const result = injectProvenanceMarker(input, sourceUrl);
      expect(result.endsWith('\n\nBody line 1.\n\nBody line 2.')).toBe(true);
    });

    it('is idempotent: applying twice returns the same content', () => {
      const input = ['---', 'name: example', '---', '', 'Body', ''].join('\n');
      const once = injectProvenanceMarker(input, sourceUrl);
      const twice = injectProvenanceMarker(once, sourceUrl);
      expect(twice).toBe(once);
    });

    it('refreshes the marker when the source URL differs', () => {
      const input = ['---', 'name: example', '---', '', 'Body', ''].join('\n');
      const withFirst = injectProvenanceMarker(input, sourceUrl);
      const newUrl =
        'https://github.com/williamthorsen/codeassembly/blob/main/packages/agents/content/skills/renamed/SKILL.md';
      const withSecond = injectProvenanceMarker(withFirst, newUrl);

      expect(withSecond).toContain(`# Source: ${newUrl}`);
      expect(withSecond).not.toContain(`# Source: ${sourceUrl}`);
    });
  });

  describe('files without YAML frontmatter', () => {
    it('prepends three HTML comment lines and a trailing blank line', () => {
      const input = '# AGENTS\n\nSome shared guidance.\n';
      const result = injectProvenanceMarker(input, sourceUrl);

      expect(result).toBe(
        [
          '<!-- GENERATED FILE - Do not edit this file. -->',
          `<!-- Source: ${sourceUrl} -->`,
          '<!-- Edits to this file are overwritten on the next install/sync. Edit the source and re-run `codeassembly install`. -->',
          '',
          '# AGENTS',
          '',
          'Some shared guidance.',
          '',
        ].join('\n'),
      );
    });

    it('is idempotent: applying twice returns the same content', () => {
      const input = '# AGENTS\n\nBody.\n';
      const once = injectProvenanceMarker(input, sourceUrl);
      const twice = injectProvenanceMarker(once, sourceUrl);
      expect(twice).toBe(once);
    });

    it('refreshes the marker when the source URL differs', () => {
      const input = '# AGENTS\n\nBody.\n';
      const withFirst = injectProvenanceMarker(input, sourceUrl);
      const newUrl =
        'https://github.com/williamthorsen/codeassembly/blob/main/packages/agents/content/guidance/shared/OTHER.md';
      const withSecond = injectProvenanceMarker(withFirst, newUrl);

      expect(withSecond).toContain(`<!-- Source: ${newUrl} -->`);
      expect(withSecond).not.toContain(`<!-- Source: ${sourceUrl} -->`);
    });

    it('handles empty input', () => {
      const result = injectProvenanceMarker('', sourceUrl);
      expect(result.startsWith('<!-- GENERATED FILE - Do not edit this file. -->\n')).toBe(true);
    });
  });

  describe('edge cases', () => {
    it('treats a `---` that is not at the start of the file as a non-frontmatter case', () => {
      const input = 'Preface line\n---\nname: example\n---\n\nBody\n';
      const result = injectProvenanceMarker(input, sourceUrl);
      expect(result.startsWith('<!-- GENERATED FILE - Do not edit this file. -->\n')).toBe(true);
    });

    it('handles unicode content in the body', () => {
      const input = ['---', 'name: example', '---', '', 'Emoji: 👍🏼', ''].join('\n');
      const result = injectProvenanceMarker(input, sourceUrl);
      expect(result).toContain('Emoji: 👍🏼');
    });
  });
});

describe(buildSourceReference, () => {
  it('renders the library blob URL for a root with no name', () => {
    expect(buildSourceReference({ dir: '/anywhere/content' }, 'scripts/relay-hook-event.mjs')).toBe(
      buildSourceUrl('scripts/relay-hook-event.mjs'),
    );
  });

  it('names the path, the source, and its directory for a declared source', () => {
    expect(
      buildSourceReference(
        { name: 'org-guidance', dir: '/Users/you/repos/org-guidance/content' },
        'guidance/_harnesses/claude/CLAUDE.md',
      ),
    ).toBe('guidance/_harnesses/claude/CLAUDE.md in source "org-guidance" (/Users/you/repos/org-guidance/content)');
  });
});

describe(buildSourceUrl, () => {
  it('builds a URL under packages/agents/content/ at the SOURCE_REF branch', () => {
    expect(buildSourceUrl('skills/collaborate/SKILL.md')).toBe(
      `https://github.com/williamthorsen/codeassembly/blob/${SOURCE_REF}/packages/agents/content/skills/collaborate/SKILL.md`,
    );
  });

  it('handles nested paths', () => {
    expect(buildSourceUrl('skills/orchestrate/modules/review-cycle.md')).toBe(
      `https://github.com/williamthorsen/codeassembly/blob/${SOURCE_REF}/packages/agents/content/skills/orchestrate/modules/review-cycle.md`,
    );
  });

  it('handles guidance and subagent paths', () => {
    expect(buildSourceUrl('guidance/shared/AGENTS.md')).toBe(
      `https://github.com/williamthorsen/codeassembly/blob/${SOURCE_REF}/packages/agents/content/guidance/shared/AGENTS.md`,
    );
    expect(buildSourceUrl('subagents/orchestrated-coder.md')).toBe(
      `https://github.com/williamthorsen/codeassembly/blob/${SOURCE_REF}/packages/agents/content/subagents/orchestrated-coder.md`,
    );
  });

  it('pins the source ref to main (until version-pinning is implemented)', () => {
    expect(SOURCE_REF).toBe('main');
  });
});
