import { describe, expect, it } from 'vitest';

import { buildSourceReference, injectProvenanceMarker } from '../marker-injector.ts';

describe(injectProvenanceMarker, () => {
  const sourceUrl = 'skills/example/SKILL.md in source "codeassembly" (/srcs/codeassembly/content)';

  describe('files with YAML frontmatter', () => {
    it('inserts three comment lines immediately after the opening `---`', () => {
      const input = ['---', 'name: example', 'description: an example skill', '---', '', '# Body', ''].join('\n');
      const result = injectProvenanceMarker(input, sourceUrl);

      expect(result).toBe(
        [
          '---',
          '# GENERATED FILE - Do not edit this file.',
          `# Source: ${sourceUrl}`,
          '# Edits to this file are overwritten on the next install/sync. Edit the source and re-run `codeassembly install`.',
          'name: example',
          'description: an example skill',
          '---',
          '',
          '# Body',
          '',
        ].join('\n'),
      );
    });

    it('preserves the body exactly', () => {
      const input = ['---', 'name: x', '---', '', 'Body line 1.', '', 'Body line 2.'].join('\n');
      const result = injectProvenanceMarker(input, sourceUrl);
      expect(result.endsWith('\n\nBody line 1.\n\nBody line 2.')).toBe(true);
    });

    it('is idempotent: Applying twice returns the same content', () => {
      const input = ['---', 'name: example', '---', '', 'Body', ''].join('\n');
      const once = injectProvenanceMarker(input, sourceUrl);
      const twice = injectProvenanceMarker(once, sourceUrl);
      expect(twice).toBe(once);
    });

    it('refreshes the marker when the source URL differs', () => {
      const input = ['---', 'name: example', '---', '', 'Body', ''].join('\n');
      const withFirst = injectProvenanceMarker(input, sourceUrl);
      const newUrl = 'skills/renamed/SKILL.md in source "codeassembly" (/srcs/codeassembly/content)';
      const withSecond = injectProvenanceMarker(withFirst, newUrl);

      expect(withSecond).toContain(`# Source: ${newUrl}`);
      expect(withSecond).not.toContain(`# Source: ${sourceUrl}`);
    });
  });

  describe('files without YAML frontmatter', () => {
    it('prepends three HTML comment lines and a trailing blank line', () => {
      const input = '# AGENTS\n\nSome shared guidance.\n';
      const result = injectProvenanceMarker(input, sourceUrl);

      expect(result).toBe(
        [
          '<!-- GENERATED FILE - Do not edit this file. -->',
          `<!-- Source: ${sourceUrl} -->`,
          '<!-- Edits to this file are overwritten on the next install/sync. Edit the source and re-run `codeassembly install`. -->',
          '',
          '# AGENTS',
          '',
          'Some shared guidance.',
          '',
        ].join('\n'),
      );
    });

    it('is idempotent: Applying twice returns the same content', () => {
      const input = '# AGENTS\n\nBody.\n';
      const once = injectProvenanceMarker(input, sourceUrl);
      const twice = injectProvenanceMarker(once, sourceUrl);
      expect(twice).toBe(once);
    });

    it('refreshes the marker when the source URL differs', () => {
      const input = '# AGENTS\n\nBody.\n';
      const withFirst = injectProvenanceMarker(input, sourceUrl);
      const newUrl = 'guidance/shared/OTHER.md in source "codeassembly" (/srcs/codeassembly/content)';
      const withSecond = injectProvenanceMarker(withFirst, newUrl);

      expect(withSecond).toContain(`<!-- Source: ${newUrl} -->`);
      expect(withSecond).not.toContain(`<!-- Source: ${sourceUrl} -->`);
    });

    it('handles empty input', () => {
      const result = injectProvenanceMarker('', sourceUrl);
      expect(result.startsWith('<!-- GENERATED FILE - Do not edit this file. -->\n')).toBe(true);
    });
  });

  describe('edge cases', () => {
    it('treats a `---` that is not at the start of the file as a non-frontmatter case', () => {
      const input = 'Preface line\n---\nname: example\n---\n\nBody\n';
      const result = injectProvenanceMarker(input, sourceUrl);
      expect(result.startsWith('<!-- GENERATED FILE - Do not edit this file. -->\n')).toBe(true);
    });

    it('handles unicode content in the body', () => {
      const input = ['---', 'name: example', '---', '', 'Emoji: 👍🏼', ''].join('\n');
      const result = injectProvenanceMarker(input, sourceUrl);
      expect(result).toContain('Emoji: 👍🏼');
    });
  });
});

describe(buildSourceReference, () => {
  it('names the path, the source, and its directory for a declared source', () => {
    expect(
      buildSourceReference(
        { name: 'org-guidance', dir: '/Users/you/repos/org-guidance/content' },
        'guidance/_harnesses/claude/CLAUDE.md',
      ),
    ).toBe('guidance/_harnesses/claude/CLAUDE.md in source "org-guidance" (/Users/you/repos/org-guidance/content)');
  });
});
