import { execFileSync } from 'node:child_process';
import { mkdir, mkdtemp, realpath, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';

import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { runResolve } from '../cli.ts';
import { RECORD_PATH } from '../record.ts';
import type { HelperFailure, ResolveSuccess } from '../types.ts';

const TARGET = 'lib/skills/demo/SKILL.md';

/** A repository holding one content root, whose skill includes a partial that includes and links onward. */
const REPOSITORY_FILES: Readonly<Record<string, string>> = {
  '.agents/preferences.yaml': 'artifacts:\n  base_dir: sealed\n',
  'AGENTS.md':
    '# Guide\n\n<!-- codeassembly-ambient:start -->\nGenerated.\n<!-- codeassembly-ambient:end -->\n\nAuthored.\n',
  'lib/codeassembly-content.yaml': 'format: 2\n',
  'lib/_partials/inner.md': 'Inner text.\n',
  'lib/_partials/shared.md': 'Shared text. See [ref](../_data/ref.md).\n\n<!-- include: ./inner.md / -->\n',
  'lib/skills/_data/deep.md': 'Deep.\n',
  'lib/skills/_data/other.md': 'Other.\n',
  'lib/skills/_data/ref.md': 'Reference. See [deep](./deep.md).\n',
  'lib/skills/_data/types.json': '{}\n',
  [TARGET]: [
    '---',
    'name: demo',
    '---',
    '',
    '<!-- include: ../../_partials/shared.md / -->',
    '',
    'Read `{harness_home_dir}/skills/_data/other.md`.',
    '',
    'See [types]({harness_home_dir}/skills/_data/types.json).',
    '',
  ].join('\n'),
  'notes.txt': 'Not guidance.\n',
  'sealed/note.md': 'A sealed artifact.\n',
};

/** Files outside the repository: deployed copies in a harness home, and an authored file that is not in git. */
const HOME_FILES: Readonly<Record<string, string>> = {
  '.claude/skills/_data/ref.md':
    '<!-- GENERATED FILE - Do not edit this file. -->\n<!-- Source: https://github.com/owner/repo/blob/main/lib/skills/_data/ref.md -->\n\nReference.\n',
  '.claude/skills/demo/SKILL.md': '---\nname: demo\n---\n<!-- codeassembly-skill:demo -->\n\nDeployed.\n',
  '.claude/skills/orphan/SKILL.md': '---\nname: orphan\n---\n<!-- codeassembly-skill:orphan -->\n\nDeployed.\n',
  'loose.md': 'Loose.\n',
};

describe(runResolve, () => {
  let home: string;
  let repository: string;
  let scratch: string;

  beforeEach(async () => {
    scratch = await realpath(await mkdtemp(path.join(tmpdir(), 'streamline-resolve-')));
    repository = path.join(scratch, 'repository');
    home = path.join(scratch, 'home');
    await writeFiles(repository, REPOSITORY_FILES);
    await writeFiles(home, HOME_FILES);
    execFileSync('git', ['-C', repository, 'init', '--quiet']);
    execFileSync('git', ['-C', repository, 'add', '--all']);
    execFileSync('git', [
      '-C',
      repository,
      '-c',
      'user.email=test@example.com',
      '-c',
      'user.name=Test',
      'commit',
      '--quiet',
      '--message',
      'seed',
    ]);
  });

  afterEach(async () => {
    await rm(scratch, { recursive: true, force: true });
  });

  it("reports a target's includes, recursively, and the Markdown files to which it and its includes link", async () => {
    const result = expectSuccess(await resolve(TARGET));

    expect(result.targets.map((target) => target.file)).toStrictEqual([TARGET]);
    expect(result.transitive.map(({ file, via }) => ({ file, via }))).toStrictEqual([
      { file: 'lib/_partials/inner.md', via: [{ from: 'lib/_partials/shared.md', kind: 'include' }] },
      { file: 'lib/_partials/shared.md', via: [{ from: TARGET, kind: 'include' }] },
      { file: 'lib/skills/_data/other.md', via: [{ from: TARGET, kind: 'link' }] },
      // The partial's link resolves against the skill that renders it, not against the partial's own directory.
      { file: 'lib/skills/_data/ref.md', via: [{ from: 'lib/_partials/shared.md', kind: 'link' }] },
    ]);
  });

  it.each([
    { copy: '.claude/skills/demo/SKILL.md', source: TARGET, marker: 'an ownership marker' },
    { copy: '.claude/skills/_data/ref.md', source: 'lib/skills/_data/ref.md', marker: 'a Source line' },
  ])('if a named path is a deployed copy carrying $marker, resolves it to its source', async ({ copy, source }) => {
    const copyPath = path.join(home, copy);

    const result = expectSuccess(await resolve(copyPath));

    expect(result.targets).toMatchObject([{ file: source, redirectedFrom: copyPath }]);
  });

  it.each([
    { named: () => path.join(home, 'loose.md'), reason: 'outside-repository' },
    { named: () => path.join(home, '.claude/skills/orphan/SKILL.md'), reason: 'source-not-in-repository' },
    { named: () => 'sealed/note.md', reason: 'sealed-artifact' },
    { named: () => 'notes.txt', reason: 'not-markdown' },
    { named: () => 'missing.md', reason: 'not-found' },
  ])('if a named path cannot be a target, rejects it as $reason', async ({ named, reason }) => {
    const namedPath = named();

    const result = expectSuccess(await resolve(namedPath));

    expect(result.targets).toStrictEqual([]);
    expect(result.rejected).toStrictEqual([{ path: namedPath, reason }]);
  });

  it('expands a named directory to the Markdown files beneath it', async () => {
    const result = expectSuccess(await resolve('lib/_partials'));

    expect(result.targets.map((target) => target.file).toSorted()).toStrictEqual([
      'lib/_partials/inner.md',
      'lib/_partials/shared.md',
    ]);
  });

  it('rejects a file beneath a named directory whose include does not resolve, and resolves the others', async () => {
    await writeFiles(repository, {
      'lib/notes/README.md': [
        '<!-- include: ../_partials/inner.md / -->',
        '',
        'An example directive:',
        '',
        '```',
        '<!-- include: _partials/example.md / -->',
        '```',
        '',
      ].join('\n'),
      'lib/notes/guide.md': 'A guide.\n',
    });

    const result = expectSuccess(await resolve('lib/notes'));

    expect(result.targets.map((target) => target.file)).toStrictEqual(['lib/notes/guide.md']);
    expect(result.transitive).toStrictEqual([]);
    expect(result.rejected).toStrictEqual([{ path: 'lib/notes/README.md', reason: 'unresolved-include' }]);
  });

  it("reports the line range of a target's generated region", async () => {
    const result = expectSuccess(await resolve('AGENTS.md'));

    expect(result.targets).toMatchObject([{ file: 'AGENTS.md', generatedRegions: [{ start: 3, end: 5 }] }]);
  });

  it('marks only a file with uncommitted changes as dirty', async () => {
    await writeFile(path.join(repository, 'lib/_partials/shared.md'), 'Shared text.\n', 'utf8');
    execFileSync('git', ['-C', repository, 'add', 'lib/_partials/shared.md']);

    const result = expectSuccess(await resolve('lib/_partials/shared.md', 'lib/_partials/inner.md', 'AGENTS.md'));

    expect(Object.fromEntries(result.targets.map((target) => [target.file, target.dirty]))).toStrictEqual({
      'AGENTS.md': false,
      'lib/_partials/inner.md': false,
      'lib/_partials/shared.md': true,
    });
  });

  it('reports only the declined cuts whose phrase their file still contains', async () => {
    await writeFile(
      path.join(repository, RECORD_PATH),
      [
        'declined:',
        '  - file: lib/_partials/shared.md',
        '    phrase: Shared   text.',
        '    class: conservative',
        '    declined-at: 2026-09-01',
        '  - file: lib/_partials/shared.md',
        '    phrase: Removed text.',
        '    class: moderate',
        '    declined-at: 2026-09-01',
        '',
      ].join('\n'),
      'utf8',
    );

    const result = expectSuccess(await resolve(TARGET));

    expect(result.declined).toStrictEqual([
      { file: 'lib/_partials/shared.md', phrase: 'Shared   text.', class: 'conservative' },
    ]);
  });

  describe('failures', () => {
    it('if the working directory is not in a repository, fails as not-a-repository', async () => {
      const result = await runResolve({ argv: ['loose.md'], cwd: home, home });

      expect(result).toMatchObject({ ok: false, error: 'not-a-repository' });
    });

    it('if the record is malformed, fails as invalid-record', async () => {
      await writeFile(path.join(repository, RECORD_PATH), 'declined:\n  - file: x.md\n', 'utf8');

      expect(await resolve(TARGET)).toMatchObject({ ok: false, error: 'invalid-record' });
    });
  });

  /** Runs `resolve` from the repository root against the fixture home. */
  async function resolve(...paths: string[]): Promise<HelperFailure | ResolveSuccess> {
    return runResolve({ argv: paths, cwd: repository, home });
  }
});

// region | Helpers

/** Narrows a result to success, failing the test with the failure's message otherwise. */
function expectSuccess(result: HelperFailure | ResolveSuccess): ResolveSuccess {
  if (!result.ok) {
    throw new Error(`expected success, got ${result.error}: ${result.message}`);
  }
  return result;
}

/** Writes each file beneath a root, creating its directories. */
async function writeFiles(root: string, files: Readonly<Record<string, string>>): Promise<void> {
  for (const [file, content] of Object.entries(files)) {
    await mkdir(path.dirname(path.join(root, file)), { recursive: true });
    await writeFile(path.join(root, file), content, 'utf8');
  }
}

// endregion | Helpers
