/** The note that `sync` renders as the first line of an ambient region's body. */
export const ambientRegionNote =
  '<!-- Generated by `codeassembly sync` from the rulebooks and references named below. Edits inside this region are overwritten. -->';
