export const deferredLintRules = {
  'unicorn/max-nested-calls': 'warn',
  'unicorn/no-computed-property-existence-check': 'warn',
  'unicorn/no-declarations-before-early-exit': 'warn',
  'unicorn/no-duplicate-loops': 'warn',
  'unicorn/no-incorrect-template-string-interpolation': 'warn',
  'unicorn/no-return-array-push': 'warn',
  'unicorn/no-top-level-assignment-in-function': 'warn',
  'unicorn/no-unreadable-for-of-expression': 'warn',
  'unicorn/no-unsafe-string-replacement': 'warn',
  'unicorn/prefer-await': 'warn',
  'unicorn/prefer-includes-over-repeated-comparisons': 'warn',
  'unicorn/prefer-iterator-to-array': 'warn',
  'unicorn/prefer-minimal-ternary': 'warn',
  'unicorn/prefer-object-iterable-methods': 'warn',
  'unicorn/prefer-set-methods': 'warn',
  'unicorn/prefer-simple-condition-first': 'warn',
  'unicorn/require-array-sort-compare': 'warn',
  'preserve-caught-error': 'warn',
} as const;
