import { readFile } from 'node:fs/promises';

import { appendAmbientRegion, classifyAmbientRegion, injectAmbientRegion } from '../../lib/ambient-region.ts';
import { writeIfChanged } from '../../lib/fs-helpers.ts';
import { checkGitIgnored } from '../../lib/git-ignore.ts';
import { resolveAmbientHostPath } from '../../lib/harness.ts';
import type { ResolvedRulebook } from '../../lib/rulebook-deploy.ts';
import { renderRulebookBody } from '../../lib/rulebook-transform.ts';
import { injectRulebook } from '../../lib/sentinel-inliner.ts';
import { isMissingFile } from '../../lib/type-guards.ts';
import type { AmbientHostKind, HarnessId } from '../../lib/types.ts';
import type { ResolveRulebookContext } from './render-contexts.ts';
import type { SyncDomain } from './sync-domain.ts';

/** What a sync does to one ambient host: write the given content, or skip for the given reason. */
export type AmbientHostPlan =
  | { readonly kind: 'skip'; readonly reason: AmbientSkipReason }
  | { readonly kind: 'write'; readonly action: 'append' | 'create' | 'inject'; readonly content: string };

/** A probed ambient host: its content when present, plus how its region stands. */
export type AmbientHostState =
  { readonly status: 'missing' } | { readonly status: 'malformed' | 'no-region' | 'ready'; readonly content: string };

/** Why one ambient host is skipped. A stale install carries the probe status that names its remedy. */
export type AmbientSkipReason =
  | { readonly cause: 'damaged-region' }
  | { readonly cause: 'not-needed' }
  | { readonly cause: 'stale-install'; readonly status: 'malformed' | 'missing' | 'no-region' };

/**
 * Carries out each ambient host's plan, regenerating the region's content wholesale (an empty ambient set empties an
 * existing region). Both domains share this one path, differing only in the host each targets and in who owns region
 * creation there.
 */
export async function deliverAmbient(plans: ReadonlyArray<PlannedAmbientHost>): Promise<void> {
  for (const { hostPath, plan } of plans) {
    if (plan.kind === 'skip') {
      continue;
    }
    await writeIfChanged(hostPath, plan.content);
  }
}

/**
 * The hosts a sync writes that git does not ignore, so machine-local guidance does not quietly become a commit
 * candidate. Purely advisory: An ignored host is omitted, and so is one the check cannot answer for — the project may
 * not be a repository at all, which is no reason to fail a sync. A host the run skips is never asked about.
 */
export async function findUnignoredHosts(
  projectRoot: string,
  plans: ReadonlyArray<PlannedAmbientHost>,
): Promise<ReadonlyArray<string>> {
  const unignored: Array<string> = [];
  for (const { hostPath, plan } of plans) {
    if (plan.kind === 'write' && (await checkGitIgnored(projectRoot, hostPath)) === false) {
      unignored.push(hostPath);
    }
  }
  return unignored;
}

/** Pairs each probed host with the plan a sync carries out there, derived once so both paths read the same one. */
export function planAmbientHosts(
  probed: ReadonlyArray<ProbedAmbientHost>,
  domain: SyncDomain,
  resolved: ReadonlyArray<ResolvedRulebook>,
  resolveRulebookContext: ResolveRulebookContext,
): ReadonlyArray<PlannedAmbientHost> {
  return probed.map(({ harnessId, hostPath, state }) => ({
    hostPath,
    plan: planAmbientHost(domain.ambient, state, renderAmbientBody(resolved, harnessId, resolveRulebookContext)),
  }));
}

/** One targeted ambient host paired with the plan a sync carries out there. */
export interface PlannedAmbientHost {
  readonly hostPath: string;
  readonly plan: AmbientHostPlan;
}

/**
 * Reads the state of every guidance file whose ambient region a sync of `domain` targets — one per targeted harness,
 * each paired with the harness id its content is rendered for. Read once here rather than per consumer, so the
 * damaged-region gate and the delivery plan cannot disagree about what a host holds.
 */
export async function probeAmbientHosts(
  harnessIds: ReadonlyArray<HarnessId>,
  domain: SyncDomain,
): Promise<ReadonlyArray<ProbedAmbientHost>> {
  return Promise.all(
    harnessIds.map(async (harnessId) => {
      const hostPath = resolveAmbientHostPath(harnessId, domain.ambient, domain.baseDir);
      return { harnessId, hostPath, state: await probeAmbientHost(hostPath) };
    }),
  );
}

/** One targeted ambient host, the harness its content renders for, and the state a probe found there. */
export interface ProbedAmbientHost {
  readonly harnessId: HarnessId;
  readonly hostPath: string;
  readonly state: AmbientHostState;
}

// region | Helpers

/** The line an ambient region opens with, so a reader who finds generated guidance knows an edit there is lost. */
const ambientRegionNote =
  '<!-- Generated by `codeassembly sync` from the rulebooks named below. Edits inside this region are overwritten. -->';

/**
 * Decides what a sync does to one ambient host. The harness-home host is `install`'s to create, so anything but a
 * rendered region is skipped with the remedy named. The project-local host is sync's own, and is materialized only
 * when there is ambient content to carry: An absent host with nothing to deliver stays absent, matching how the
 * `prompts.yml` region and the legacy ambient host withdraw rather than persist empty.
 */
function planAmbientHost(hostKind: AmbientHostKind, host: AmbientHostState, body: string): AmbientHostPlan {
  if (host.status === 'ready') {
    return { kind: 'write', action: 'inject', content: injectAmbientRegion(host.content, body) };
  }
  if (hostKind === 'harness-home') {
    return { kind: 'skip', reason: { cause: 'stale-install', status: host.status } };
  }
  if (body === '') {
    return { kind: 'skip', reason: { cause: 'not-needed' } };
  }
  // A damaged region never reaches a write: `findDamagedAmbientHostDefects` has already failed the run.
  return host.status === 'malformed'
    ? { kind: 'skip', reason: { cause: 'damaged-region' } }
    : {
        kind: 'write',
        action: host.status === 'missing' ? 'create' : 'append',
        content: appendAmbientRegion(host.status === 'missing' ? '' : host.content, body),
      };
}

/** Probes an ambient host for its content and region state. */
async function probeAmbientHost(hostPath: string): Promise<AmbientHostState> {
  let content: string;
  try {
    content = await readFile(hostPath, 'utf8');
  } catch (error: unknown) {
    if (isMissingFile(error)) {
      return { status: 'missing' };
    }
    throw error;
  }
  switch (classifyAmbientRegion(content)) {
    case 'complete':
      return { status: 'ready', content };
    case 'malformed':
      return { status: 'malformed', content };
    case 'absent':
      return { status: 'no-region', content };
  }
}

/**
 * Renders the ambient rulebooks as concatenated sentinel blocks beneath the generated-region note — the wholesale
 * content of one harness's ambient region. The context is one harness's, so the same rulebook yields that harness's
 * own absolute paths. An empty result stays empty: the note belongs to generated content, and callers read emptiness
 * as "nothing to deliver here".
 */
function renderAmbientBody(
  resolved: ReadonlyArray<ResolvedRulebook>,
  harnessId: HarnessId,
  resolveRulebookContext: ResolveRulebookContext,
): string {
  let body = '';
  for (const rulebook of resolved) {
    if (!rulebook.ambient) {
      continue;
    }
    const context = resolveRulebookContext(harnessId, rulebook.source);
    body = injectRulebook(
      body,
      rulebook.slug,
      renderRulebookBody(rulebook.body, rulebook.slug, context),
      rulebook.version,
    );
  }
  // Prepend rather than seed the loop: seeding would route the note through `injectRulebook`, which separates it from
  // the first block with a blank line and would leave the note standing as the whole body when nothing is ambient.
  return body === '' ? '' : `${ambientRegionNote}\n${body}`;
}

// endregion | Helpers
