import { existsSync } from 'node:fs';
import { mkdir, readFile, rm, rmdir } from 'node:fs/promises';
import { homedir } from 'node:os';
import path from 'node:path';
import process from 'node:process';

import { describeError } from '@williamthorsen/toolbelt.errors';

import { appendAmbientRegion, classifyAmbientRegion, injectAmbientRegion } from '../../lib/ambient-region.ts';
import { ARTIFACT_TYPE_VALUES, artifactFrontmatterPath, type ArtifactType } from '../../lib/artifact-types.ts';
import { type ResolvedDeclaration, resolveDeclaration } from '../../lib/codeassembly-manifest.ts';
import {
  type ContentDefect,
  foldHarnessDefects,
  formatContentDefects,
  type HarnessDefect,
} from '../../lib/content-defects.ts';
import { resolveContentDir } from '../../lib/content-resolver.ts';
import {
  createSourceResolver,
  describeSearchedLocations,
  hasLibraryArtifact,
  type SourceResolver,
} from '../../lib/content-sources.ts';
import { listDeclaredGuidanceHooks } from '../../lib/declared-guidance-hooks.ts';
import { type DeclaredSource, resolveDeclaredSources } from '../../lib/declared-sources.ts';
import { type DirectArtifacts, resolveSeedClosures } from '../../lib/dependency-resolver.ts';
import { findCrossNamespaceCollisions, findSkillNameCollisions } from '../../lib/deploy-collisions.ts';
import { readDirEntries, readFileOrEmpty, writeIfChanged } from '../../lib/fs-helpers.ts';
import { checkGitIgnored } from '../../lib/git-ignore.ts';
import { type GuidanceHookFill, type GuidanceHookFills, listGuidanceHooks } from '../../lib/guidance-hooks.ts';
import { HARNESSES, resolveAmbientHostPath, resolveHarnessPaths } from '../../lib/harness.ts';
import { loadHarnessOverlay } from '../../lib/harness-overlay.ts';
import { type HomeFailure, recordFailedHomeAttempt, recordHomeProvenance } from '../../lib/home-provenance.ts';
import { assertDesignatedWriter } from '../../lib/home-writer-guard.ts';
import type { RulebookInvocationCatalog } from '../../lib/invocation-tokens.ts';
import { enumerateCatalogSlugs } from '../../lib/library-catalog.ts';
import {
  createContentRootLinkAnchor,
  createSkillLinkAnchor,
  type LinkAnchorContext,
  SOURCE_SUPPORT_DIR,
} from '../../lib/link-anchor.ts';
import { findUndeclaredGuidancePackages } from '../../lib/package-sources.ts';
import type { ResolveLinkAnchor } from '../../lib/path-rewriter.ts';
import { collectPromptEntries, renderPromptEntries } from '../../lib/prompts-yml.ts';
import { hasPromptsRegion, injectPromptsRegion, removePromptsRegion } from '../../lib/prompts-yml-region.ts';
import { type ResolvedRulebook, resolveRulebook } from '../../lib/rulebook-deploy.ts';
import { extractRulebookSkillSlug, renderSkillFile } from '../../lib/rulebook-skill.ts';
import { renderRulebookBody, type RulebookRenderContext } from '../../lib/rulebook-transform.ts';
import { resolveRunningPackageRoot } from '../../lib/running-package.ts';
import { extractInstalledSlugs, injectRulebook, removeRulebook } from '../../lib/sentinel-inliner.ts';
import { deploySkill, resolveDeclaredSkill, type ResolvedSkill, skillTargetsHarness } from '../../lib/skill-deploy.ts';
import { type RenderedSkillEntry, renderSkillDirectory, type SkillDeployContext } from '../../lib/skill-transform.ts';
import {
  deploySubagent,
  renderSubagent,
  resolveDeclaredSubagent,
  type ResolvedSubagent,
  type SubagentDeployContext,
} from '../../lib/subagent-deploy.ts';
import {
  deploySourceSupport,
  listUndeclaredSourceSupport,
  renderSourceSupport,
  retractUndeclaredSourceSupport,
  type SourceSupportOutcome,
} from '../../lib/support-deploy.ts';
import { type ResolvedHarnessTargets, resolveTargetHarnesses } from '../../lib/target-harnesses.ts';
import { isMissingFile } from '../../lib/type-guards.ts';
import type { AmbientHostKind, HarnessId, InstallOptions } from '../../lib/types.ts';
import {
  type DroppedHarnessRetraction,
  planDroppedHarnessRetractions,
  retractDroppedHarnesses,
} from './harness-retraction.ts';
import {
  listOwnedDeclaredSkills,
  listOwnedSkills,
  listOwnedSubagents,
  skillMarker,
  subagentMarker,
} from './owned-artifacts.ts';
import { isSyncValidationError, SyncValidationError } from './sync-validation-error.ts';

/** The line an ambient region opens with, so a reader who finds generated guidance knows an edit there is lost. */
const ambientRegionNote =
  '<!-- Generated by `codeassembly sync` from the rulebooks named below. Edits inside this region are overwritten. -->';

/**
 * One deployed artifact's resolution outcome: its type and slug, the source it resolved from (`undefined` = library),
 * and whether it masks a same-slug library artifact. Drives both the dry-run resolution report and the real-run shadow
 * warning.
 */
export interface ResolutionEntry {
  readonly type: ArtifactType;
  readonly slug: string;
  readonly source: string | undefined;
  readonly shadowsLibrary: boolean;
}

/** One targeted harness's project-local subagents dir paired with the per-harness inputs the deploy transform needs. */
export interface HarnessSubagentTarget {
  readonly harnessId: HarnessId;
  readonly subagentsDir: string;
  /** Everything but the anchor and the overlay, which the owning source decides and so are supplied per subagent. */
  readonly deployContext: Omit<SubagentDeployContext, 'anchor' | 'overlayYaml'>;
}

/** One targeted harness's ambient host, paired with the harness id whose paths its rulebook bodies render for. */
interface AmbientHostTarget {
  readonly harnessId: HarnessId;
  readonly hostPath: string;
}

/**
 * Builds one harness's rulebook render context. Threaded rather than rebuilt per call site so the pre-write gate,
 * ambient delivery, and skill delivery all render a rulebook body against the same anchor.
 */
type ResolveRulebookContext = (harnessId: HarnessId, supportNamespace: string | undefined) => RulebookRenderContext;

/**
 * Resolves the anchor inputs for one harness and one owning source (`undefined` = the built-in library). The owner is
 * a per-artifact input rather than a per-harness one, because only it distinguishes a link into a source's own support
 * tree from the same target written by a library artifact.
 */
type ResolveAnchorContext = (harnessId: HarnessId, supportNamespace: string | undefined) => LinkAnchorContext;

/**
 * Reads the frontmatter overlay one harness applies to subagents resolved from `contentRoot`. Source-scoped rather
 * than per-harness: a subagent merges against the overlay of the root it came from, so a source shipping none merges
 * against nothing.
 */
type ResolveOverlay = (harnessId: HarnessId, contentRoot: string) => Promise<string>;

/**
 * One source's support entries rendered for one harness, paired with the namespace directory they deploy into and
 * what delivery will do there: Write the entries, remove a namespace the source no longer fills, or nothing at all.
 * Carrying the verdict is what lets the preview describe the removals without re-deriving them from the tree that
 * delivery is about to change.
 */
export interface SourceSupportPlan {
  readonly sourcesRoot: string;
  readonly name: string;
  readonly destDir: string;
  readonly entries: ReadonlyArray<RenderedSkillEntry>;
  readonly kind: 'deliver' | 'retract' | 'none';
}

/** One targeted harness's id and project-local skills dir paired with the per-harness inputs the skill transform needs. */
export interface HarnessSkillTarget {
  readonly harnessId: HarnessId;
  readonly skillsDir: string;
  /** Everything but the anchor, which the owning source decides and so is supplied per skill. */
  readonly deployContext: Omit<SkillDeployContext, 'anchor'>;
}

/** A scope carrying no `codeassembly.yaml` to act on, and the tier whose remedy the report names. */
export interface MissingDeclaration {
  readonly kind: 'no-declaration';
  readonly declarationPath: string;
  readonly scope: 'global' | 'project';
}

/** What a sync resolved and what it did, or what it would have done under `--dry-run`. */
export type SyncOutcome = MissingDeclaration | { readonly kind: 'reconciled'; readonly plan: SyncPlan };

/**
 * Everything a sync resolved, and every write, retraction, and warning it produced. Both reports render from this one
 * plan, so a condition either can describe reaches the other in the same terms. The closing summary's counts are
 * derived from these same fields rather than carried alongside them, which is what keeps a count and the enumeration
 * it summarizes from disagreeing.
 */
export interface SyncPlan {
  readonly targets: ResolvedHarnessTargets;
  /** What each harness dropped by the declaration still holds from a previous sync, one entry per harness with any. */
  readonly droppedHarnesses: ReadonlyArray<DroppedHarnessRetraction>;
  readonly resolutionReport: ReadonlyArray<ResolutionEntry>;
  readonly ambientHosts: ReadonlyArray<PlannedAmbientHost>;
  /** Hosts the run writes that git does not ignore, so machine-local guidance does not become a commit candidate. */
  readonly unignoredHosts: ReadonlyArray<string>;
  readonly retirements: ReadonlyArray<Retirement>;
  readonly resolved: ReadonlyArray<ResolvedRulebook>;
  readonly harnessSkillTargets: ReadonlyArray<HarnessSkillTarget>;
  readonly skillOrphansByDir: ReadonlyArray<{ skillsDir: string; orphans: ReadonlyArray<string> }>;
  readonly resolvedSkills: ReadonlyArray<ResolvedSkill>;
  readonly declaredSkillOrphansByDir: ReadonlyArray<{ skillsDir: string; orphans: ReadonlyArray<string> }>;
  readonly resolvedSubagents: ReadonlyArray<ResolvedSubagent>;
  readonly harnessSubagentTargets: ReadonlyArray<HarnessSubagentTarget>;
  readonly subagentOrphansByDir: ReadonlyArray<{ subagentsDir: string; orphans: ReadonlyArray<string> }>;
  /** One entry per source that would deliver support content, naming its namespace dir and how many files land there. */
  readonly sourceSupportPlans: ReadonlyArray<SourceSupportPlan>;
  /** Namespace paths under each target's support root that no declared source claims. */
  readonly sourceSupportRetractions: ReadonlyArray<string>;
  readonly promptsYmlPaths: ReadonlyArray<string>;
  /** Declared sources whose directory does not exist, and so contribute nothing to resolution. */
  readonly missingSources: ReadonlyArray<DeclaredSource>;
  /** Dependencies shipping guidance the project has not declared. */
  readonly undeclaredPackages: ReadonlyArray<string>;
  /** Disagreements between the declaration's guidance-hook bindings and what those bindings reach. */
  readonly guidanceHookAdvisories: ReadonlyArray<GuidanceHookAdvisory>;
}

/**
 * A disagreement between what a declaration's guidance-hook bindings do and what they find: a rulebook whose
 * `delivery` answers the binding differently, or a hook no body declares. Every kind is advisory: A rulebook's
 * delivery is written by its author and a binding by its consumer, so a mismatch is not always the consumer's to fix
 * and never fails their run.
 *
 * `bound-unreached` is keyed on the hook rather than a rulebook, because one mistyped hook name strands every
 * rulebook bound under it at once.
 */
export type GuidanceHookAdvisory =
  | { readonly kind: 'bound-undeclared'; readonly slug: string; readonly hook: string }
  | { readonly kind: 'bound-unreached'; readonly hook: string }
  | { readonly kind: 'declared-unbound'; readonly slug: string };

/** A retired legacy output, and whether the host it names held nothing but retired blocks. */
export type Retirement =
  | { readonly kind: 'ambient-host'; readonly hostPath: string; readonly emptied: boolean }
  | { readonly kind: 'neutral-rulebooks'; readonly dir: string };

/** The one per-domain difference: the base dir to resolve and deploy under, and where ambient blocks land. */
export interface SyncDomain {
  readonly baseDir: string;
  /**
   * Which guidance file hosts this domain's ambient region. Both domains inject into a per-harness region; they
   * differ only in the host and in who creates it — `install` renders the harness-home region, while `sync` owns
   * the project-local one because `install` does not manage user-local files.
   */
  readonly ambient: AmbientHostKind;
  /**
   * Root that rendered links to this domain's own deployed trees are written under: `~` for the home domain, the
   * absolute project root for the project domain. Without it a project-deployed artifact addresses the home harness
   * dir, which a project sync never populates.
   */
  readonly anchorBase: string;
}

/**
 * Resolves a project's `codeassembly.yaml` scope chain and reconciles it into that project's harness dirs (the repo
 * domain). A thin wrapper over `reconcileDomain` that supplies the repo `SyncDomain`. An absent `codeassembly.yaml`
 * is a total no-op. The home directory decides targeting, through its declaration tier and the harnesses installed
 * under it.
 */
export async function syncCommand(
  options: InstallOptions,
  projectRoot: string = process.cwd(),
  contentDirOverride?: string,
  homeDir: string = homedir(),
): Promise<SyncOutcome> {
  if (path.resolve(projectRoot) === path.resolve(homeDir)) {
    throw new Error(
      'Refusing to run `sync` in the home directory: That would deploy the user-global tier through the project ' +
        'path. Run `sync --global` to sync the user-global tier into the home harness dirs.',
    );
  }
  return reconcileDomain(
    options,
    { baseDir: projectRoot, ambient: 'project-local', anchorBase: path.resolve(projectRoot) },
    homeDir,
    contentDirOverride,
  );
}

/**
 * Resolves the user-global `~/.agents/codeassembly.yaml` scope chain and reconciles it into the home harness dirs (the
 * home domain). A thin wrapper over `reconcileDomain` that supplies the home `SyncDomain`. Ambient blocks land in the
 * ambient region of each targeted harness's guidance file (e.g. `~/.claude/CLAUDE.md`), which the harness loads
 * mechanically; no agent-read host file is written. When the home declaration is absent, changes nothing and returns
 * the outcome naming `init --global` as the remedy.
 */
export async function syncGlobalCommand(
  options: InstallOptions,
  homeDir: string = homedir(),
  contentDirOverride?: string,
): Promise<SyncOutcome> {
  // Runs first, and before the dry-run gate: a preview must refuse wherever the real run would.
  await assertDesignatedWriter({
    command: 'sync --global',
    homeDir,
    packageRoot: resolveRunningPackageRoot(),
    shouldOverrideWriter: options.shouldOverrideWriter,
  });

  const declarationPath = path.join(homeDir, '.agents', 'codeassembly.yaml');
  if (!existsSync(declarationPath)) {
    return { kind: 'no-declaration', declarationPath, scope: 'global' };
  }
  let outcome: SyncOutcome;
  let retirement: Retirement | undefined;
  try {
    outcome = await reconcileDomain(
      options,
      { baseDir: homeDir, ambient: 'harness-home', anchorBase: '~' },
      homeDir,
      contentDirOverride,
    );
    retirement = await retireAmbientHost(options, path.join(homeDir, '.agents', 'GLOBAL.md'), true);
  } catch (error: unknown) {
    // Recorded past the designated-writer guard above, so an installation refused by the guard touches no home state.
    if (!options.dryRun) {
      await recordFailedHomeAttempt('sync --global', describeSyncFailure(error), homeDir);
    }
    throw error;
  }

  if (!options.dryRun) {
    await recordHomeProvenance('sync --global', homeDir);
  }

  if (retirement === undefined || outcome.kind !== 'reconciled') {
    return outcome;
  }
  return { ...outcome, plan: { ...outcome.plan, retirements: [...outcome.plan.retirements, retirement] } };
}

/**
 * Resolves the `codeassembly.yaml` scope chain under `domain.baseDir`, materializes each declared rulebook's neutral
 * body to `<baseDir>/.agents/rulebooks/<slug>.md`, delivers `ambient` rulebooks to `domain.ambient`'s target, writes
 * `skill` rulebooks as thin-wrapper skills into each targeted harness's skills dir, deploys declared skills and
 * subagents (the latter through the harness transform) into those harness dirs, and retracts anything no longer
 * declared. Installed state is derived from the filesystem, not a manifest, which keeps the command idempotent. An
 * absent `codeassembly.yaml` is a total no-op. Repo and home domains share this one reconciler, differing only in
 * the `SyncDomain` they pass.
 *
 * `homeDir` is a parameter rather than a `SyncDomain` field because it is the same directory in both domains: It
 * carries the user-global half of the `harnesses` chain and the harnesses targeting falls back to.
 */
async function reconcileDomain(
  options: InstallOptions,
  domain: SyncDomain,
  homeDir: string,
  contentDirOverride?: string,
): Promise<SyncOutcome> {
  const declaration = await resolveDeclaration({
    cwd: domain.baseDir,
    domain: domain.ambient === 'harness-home' ? 'home' : 'project',
  });
  if (declaration === undefined) {
    return {
      kind: 'no-declaration',
      declarationPath: path.join(domain.baseDir, '.agents', 'codeassembly.yaml'),
      scope: domain.ambient === 'harness-home' ? 'global' : 'project',
    };
  }

  const contentDir = contentDirOverride ?? resolveContentDir();

  // Resolution searches declared sources (highest precedence first) then the built-in library. Every declared source
  // is validated up front, so a non-directory or unreadable one fails the whole run — dry-run included — before any
  // write.
  const { sources, missingSources } = await resolveDeclaredSources({
    baseDir: domain.baseDir,
    contentDir,
    declaration,
  });
  const resolver = createSourceResolver(sources, contentDir);

  // Everything a declared package ships seeds the closure, which is what makes naming the package the whole
  // declaration. A package whose content dir is missing enumerates nothing: The walk reads through a directory listing
  // that answers an absent directory with no entries.
  const packageCatalogs = await Promise.all(
    sources.filter((source) => source.declaredAs === 'package').map((source) => enumerateCatalogSlugs(source.dir)),
  );

  // Every gate in this phase reports into one collector rather than throwing, so a run reports every defect it found
  // instead of its first. The list is raised below, before the first call that writes.
  const defects = createDefectCollector();

  // Checked before the closure resolves so a typo names the hook that bound it or the file that declared it;
  // seeding alone would report only that some artifact went missing.
  const bound = await findUnresolvableBindingDefects(declaration.guidanceHooks, resolver);
  defects.add(bound.defects);
  const declared = await findUnresolvableDeclaredArtifactDefects(
    declaration,
    domain.ambient === 'harness-home' ? 'home' : 'project',
    resolver,
  );
  defects.add(declared.defects);
  // A binding seeds the closure, so a bound rulebook resolving from nowhere joins the declared set skipped by the walk.
  const unresolvable: UnresolvableSlugs = {
    ...declared.unresolvable,
    rulebook: new Set([...declared.unresolvable.rulebook, ...bound.unresolvable]),
  };

  // Expand declared collections — and any artifact's own dependencies — into the deployable per-type sets before
  // resolving against the sources and library, so a declared collection deploys exactly its transitive closure.
  // The walk runs one seed at a time, so a bad edge is attributed to the artifact that owns it and every remaining
  // seed still resolves. A seed already reported as unresolvable is dropped, so it is not reported twice.
  const seeded = await resolveSeedClosures(
    dropUnresolvableSeeds(
      mergeSeeds([
        {
          rulebook: declaration.rulebooks,
          skill: declaration.skills,
          subagent: declaration.subagents,
          collection: declaration.collections,
        },
        // A binding is a dependency edge: a bound rulebook deploys per its own `delivery:` without being declared twice.
        { rulebook: [...new Set(declaration.guidanceHooks.values().toArray().flat())] },
        ...packageCatalogs,
      ]),
      unresolvable,
    ),
    resolver,
  );
  defects.add(seeded.defects);
  const closure = seeded.closure;
  const declaredRulebooks = closure.rulebooks;

  // Resolve and validate every declared rulebook, skill, and subagent before writing anything, so a missing library
  // file, invalid frontmatter, or a still-`install` artifact is reported rather than leaving a partial sync. Each pass
  // resolves what it can: an artifact reported here is simply absent from the passes below.
  const rulebookResolution = await resolveEachArtifact('rulebook', declaredRulebooks, (slug) =>
    resolveRulebook(slug, resolver),
  );
  const resolved = rulebookResolution.resolved;
  defects.add(rulebookResolution.defects);
  defects.add(findSkillNameCollisionDefects(resolved));
  defects.add(findBoundRulebookHookDefects(declaration.guidanceHooks, resolved));
  const skillResolution = await resolveEachArtifact('skill', closure.skills, (slug) =>
    resolveDeclaredSkill(slug, resolver),
  );
  const resolvedSkills = skillResolution.resolved;
  defects.add(skillResolution.defects);
  const subagentResolution = await resolveEachArtifact('subagent', closure.subagents, (slug) =>
    resolveDeclaredSubagent(slug, resolver),
  );
  const resolvedSubagents = subagentResolution.resolved;
  defects.add(subagentResolution.defects);

  // Maps each skill-delivery rulebook's stable slug to the directory its skill currently belongs in. Retraction
  // compares this against what each owned directory's marker reports, so a renamed skill retracts its old dir.
  const desiredSkillDirs = new Map(
    resolved.filter((rulebook) => rulebook.skill).map((rulebook) => [rulebook.slug, rulebook.skillName] as const),
  );

  // One catalog for every body that addresses a rulebook by token — rulebook, skill, and subagent alike — so no two
  // passes can disagree about what is addressable. The closure it indexes already holds a rulebook named only by a
  // skill's or subagent's token, since those tokens are dependency edges.
  const rulebookCatalog = buildRulebookInvocationCatalog(resolved);
  const declaredSkillSet = new Set(resolvedSkills.map((skill) => skill.slug));

  // Rulebook skills and declared skills share the project-local skills dirs. A directory name claimed by both
  // delivery namespaces would clobber, so reject the overlap before any write.
  defects.add(findCrossNamespaceCollisionDefects(desiredSkillDirs.values().toArray(), declaredSkillSet));

  // Every delivery pass below targets this one set of harnesses, and each renders its content for the harness it
  // lands on, so the set is resolved once and threaded rather than re-derived per pass.
  const targets = await resolveTargetHarnesses({ harness: options.harness, cwd: domain.baseDir, homeDir });
  const harnessIds = targets.harnessIds;

  // Resolved before every render gate, so the gates and the writes they guard cannot disagree about where a link
  // target lands. The deployed skill dirs it reads are settled above: `resolvedSkills` and `desiredSkillDirs` name
  // everything this run writes into a domain skills dir, and the collision gate has already proven them disjoint.
  const resolveAnchorContext: ResolveAnchorContext = (harnessId, supportNamespace) => {
    const config = HARNESSES[harnessId];
    return {
      supportNamespace,
      // Declared skills are filtered per harness because a skill may target only some; rulebook-delivered skill names
      // are not, because every skill-delivery rulebook is written to every targeted harness.
      deployedSkillDirs: new Set([
        ...resolvedSkills.filter((skill) => skillTargetsHarness(skill, harnessId)).map((skill) => skill.slug),
        ...desiredSkillDirs.values(),
      ]),
      domainBase: domain.anchorBase,
      guidanceFileName: config.guidanceFileName,
      homeDir: config.homeDir,
      skillsDirName: config.skillsDirName,
    };
  };

  const resolveRulebookContext: ResolveRulebookContext = (harnessId, supportNamespace) =>
    buildRulebookRenderContext(
      harnessId,
      resolved,
      createContentRootLinkAnchor(resolveAnchorContext(harnessId, supportNamespace)),
    );

  // Skill delivery targets project-local harness skills dirs, gated by detection (or `--harness`). Passing
  // `projectRoot` as the base is what keeps the skills project-scoped, and keeps tests out of the real home dir. Each
  // target carries the per-harness skill-transform inputs so declared-skill deployment applies include expansion and
  // tool-name/link rewriting, and the harness id each rulebook body renders for.
  // Rendered per harness, because a bound body carries that harness's link targets, sigils, and home dir. Built once
  // here so the skill pass and the subagent pass splice the same guidance.
  const fillsByHarness = new Map(
    harnessIds.map((harnessId) => [
      harnessId,
      buildGuidanceHookFills(declaration.guidanceHooks, resolved, harnessId, resolveRulebookContext),
    ]),
  );

  const harnessSkillTargets = harnessIds.map((harnessId) =>
    resolveSkillTarget(harnessId, domain.baseDir, rulebookCatalog, fillsByHarness.get(harnessId)),
  );

  // Subagent delivery targets each harness's project-local subagents dir. Resolved separately from skills because the
  // transform is harness-specific, and subagents live in a distinct flat dir from skills.
  const declaredSubagentSet = new Set(resolvedSubagents.map((subagent) => subagent.slug));
  const harnessSubagentTargets = harnessIds.map((harnessId) =>
    resolveSubagentTarget(harnessId, domain.baseDir, rulebookCatalog, fillsByHarness.get(harnessId)),
  );

  // Memoized, so the pre-write render gate and the write that follows it read one overlay per (harness, source)
  // rather than one per subagent.
  const resolveOverlay = createOverlayLoader();

  // A skill dir is sync-owned only when its `SKILL.md` carries the provenance marker; that gate is what keeps
  // hand-authored skills safe. An owned dir is an orphan when its marker slug no longer maps to that directory —
  // because the rulebook is no longer skill-delivered, or because its resolved skill name (and dir) changed.
  const skillOrphansByDir = await Promise.all(
    harnessSkillTargets.map(async ({ harnessId, skillsDir }) => ({
      harnessId,
      skillsDir,
      orphans: (await listOwnedSkills(skillsDir))
        .filter(({ dir, slug }) => desiredSkillDirs.get(slug) !== dir)
        .map(({ dir }) => dir),
    })),
  );
  // Declared-skill orphans reconcile per harness, reading only the declared-skill marker so the two namespaces never
  // consider each other's dirs. An owned declared-skill dir in a harness is an orphan once its slug is no longer among
  // the declared skills that target that harness — covering both an undeclared skill and one that dropped this harness.
  const declaredSkillOrphansByDir = await Promise.all(
    harnessSkillTargets.map(async ({ skillsDir, harnessId }) => {
      const targetedSlugs = new Set(
        resolvedSkills.filter((skill) => skillTargetsHarness(skill, harnessId)).map((skill) => skill.slug),
      );
      return {
        skillsDir,
        orphans: (await listOwnedDeclaredSkills(skillsDir))
          .filter(({ slug }) => !targetedSlugs.has(slug))
          .map(({ dir }) => dir),
      };
    }),
  );
  // Declared subagents reconcile file-based (flat `.md` files, not directories): An owned subagent file is one whose
  // content carries the `codeassembly-subagent:` marker. It is an orphan once its slug is no longer declared. A
  // marker-less hand-authored file is never claimed, so it survives untouched.
  const subagentOrphansByDir = await Promise.all(
    harnessSubagentTargets.map(async (target) => ({
      subagentsDir: target.subagentsDir,
      orphans: (await listOwnedSubagents(target.subagentsDir))
        .filter(({ slug }) => !declaredSubagentSet.has(slug))
        .map(({ file }) => file),
    })),
  );

  // Before any write or delete, fail closed on any skill or subagent target that already exists without this sync's
  // ownership marker — an install-managed or hand-authored file. The marker-gated retraction scans keep such files
  // from being deleted; this keeps them from being overwritten. Runs in dry-run too, so a preview surfaces the conflict.
  defects.add(
    await findForeignOwnedTargetDefects(
      collectOwnedTargets(harnessSkillTargets, resolved, resolvedSkills, harnessSubagentTargets, resolvedSubagents),
    ),
  );

  // Render every declared skill against every targeted harness up front, so a broken include or an unmapped tool
  // placeholder fails the whole run — dry-run included — before any file is written. The rendered output is discarded
  // here; `deploySkill` re-renders it at write time.
  defects.add(await findDeclaredSkillRenderDefects(harnessSkillTargets, resolvedSkills, resolveAnchorContext));

  // Same gate for each source's support entries, whose defects would otherwise surface only at the write below. The
  // rendered result is carried to the preview and the delivery pass rather than rendered again by each.
  const sourceSupport = await renderSourceSupportPlans(harnessSkillTargets, sources, resolveAnchorContext);
  const sourceSupportPlans = sourceSupport.plans;
  defects.add(sourceSupport.defects);

  // Same gate for subagents, whose deploy is the last write pass: Without it a render failure lands after the ambient
  // host and every skill file are already on disk.
  defects.add(
    await findDeclaredSubagentRenderDefects(
      harnessSubagentTargets,
      resolvedSubagents,
      resolveAnchorContext,
      resolveOverlay,
    ),
  );

  // Same gate for rulebooks: A link target the delivery pipeline cannot honor fails the run before either delivery
  // pass writes, rather than shipping a path that resolves to nothing.
  defects.add(findRulebookRenderDefects(harnessIds, resolved, resolveRulebookContext));

  // Reject a sync-owned ambient host whose region is half-written before anything is written, dry-run included.
  // Appending beside a stray marker is the one path in this command that can destroy hand-authored content.
  const ambientHosts = resolveAmbientHosts(harnessIds, domain);
  defects.add(await findDamagedAmbientHostDefects(ambientHosts, domain, resolved));

  // Every gate above has reported. Raised here, ahead of `retireRetiredOutputs`, which is the first call in this
  // phase that writes, so a failing run leaves the previously deployed guidance exactly as it found it.
  if (defects.found.length > 0) {
    throw new SyncValidationError(defects.found);
  }

  // Attribute each deployed artifact to the source it resolved from, flagging any that shadows a same-slug library
  // artifact. Built once, off the write path, and consumed by both the dry-run report and the real-run shadow warning.
  const resolutionReport = await buildResolutionReport(resolver, resolved, resolvedSkills, resolvedSubagents);

  // Derived before the paths part, so a dry run cannot describe an ambient host differently from the run it previews.
  const ambientHostPlans = await planAmbientHosts(ambientHosts, domain, resolved, resolveRulebookContext);

  // Advisory only, and gathered for both paths: a dry run that would create the host warns about it too.
  const unignoredHosts =
    domain.ambient === 'project-local' ? await findUnignoredHosts(domain.baseDir, ambientHostPlans) : [];

  // Read after the render gates above, which is what leaves a malformed directive to fail from the gate that can
  // name its body and line rather than from this pass.
  const declaredHooks = await listDeclaredGuidanceHooks(resolvedSkills, resolvedSubagents, harnessIds);

  const retirements = await retireRetiredOutputs(options, domain);

  const plan: SyncPlan = {
    targets,
    droppedHarnesses: await planDroppedHarnessRetractions({
      targets,
      baseDir: domain.baseDir,
      ambient: domain.ambient,
    }),
    resolutionReport,
    ambientHosts: ambientHostPlans,
    unignoredHosts,
    retirements,
    resolved,
    harnessSkillTargets,
    skillOrphansByDir,
    resolvedSkills,
    declaredSkillOrphansByDir,
    resolvedSubagents,
    harnessSubagentTargets,
    subagentOrphansByDir,
    sourceSupportPlans,
    sourceSupportRetractions: await planSourceSupportRetractions(harnessSkillTargets, sourceSupportPlans),
    promptsYmlPaths: resolvePromptsYmlPaths(harnessIds, domain),
    missingSources,
    // Otherwise a consumer has to learn a third party's catalog by hand to discover there is anything to adopt. This
    // is advice, not action: Nothing is deployed until the project declares the package.
    undeclaredPackages: await findUndeclaredGuidancePackages(
      [...declaration.packages, ...declaration.declinedPackages],
      domain.baseDir,
    ),
    guidanceHookAdvisories: findGuidanceHookAdvisories(declaration.guidanceHooks, resolved, declaredHooks),
  };

  if (options.dryRun) {
    return { kind: 'reconciled', plan };
  }

  // First write of the run, so a harness leaving the target set is cleared before anything is delivered to the ones
  // that remain. Its paths are disjoint from every targeted harness's, so the order costs the delivery passes nothing.
  await retractDroppedHarnesses(plan.droppedHarnesses);

  await deliverAmbient(ambientHostPlans);

  // Reconcile skill files per targeted harness: Retract sync-owned skill dirs that are no longer current, then
  // write every skill-delivery rulebook. Orphans were computed against the pre-write filesystem, so retracting
  // before writing lets a skill name freed by one rulebook be recreated for another in the same sync, instead
  // of the write being clobbered by a later retract.
  for (const { harnessId, skillsDir, orphans } of skillOrphansByDir) {
    for (const dir of orphans) {
      await rm(path.join(skillsDir, dir), { recursive: true, force: true });
    }
    for (const rulebook of resolved) {
      if (!rulebook.skill) {
        continue;
      }
      const skillDir = path.join(skillsDir, rulebook.skillName);
      await mkdir(skillDir, { recursive: true });
      await writeIfChanged(
        path.join(skillDir, 'SKILL.md'),
        renderSkillFile({
          body: renderRulebookBody(rulebook.body, rulebook.slug, resolveRulebookContext(harnessId, rulebook.source)),
          description: rulebook.description,
          skillName: rulebook.skillName,
          slug: rulebook.slug,
          version: rulebook.version,
        }),
      );
    }
  }

  // Reconcile declared skills per targeted harness, independently of the rulebook-skill pass above: Retract owned
  // declared-skill dirs no longer declared, then deploy each declared skill into `<skillsDir>/<slug>/`.
  await reconcileDeclaredSkills(harnessSkillTargets, declaredSkillOrphansByDir, resolvedSkills, resolveAnchorContext);

  // Deliver each source's support entries into its own namespace, then retract the namespaces no source claims.
  await reconcileSourceSupport(harnessSkillTargets, sourceSupportPlans);

  // Reconcile declared subagents per targeted harness, independently of the skill passes: Retract owned subagent
  // files no longer declared, then deploy each declared subagent as `<subagentsDir>/<slug>.md` with the harness
  // transform applied and the ownership marker stamped.
  await reconcileDeclaredSubagents(
    harnessSubagentTargets,
    subagentOrphansByDir,
    resolvedSubagents,
    resolveAnchorContext,
    resolveOverlay,
  );

  await refreshPromptsYml(harnessIds, domain);

  return { kind: 'reconciled', plan };
}

// region | Helpers

/**
 * Concatenates per-type seed sets into the one set that seeds closure resolution. Deduping is deliberately left out:
 * `resolveClosure` already dedupes by slug as it walks, so a slug both declared directly and enumerated from a
 * package's catalog is visited once.
 */
function mergeSeeds(sets: ReadonlyArray<DirectArtifacts>): DirectArtifacts {
  const merged: Record<ArtifactType, Array<string>> = { rulebook: [], skill: [], subagent: [], collection: [] };
  for (const set of sets) {
    for (const type of ARTIFACT_TYPE_VALUES) {
      merged[type].push(...(set[type] ?? []));
    }
  }
  return merged;
}

/**
 * Describes a failed home-domain sync for the provenance record, carrying the whole defect report where the failure
 * has one. The report is held for a reader who opens the stamp; `status` prints the count alone, because a stored
 * report describes the content as it stood at the attempt rather than as it stands now.
 */
function describeSyncFailure(error: unknown): HomeFailure {
  return isSyncValidationError(error)
    ? { summary: formatContentDefects(error.defects), defectCount: error.defects.length }
    : { summary: describeError(error) };
}

/** Collects the defects reported by a sync's pre-write gates, so the run fails once on the whole list. */
interface DefectCollector {
  readonly found: ReadonlyArray<ContentDefect>;
  add(found: ReadonlyArray<ContentDefect>): void;
}

/** Builds the collector every pre-write gate reports into. */
function createDefectCollector(): DefectCollector {
  const collected: Array<ContentDefect> = [];
  return {
    add(found) {
      collected.push(...found);
    },
    get found() {
      return collected;
    },
  };
}

/** Declared slugs per type that resolve from nowhere, so the closure walk can skip a seed already reported. */
type UnresolvableSlugs = Record<ArtifactType, ReadonlySet<string>>;

/**
 * Drops every seed already reported as unresolvable, so the closure walk does not report the same slug a second time
 * as a missing edge. A slug reachable only through a dropped seed is unreported here, and the dropped seed's own
 * defect is what sends the reader to it.
 */
function dropUnresolvableSeeds(seeds: DirectArtifacts, unresolvable: UnresolvableSlugs): DirectArtifacts {
  const kept: Record<ArtifactType, Array<string>> = { rulebook: [], skill: [], subagent: [], collection: [] };
  for (const type of ARTIFACT_TYPE_VALUES) {
    kept[type] = (seeds[type] ?? []).filter((slug) => !unresolvable[type].has(slug));
  }
  return kept;
}

/**
 * Resolves each slug, reporting the ones that fail rather than abandoning the rest. What resolved is what the passes
 * below run over, so an artifact reported here is absent from them rather than carried forward half-resolved.
 */
async function resolveEachArtifact<T>(
  type: ArtifactType,
  slugs: ReadonlyArray<string>,
  resolve: (slug: string) => Promise<T>,
): Promise<{ resolved: ReadonlyArray<T>; defects: ReadonlyArray<ContentDefect> }> {
  const resolved: Array<T> = [];
  const defects: Array<ContentDefect> = [];
  for (const slug of slugs) {
    try {
      resolved.push(await resolve(slug));
    } catch (error: unknown) {
      defects.push({ file: artifactFrontmatterPath(type, slug), kind: 'resolution', detail: describeError(error) });
    }
  }
  return { resolved, defects };
}

/** A planned write whose destination must be sync-owned (or absent) before the write proceeds. */
interface OwnedTarget {
  readonly filePath: string;
  readonly isOwned: (content: string) => boolean;
}

/**
 * Reports each guidance-hook binding naming a rulebook that resolves from no declared source or the library, naming
 * both the slug and the hook that bound it. Seeding the closure would catch the same slug, but only as an anonymous
 * missing reference: the hook name is the half that says where to go and fix it.
 */
async function findUnresolvableBindingDefects(
  bindings: ReadonlyMap<string, ReadonlyArray<string>>,
  resolver: SourceResolver,
): Promise<{ defects: ReadonlyArray<ContentDefect>; unresolvable: ReadonlySet<string> }> {
  const defects: Array<ContentDefect> = [];
  const unresolvable = new Set<string>();
  for (const [hook, slugs] of bindings) {
    for (const slug of slugs) {
      if ((await resolver.resolve('rulebook', slug)) !== undefined) {
        continue;
      }
      unresolvable.add(slug);
      defects.push({
        file: artifactFrontmatterPath('rulebook', slug),
        kind: 'resolution',
        detail:
          `Guidance hook "${hook}" binds rulebook "${slug}", which was not found in any of: ` +
          describeSearchedLocations(resolver, 'rulebook', slug),
      });
    }
  }
  return { defects, unresolvable };
}

/**
 * Reports each artifact a declaration's own `use:` list names that resolves from no declared source or the
 * library, naming the chain files that declare it alongside the slug. The closure catches the same slug, but only
 * as an anonymous missing reference: The declaring file is the half that says where to go and fix it, and a path
 * derived from the domain cannot supply it, since either tier of the chain could have named the slug.
 */
async function findUnresolvableDeclaredArtifactDefects(
  declaration: ResolvedDeclaration,
  scope: 'home' | 'project',
  resolver: SourceResolver,
): Promise<{ defects: ReadonlyArray<ContentDefect>; unresolvable: UnresolvableSlugs }> {
  const defects: Array<ContentDefect> = [];
  const unresolvable: Record<ArtifactType, Set<string>> = {
    rulebook: new Set(),
    skill: new Set(),
    subagent: new Set(),
    collection: new Set(),
  };
  for (const type of ARTIFACT_TYPE_VALUES) {
    const declared = declaration.declaredIn[type];
    for (const [slug, declaredIn] of declared) {
      if ((await resolver.resolve(type, slug)) !== undefined) {
        continue;
      }

      unresolvable[type].add(slug);
      defects.push({
        file: artifactFrontmatterPath(type, slug),
        kind: 'resolution',
        detail:
          `The ${scope} declaration (${declaredIn.join(', ')}) declares ${type} "${slug}", which was not found ` +
          `in any of: ${describeSearchedLocations(resolver, type, slug)}`,
      });
    }
  }
  return { defects, unresolvable };
}

/**
 * Reports each bound rulebook whose own body declares a guidance hook. Bound guidance is spliced as rendered, so a hook
 * inside it has no pass left that could fill it. Checked here, against the unrendered body, because the rulebook
 * renderer strips the directive and the evidence is gone by the time a fill is built.
 */
function findBoundRulebookHookDefects(
  bindings: ReadonlyMap<string, ReadonlyArray<string>>,
  resolved: ReadonlyArray<ResolvedRulebook>,
): ReadonlyArray<ContentDefect> {
  const defects: Array<ContentDefect> = [];
  const bySlug = indexRulebooksBySlug(resolved);
  for (const [hook, slugs] of bindings) {
    for (const slug of slugs) {
      // A bound rulebook rejected by the resolution pass is absent from the closure, and its own defect already names it.
      const bound = bySlug.get(slug);
      if (bound === undefined) {
        continue;
      }
      const declared = listGuidanceHooks(bound.body, `guidance/rulebooks/${slug}.md`);
      if (declared.length > 0) {
        const names = declared.map((declaration) => declaration.name).join(', ');
        defects.push({
          file: artifactFrontmatterPath('rulebook', slug),
          kind: 'frontmatter',
          detail:
            `Rulebook "${slug}", bound to guidance hook "${hook}", declares a guidance hook of its own (${names}). ` +
            'Bound guidance is spliced as rendered, so nothing can fill a hook inside it: remove the directive, or ' +
            'bind a rulebook that carries none.',
        });
      }
    }
  }
  return defects;
}

/**
 * Renders one harness's guidance-hook fills: each bound rulebook's body through the rulebook renderer, keyed by the
 * hook it fills and ordered as the declaration bound it. Rendering here rather than at the splice is what makes the
 * spliced body position-independent, since link targets and invocation tokens are resolved before it moves.
 */
function buildGuidanceHookFills(
  bindings: ReadonlyMap<string, ReadonlyArray<string>>,
  resolved: ReadonlyArray<ResolvedRulebook>,
  harnessId: HarnessId,
  resolveRulebookContext: ResolveRulebookContext,
): GuidanceHookFills {
  const bySlug = indexRulebooksBySlug(resolved);
  const fills = new Map<string, ReadonlyArray<GuidanceHookFill>>();
  for (const [hook, slugs] of bindings) {
    fills.set(
      hook,
      slugs.flatMap((slug) => {
        // A bound rulebook rejected by the resolution or render gate is left out rather than raised again here: its own
        // defect names it, and the run fails on the collected list before anything is written.
        const rulebook = bySlug.get(slug);
        if (rulebook === undefined) {
          return [];
        }
        try {
          const context = resolveRulebookContext(harnessId, rulebook.source);
          return [{ slug, body: renderRulebookBody(rulebook.body, slug, context), version: rulebook.version }];
        } catch {
          return [];
        }
      }),
    );
  }
  return fills;
}

/**
 * Collects every disagreement between the rulebooks a declaration binds and the delivery those rulebooks declare.
 * No disagreement throws: Each reaches the reader as a report line, because a binding and a `delivery` are written by
 * different people and a run whose output is correct must not fail over their disagreement.
 *
 * Order is fixed so both reports render alike: The bound findings follow the bindings in declaration order, each
 * hook's own finding ahead of its rulebooks', and the unbound ones follow `resolved`, whose order the closure walk
 * fixes.
 */
function findGuidanceHookAdvisories(
  bindings: ReadonlyMap<string, ReadonlyArray<string>>,
  resolved: ReadonlyArray<ResolvedRulebook>,
  declaredHooks: ReadonlySet<string>,
): ReadonlyArray<GuidanceHookAdvisory> {
  const bySlug = indexRulebooksBySlug(resolved);
  const advisories: Array<GuidanceHookAdvisory> = [];
  const boundSlugs = new Set<string>();

  for (const [hook, slugs] of bindings) {
    // Reported once for the hook rather than per rulebook: The binding delivers nothing, whatever it names.
    if (!declaredHooks.has(hook)) {
      advisories.push({ kind: 'bound-unreached', hook });
    }
    for (const slug of slugs) {
      boundSlugs.add(slug);
      const rulebook = readBoundRulebook(bySlug, slug, hook);
      if (!rulebook.hook) {
        advisories.push({ kind: 'bound-undeclared', slug, hook });
      }
    }
  }

  for (const rulebook of resolved) {
    // Measured against every hook's bindings at once: A rulebook bound anywhere has taken the route it declares.
    if (rulebook.hook && !boundSlugs.has(rulebook.slug)) {
      advisories.push({ kind: 'declared-unbound', slug: rulebook.slug });
    }
  }

  return advisories;
}

/** Indexes resolved rulebooks by slug, so a binding reaches its body without rescanning the list per lookup. */
function indexRulebooksBySlug(resolved: ReadonlyArray<ResolvedRulebook>): ReadonlyMap<string, ResolvedRulebook> {
  return new Map(resolved.map((rulebook) => [rulebook.slug, rulebook]));
}

/**
 * Returns the resolved rulebook a binding names. A binding seeds the closure, so its absence here is a defect in this
 * command rather than in what the user declared, and it is reported as one.
 */
function readBoundRulebook(
  bySlug: ReadonlyMap<string, ResolvedRulebook>,
  slug: string,
  hook: string,
): ResolvedRulebook {
  const rulebook = bySlug.get(slug);
  if (rulebook === undefined) {
    throw new Error(`Rulebook "${slug}", bound to guidance hook "${hook}", did not reach the deploy closure.`);
  }
  return rulebook;
}

/**
 * Reports every planned target that already exists without this sync's ownership marker — an install-managed or
 * hand-authored file. Failing here, before any write or delete, is what keeps a same-named foreign file from being
 * overwritten; the marker-gated retraction scans separately keep it from being deleted. Absent targets are safe.
 */
async function findForeignOwnedTargetDefects(
  targets: ReadonlyArray<OwnedTarget>,
): Promise<ReadonlyArray<ContentDefect>> {
  const defects: Array<ContentDefect> = [];
  for (const target of targets) {
    let content: string;
    try {
      content = await readFile(target.filePath, 'utf8');
    } catch (error: unknown) {
      if (isMissingFile(error)) {
        continue;
      }
      throw error;
    }
    if (!target.isOwned(content)) {
      defects.push({
        file: target.filePath,
        kind: 'target',
        detail:
          'Refusing to overwrite a file not owned by sync (install-managed or hand-authored). Rename or remove it, ' +
          'or retire the conflicting install artifact, then re-run.',
      });
    }
  }
  return defects;
}

/**
 * Collects the skill and subagent destinations a sync would write, each paired with the predicate that recognizes its
 * own ownership marker, so the pre-write guard can reject any that already exist foreign-owned.
 */
function collectOwnedTargets(
  harnessSkillTargets: ReadonlyArray<HarnessSkillTarget>,
  resolved: ReadonlyArray<ResolvedRulebook>,
  resolvedSkills: ReadonlyArray<ResolvedSkill>,
  harnessSubagentTargets: ReadonlyArray<HarnessSubagentTarget>,
  resolvedSubagents: ReadonlyArray<ResolvedSubagent>,
): ReadonlyArray<OwnedTarget> {
  const targets: Array<OwnedTarget> = [];
  for (const { skillsDir, harnessId } of harnessSkillTargets) {
    for (const rulebook of resolved) {
      if (rulebook.skill) {
        targets.push({
          filePath: path.join(skillsDir, rulebook.skillName, 'SKILL.md'),
          isOwned: (content) => extractRulebookSkillSlug(content) !== undefined,
        });
      }
    }
    for (const skill of resolvedSkills) {
      if (!skillTargetsHarness(skill, harnessId)) {
        continue;
      }
      targets.push({
        filePath: path.join(skillsDir, skill.slug, 'SKILL.md'),
        isOwned: (content) => skillMarker.extractSlug(content) !== undefined,
      });
    }
  }
  for (const target of harnessSubagentTargets) {
    for (const subagent of resolvedSubagents) {
      targets.push({
        filePath: path.join(target.subagentsDir, `${subagent.slug}.md`),
        isOwned: (content) => subagentMarker.extractSlug(content) !== undefined,
      });
    }
  }
  return targets;
}

/**
 * Reports each rulebook-skill directory name colliding with a declared-skill directory name, which would let the two
 * delivery namespaces clobber each other in a shared project-local skills dir. Failing here, before any write,
 * forces the conflict to be resolved by renaming one side rather than letting the last write win.
 */
function findCrossNamespaceCollisionDefects(
  rulebookSkillDirs: ReadonlyArray<string>,
  declaredSkillSlugs: ReadonlySet<string>,
): ReadonlyArray<ContentDefect> {
  return findCrossNamespaceCollisions(rulebookSkillDirs, declaredSkillSlugs).map((name) => ({
    file: artifactFrontmatterPath('skill', name),
    kind: 'collision',
    detail:
      `Skill directory name collision across delivery namespaces: ${name} is delivered as both a rulebook skill ` +
      'and a declared skill. Rename one so they no longer share a directory.',
  }));
}

/**
 * Reports every pair of skill-delivery rulebooks resolving to the same skill name, which would share one directory and
 * clobber each other. Failing here, before any write, forces the conflict to be resolved with a `skill-name`
 * override rather than silently letting the last write win.
 */
function findSkillNameCollisionDefects(resolved: ReadonlyArray<ResolvedRulebook>): ReadonlyArray<ContentDefect> {
  return findSkillNameCollisions(resolved).map((collision) => ({
    file: artifactFrontmatterPath('rulebook', collision.slugs[0] ?? collision.skillName),
    kind: 'collision',
    detail:
      `Skill name collision: rulebooks ${collision.slugs.join(', ')} all resolve to skill "${collision.skillName}". ` +
      'Give all but one a distinct `skill-name`.',
  }));
}

/**
 * Retracts owned subagent files no longer declared, then deploys each declared subagent into every targeted harness's
 * subagents dir. Orphans were computed against the pre-write filesystem, so retracting before writing lets a slug
 * freed in one dir be re-created in the same sync rather than clobbered by a later retract.
 */
async function reconcileDeclaredSubagents(
  targets: ReadonlyArray<HarnessSubagentTarget>,
  orphansByDir: ReadonlyArray<{ subagentsDir: string; orphans: ReadonlyArray<string> }>,
  resolvedSubagents: ReadonlyArray<ResolvedSubagent>,
  resolveAnchorContext: ResolveAnchorContext,
  resolveOverlay: ResolveOverlay,
): Promise<void> {
  for (const target of targets) {
    const orphans = orphansByDir.find((entry) => entry.subagentsDir === target.subagentsDir)?.orphans ?? [];
    for (const file of orphans) {
      await rm(path.join(target.subagentsDir, file), { force: true });
    }
    for (const subagent of resolvedSubagents) {
      await deploySubagent(subagent, path.join(target.subagentsDir, `${subagent.slug}.md`), {
        ...target.deployContext,
        anchor: createContentRootLinkAnchor(resolveAnchorContext(target.harnessId, subagent.source)),
        overlayYaml: await resolveOverlay(target.harnessId, subagent.contentRoot),
      });
    }
  }
}

/**
 * Retracts owned declared-skill dirs no longer declared, then deploys each declared skill into every targeted harness's
 * skills dir with that harness's transform applied. Orphans were computed against the pre-write filesystem, so
 * retracting before writing lets a slug freed in one dir be re-created in the same sync rather than clobbered.
 */
async function reconcileDeclaredSkills(
  targets: ReadonlyArray<HarnessSkillTarget>,
  orphansByDir: ReadonlyArray<{ skillsDir: string; orphans: ReadonlyArray<string> }>,
  resolvedSkills: ReadonlyArray<ResolvedSkill>,
  resolveAnchorContext: ResolveAnchorContext,
): Promise<void> {
  for (const target of targets) {
    const orphans = orphansByDir.find((entry) => entry.skillsDir === target.skillsDir)?.orphans ?? [];
    for (const dir of orphans) {
      await rm(path.join(target.skillsDir, dir), { recursive: true, force: true });
    }
    for (const skill of resolvedSkills) {
      if (!skillTargetsHarness(skill, target.harnessId)) {
        continue;
      }
      await deploySkill(skill, path.join(target.skillsDir, skill.slug), {
        ...target.deployContext,
        anchor: createSkillLinkAnchor(resolveAnchorContext(target.harnessId, skill.source)),
      });
    }
  }
}

/**
 * Delivers each source's skill support entries into that source's namespace under every targeted harness's skills dir,
 * then retracts the namespaces no declared source claims. Delivery runs first so a source that dropped its last
 * support entry leaves an empty namespace root for the retraction to retire in the same pass.
 */
async function reconcileSourceSupport(
  targets: ReadonlyArray<HarnessSkillTarget>,
  plans: ReadonlyArray<SourceSupportPlan>,
): Promise<void> {
  for (const plan of plans) {
    await deploySourceSupport(plan.destDir, plan.entries);
  }
  // Rooted in the targets rather than the plans: a run that declares no source has no plans, and its support roots
  // are exactly the ones whose every namespace is now undeclared.
  for (const sourcesRoot of resolveSupportRoots(targets)) {
    await retractUndeclaredSourceSupport(sourcesRoot, resolveSupportOutcome(plans, sourcesRoot));
  }
}

/** Lists the support root each targeted harness keeps its per-source namespaces under. */
function resolveSupportRoots(targets: ReadonlyArray<HarnessSkillTarget>): ReadonlyArray<string> {
  return targets.map((target) => path.join(target.skillsDir, SOURCE_SUPPORT_DIR));
}

/** Groups one support root's plans into what delivery leaves there: the namespaces that hold content, and the rest. */
function resolveSupportOutcome(plans: ReadonlyArray<SourceSupportPlan>, sourcesRoot: string): SourceSupportOutcome {
  const rooted = plans.filter((plan) => plan.sourcesRoot === sourcesRoot);
  return {
    surviving: rooted.filter((plan) => plan.kind === 'deliver').map((plan) => plan.name),
    emptied: rooted.filter((plan) => plan.kind !== 'deliver').map((plan) => plan.name),
  };
}

/**
 * Renders every source's support entries for every targeted harness, pairing each result with where it deploys.
 *
 * Rendering is where a defect in a package's reference content surfaces, so calling this ahead of every write is what
 * fails the run — dry-run included — before anything lands. The gate, the dry-run preview, and the delivery pass all
 * read this one result, which is what keeps them from disagreeing about what a source ships and from rendering the
 * same content more than once.
 */
async function renderSourceSupportPlans(
  targets: ReadonlyArray<HarnessSkillTarget>,
  sources: ReadonlyArray<{ name: string; dir: string }>,
  resolveAnchorContext: ResolveAnchorContext,
): Promise<{ plans: ReadonlyArray<SourceSupportPlan>; defects: ReadonlyArray<ContentDefect> }> {
  const plans: Array<SourceSupportPlan> = [];
  const raised: Array<HarnessDefect> = [];
  for (const target of targets) {
    const sourcesRoot = path.join(target.skillsDir, SOURCE_SUPPORT_DIR);
    for (const source of sources) {
      const destDir = path.join(sourcesRoot, source.name);
      let entries: ReadonlyArray<RenderedSkillEntry>;
      try {
        entries = await renderSourceSupport(source.dir, {
          ...target.deployContext,
          anchor: createSkillLinkAnchor(resolveAnchorContext(target.harnessId, source.name)),
        });
      } catch (error: unknown) {
        raised.push({
          harnessId: target.harnessId,
          defect: { file: path.join(source.dir, SOURCE_SUPPORT_DIR), kind: 'render', detail: describeError(error) },
        });
        continue;
      }
      plans.push({
        sourcesRoot,
        name: source.name,
        destDir,
        entries,
        kind: resolveSupportVerdict(entries.length > 0, existsSync(destDir)),
      });
    }
  }
  return {
    plans,
    defects: foldHarnessDefects(
      raised,
      targets.map((target) => target.harnessId),
    ),
  };
}

/** Names what delivery does at a namespace directory, given whether its source ships content and whether it exists. */
function resolveSupportVerdict(shipsContent: boolean, destExists: boolean): SourceSupportPlan['kind'] {
  if (shipsContent) {
    return 'deliver';
  }
  return destExists ? 'retract' : 'none';
}

/**
 * Lists the namespace paths a real run would retract, one per targeted harness's support root, judged against the tree
 * delivery leaves rather than the one on disk. The plans name both halves of that: which namespaces gain content and
 * which delivery empties.
 */
async function planSourceSupportRetractions(
  targets: ReadonlyArray<HarnessSkillTarget>,
  plans: ReadonlyArray<SourceSupportPlan>,
): Promise<ReadonlyArray<string>> {
  const retractions: Array<string> = [];
  for (const sourcesRoot of resolveSupportRoots(targets)) {
    retractions.push(...(await listUndeclaredSourceSupport(sourcesRoot, resolveSupportOutcome(plans, sourcesRoot))));
  }
  return retractions;
}

/** Builds one artifact's render defect, holding the harness so the fold can tell a body-local failure from a scoped one. */
function describeRenderDefect(type: ArtifactType, slug: string, harnessId: HarnessId, error: unknown): HarnessDefect {
  return {
    harnessId,
    defect: { file: artifactFrontmatterPath(type, slug), kind: 'render', detail: describeError(error) },
  };
}

/**
 * Renders every declared skill against every targeted harness, discarding the output, so a broken include or an
 * unmapped tool placeholder is reported before any file is written. The deploy pass re-renders at write time; this
 * pass exists only to fail the run closed, including under `--dry-run`.
 */
async function findDeclaredSkillRenderDefects(
  targets: ReadonlyArray<HarnessSkillTarget>,
  resolvedSkills: ReadonlyArray<ResolvedSkill>,
  resolveAnchorContext: ResolveAnchorContext,
): Promise<ReadonlyArray<ContentDefect>> {
  const raised: Array<HarnessDefect> = [];
  for (const target of targets) {
    for (const skill of resolvedSkills) {
      if (!skillTargetsHarness(skill, target.harnessId)) {
        continue;
      }
      try {
        await renderSkillDirectory(skill.srcDir, skill.slug, skill.contentRoot, {
          ...target.deployContext,
          anchor: createSkillLinkAnchor(resolveAnchorContext(target.harnessId, skill.source)),
        });
      } catch (error: unknown) {
        raised.push(describeRenderDefect('skill', skill.slug, target.harnessId, error));
      }
    }
  }
  return foldHarnessDefects(
    raised,
    targets.map((target) => target.harnessId),
  );
}

/**
 * Renders every declared subagent against every targeted harness, discarding the output, so an unmapped tool
 * placeholder or a rulebook token is reported before any file is written. `reconcileDeclaredSubagents` re-renders at write
 * time; this pass exists only to fail the run closed, including under `--dry-run`.
 */
async function findDeclaredSubagentRenderDefects(
  targets: ReadonlyArray<HarnessSubagentTarget>,
  resolvedSubagents: ReadonlyArray<ResolvedSubagent>,
  resolveAnchorContext: ResolveAnchorContext,
  resolveOverlay: ResolveOverlay,
): Promise<ReadonlyArray<ContentDefect>> {
  const raised: Array<HarnessDefect> = [];
  for (const target of targets) {
    for (const subagent of resolvedSubagents) {
      try {
        await renderSubagent(subagent, {
          ...target.deployContext,
          anchor: createContentRootLinkAnchor(resolveAnchorContext(target.harnessId, subagent.source)),
          overlayYaml: await resolveOverlay(target.harnessId, subagent.contentRoot),
        });
      } catch (error: unknown) {
        raised.push(describeRenderDefect('subagent', subagent.slug, target.harnessId, error));
      }
    }
  }
  return foldHarnessDefects(
    raised,
    targets.map((target) => target.harnessId),
  );
}

/**
 * Renders every resolved rulebook against every targeted harness, discarding the output, so a link target the
 * delivery pipeline cannot honor is reported before any file is written. Both delivery passes re-render at write time;
 * this pass exists only to fail the run closed, including under `--dry-run`.
 */
function findRulebookRenderDefects(
  harnessIds: ReadonlyArray<HarnessId>,
  resolved: ReadonlyArray<ResolvedRulebook>,
  resolveRulebookContext: ResolveRulebookContext,
): ReadonlyArray<ContentDefect> {
  const raised: Array<HarnessDefect> = [];
  for (const harnessId of harnessIds) {
    for (const rulebook of resolved) {
      try {
        renderRulebookBody(rulebook.body, rulebook.slug, resolveRulebookContext(harnessId, rulebook.source));
      } catch (error: unknown) {
        raised.push(describeRenderDefect('rulebook', rulebook.slug, harnessId, error));
      }
    }
  }
  return foldHarnessDefects(raised, harnessIds);
}

/**
 * Carries out each ambient host's plan, regenerating the region's content wholesale (an empty ambient set empties an
 * existing region). Both domains share this one path, differing only in the host each targets and in who owns region
 * creation there.
 */
async function deliverAmbient(plans: ReadonlyArray<PlannedAmbientHost>): Promise<void> {
  for (const { hostPath, plan } of plans) {
    if (plan.kind === 'skip') {
      continue;
    }
    await writeIfChanged(hostPath, plan.content);
  }
}

/** A probed ambient host: its content when present, plus how its region stands. */
type AmbientHostState =
  { readonly status: 'missing' } | { readonly status: 'malformed' | 'no-region' | 'ready'; readonly content: string };

/** What a sync does to one ambient host: write the given content, or skip for the given reason. */
export type AmbientHostPlan =
  | { readonly kind: 'skip'; readonly reason: AmbientSkipReason }
  | { readonly kind: 'write'; readonly action: 'append' | 'create' | 'inject'; readonly content: string };

/** Why one ambient host is skipped. A stale install carries the probe status that names its remedy. */
export type AmbientSkipReason =
  | { readonly cause: 'damaged-region' }
  | { readonly cause: 'not-needed' }
  | { readonly cause: 'stale-install'; readonly status: 'malformed' | 'missing' | 'no-region' };

/** One targeted ambient host paired with the plan a sync carries out there. */
export interface PlannedAmbientHost {
  readonly hostPath: string;
  readonly plan: AmbientHostPlan;
}

/**
 * Decides what a sync does to one ambient host. The harness-home host is `install`'s to create, so anything but a
 * rendered region is skipped with the remedy named. The project-local host is sync's own, and is materialized only
 * when there is ambient content to carry: An absent host with nothing to deliver stays absent, matching how the
 * `prompts.yml` region and the legacy ambient host withdraw rather than persist empty.
 */
function planAmbientHost(hostKind: AmbientHostKind, host: AmbientHostState, body: string): AmbientHostPlan {
  if (host.status === 'ready') {
    return { kind: 'write', action: 'inject', content: injectAmbientRegion(host.content, body) };
  }
  if (hostKind === 'harness-home') {
    return { kind: 'skip', reason: { cause: 'stale-install', status: host.status } };
  }
  if (body === '') {
    return { kind: 'skip', reason: { cause: 'not-needed' } };
  }
  // A damaged region never reaches a write: `assertAmbientHostsWritable` has already failed the run.
  return host.status === 'malformed'
    ? { kind: 'skip', reason: { cause: 'damaged-region' } }
    : {
        kind: 'write',
        action: host.status === 'missing' ? 'create' : 'append',
        content: appendAmbientRegion(host.status === 'missing' ? '' : host.content, body),
      };
}

/** Pairs each targeted host with the plan a sync carries out there, derived once so both paths read the same one. */
async function planAmbientHosts(
  hosts: ReadonlyArray<AmbientHostTarget>,
  domain: SyncDomain,
  resolved: ReadonlyArray<ResolvedRulebook>,
  resolveRulebookContext: ResolveRulebookContext,
): Promise<ReadonlyArray<PlannedAmbientHost>> {
  return Promise.all(
    hosts.map(async ({ harnessId, hostPath }) => ({
      hostPath,
      plan: planAmbientHost(
        domain.ambient,
        await probeAmbientHost(hostPath),
        renderAmbientBody(resolved, harnessId, resolveRulebookContext),
      ),
    })),
  );
}

/**
 * The hosts a sync writes that git does not ignore, so machine-local guidance does not quietly become a commit
 * candidate. Purely advisory: An ignored host is omitted, and so is one the check cannot answer for — the project may
 * not be a repository at all, which is no reason to fail a sync. A host the run skips is never asked about.
 */
async function findUnignoredHosts(
  projectRoot: string,
  plans: ReadonlyArray<PlannedAmbientHost>,
): Promise<ReadonlyArray<string>> {
  const unignored: Array<string> = [];
  for (const { hostPath, plan } of plans) {
    if (plan.kind === 'write' && (await checkGitIgnored(projectRoot, hostPath)) === false) {
      unignored.push(hostPath);
    }
  }
  return unignored;
}

/** Probes an ambient host for its content and region state. */
async function probeAmbientHost(hostPath: string): Promise<AmbientHostState> {
  let content: string;
  try {
    content = await readFile(hostPath, 'utf8');
  } catch (error: unknown) {
    if (isMissingFile(error)) {
      return { status: 'missing' };
    }
    throw error;
  }
  switch (classifyAmbientRegion(content)) {
    case 'complete':
      return { status: 'ready', content };
    case 'malformed':
      return { status: 'malformed', content };
    case 'absent':
      return { status: 'no-region', content };
  }
}

/**
 * Reports every host `sync` would write that already carries a damaged region — an unmatched marker, or more than one.
 * Only the sync-owned project-local host can be appended to, so only it needs the guard; the harness-home path skips
 * such a file with a warning instead. Runs before any write so a dry-run surfaces the conflict with nothing changed.
 */
async function findDamagedAmbientHostDefects(
  hosts: ReadonlyArray<AmbientHostTarget>,
  domain: SyncDomain,
  resolved: ReadonlyArray<ResolvedRulebook>,
): Promise<ReadonlyArray<ContentDefect>> {
  // Asks whether anything would be delivered, which is a property of the declaration alone. Rendering could answer it
  // too, but rendering can now fail on a bad link, and this guard is about region damage rather than link validity.
  if (domain.ambient !== 'project-local' || resolved.every((rulebook) => !rulebook.ambient)) {
    return [];
  }
  const defects: Array<ContentDefect> = [];
  for (const { hostPath } of hosts) {
    if ((await probeAmbientHost(hostPath)).status === 'malformed') {
      defects.push({
        file: hostPath,
        kind: 'target',
        detail:
          'Refusing to deliver ambient guidance into a file carrying a damaged ambient region (an unmatched marker, ' +
          'or more than one region). Repair the codeassembly-ambient markers, then re-run.',
      });
    }
  }
  return defects;
}

/**
 * Retires a former ambient host: removes the sync-owned rulebook blocks it carries and writes back the stripped
 * remainder, so hand-authored content survives. Ambient delivery targets the harness regions now, and a lingering
 * copy would present stale guidance as current. `deleteWhenEmpty` deletes a host left holding nothing — right for
 * one sync created itself, wrong for a hand-authored file like the project's own `AGENTS.md`, which is never
 * deleted. A missing host, and one carrying nothing to retire, are both no-ops.
 */
async function retireAmbientHost(
  options: InstallOptions,
  hostPath: string,
  deleteWhenEmpty: boolean,
): Promise<Retirement | undefined> {
  let content: string;
  try {
    content = await readFile(hostPath, 'utf8');
  } catch (error: unknown) {
    if (isMissingFile(error)) {
      return undefined;
    }
    throw error;
  }

  let stripped = content;
  for (const slug of extractInstalledSlugs(content)) {
    stripped = removeRulebook(stripped, slug);
  }
  const deletable = deleteWhenEmpty && stripped.trim() === '';
  if (stripped === content && !deletable) {
    return undefined;
  }

  if (!options.dryRun) {
    await (deletable ? rm(hostPath, { force: true }) : writeIfChanged(hostPath, stripped));
  }
  return { kind: 'ambient-host', hostPath, emptied: deletable };
}

/**
 * Retires the neutral rulebook tree at `<baseDir>/.agents/rulebooks/`. Nothing reads it, so it is removed rather than
 * maintained. Only the `.md` files sync materialized are deleted, and the directory itself only once nothing else
 * remains in it, so anything a user placed alongside them survives. A missing directory is a no-op.
 */
async function retireNeutralRulebooks(options: InstallOptions, baseDir: string): Promise<Retirement | undefined> {
  const neutralDir = path.join(baseDir, '.agents', 'rulebooks');
  if (!existsSync(neutralDir)) {
    return undefined;
  }

  if (!options.dryRun) {
    const entries = await readDirEntries(neutralDir);
    for (const entry of entries) {
      if (entry.isFile() && entry.name.endsWith('.md')) {
        await rm(path.join(neutralDir, entry.name), { force: true });
      }
    }
    if ((await readDirEntries(neutralDir)).length === 0) {
      await rmdir(neutralDir);
    }
  }
  return { kind: 'neutral-rulebooks', dir: neutralDir };
}

/**
 * Retires the outputs this domain no longer produces: the neutral rulebook tree in both domains, and, in the project
 * domain, the rulebook blocks the hand-authored project guidance used to host. Runs on every sync that has a
 * declaration to act on, so a project picks the retirement up on its next run rather than needing a migration step.
 *
 * Both guidance locations are swept. A project that renames `.agents/PROJECT.md` to the repository-root `AGENTS.md`
 * before its next sync would otherwise carry the stale blocks into the new location for good.
 */
async function retireRetiredOutputs(options: InstallOptions, domain: SyncDomain): Promise<ReadonlyArray<Retirement>> {
  const legacyHosts =
    domain.ambient === 'project-local'
      ? [path.join(domain.baseDir, '.agents', 'PROJECT.md'), path.join(domain.baseDir, 'AGENTS.md')]
      : [];
  const retirements = [await retireNeutralRulebooks(options, domain.baseDir)];
  for (const hostPath of legacyHosts) {
    retirements.push(await retireAmbientHost(options, hostPath, false));
  }
  return retirements.filter((retirement) => retirement !== undefined);
}

/**
 * Renders the ambient rulebooks as concatenated sentinel blocks beneath the generated-region note — the wholesale
 * content of one harness's ambient region. The context is one harness's, so the same rulebook yields that harness's
 * own absolute paths. An empty result stays empty: the note belongs to generated content, and callers read emptiness
 * as "nothing to deliver here".
 */
function renderAmbientBody(
  resolved: ReadonlyArray<ResolvedRulebook>,
  harnessId: HarnessId,
  resolveRulebookContext: ResolveRulebookContext,
): string {
  let body = '';
  for (const rulebook of resolved) {
    if (!rulebook.ambient) {
      continue;
    }
    const context = resolveRulebookContext(harnessId, rulebook.source);
    body = injectRulebook(
      body,
      rulebook.slug,
      renderRulebookBody(rulebook.body, rulebook.slug, context),
      rulebook.version,
    );
  }
  // Prepend rather than seed the loop: seeding would route the note through `injectRulebook`, which separates it from
  // the first block with a blank line and would leave the note standing as the whole body when nothing is ambient.
  return body === '' ? '' : `${ambientRegionNote}\n${body}`;
}

/**
 * The per-harness inputs a rulebook render depends on: the harness config's own segments and sigils, the anchor its
 * link targets resolve through, and the deployed rulebooks indexed by slug, so a `{rulebook:<slug>}` token renders the
 * skill name its target deploys under.
 */
function buildRulebookRenderContext(
  harnessId: HarnessId,
  resolved: ReadonlyArray<ResolvedRulebook>,
  anchor: ResolveLinkAnchor,
): RulebookRenderContext {
  const config = HARNESSES[harnessId];
  return {
    anchor,
    guidanceFileName: config.guidanceFileName,
    homeDir: config.homeDir,
    harnessId: config.id,
    skillSigil: config.skillSigil,
    subagentSigil: config.subagentSigil,
    rulebooks: buildRulebookInvocationCatalog(resolved),
  };
}

/**
 * Indexes the deployed rulebooks by slug, so a `{rulebook:<slug>}` token renders the skill name its target deploys
 * under. Harness-invariant, unlike the render contexts that carry it: What a rulebook deploys as does not vary by
 * harness.
 */
function buildRulebookInvocationCatalog(resolved: ReadonlyArray<ResolvedRulebook>): RulebookInvocationCatalog {
  return new Map(resolved.map((rulebook) => [rulebook.slug, { skillName: rulebook.skillName, skill: rulebook.skill }]));
}

/**
 * Lists the guidance files whose ambient regions a sync of `domain` targets — one per targeted harness, each paired
 * with the harness id its content is rendered for.
 */
function resolveAmbientHosts(
  harnessIds: ReadonlyArray<HarnessId>,
  domain: SyncDomain,
): ReadonlyArray<AmbientHostTarget> {
  return harnessIds.map((harnessId) => ({
    harnessId,
    hostPath: resolveAmbientHostPath(harnessId, domain.ambient, domain.baseDir),
  }));
}

/**
 * Reconciles the Rovo Dev `prompts.yml` index so it lists the user-invocable skills currently in the harness skills
 * dir. The deployed skills are projected into a codeassembly-owned region merged into the shared file, preserving any
 * foreign entries; when no skills remain, the region is stripped — and the file deleted when nothing foreign is left. A
 * no-op for non-Rovo Dev harnesses and for a file carrying no codeassembly region. Both domains share this one path, so
 * the home file is merged rather than whole-file overwritten, matching the repo file's non-clobbering shape.
 */
async function refreshPromptsYml(harnessIds: ReadonlyArray<HarnessId>, domain: SyncDomain): Promise<void> {
  for (const harnessId of harnessIds) {
    if (harnessId !== 'rovo') {
      continue;
    }
    const { harnessHome, skillsDir } = resolveHarnessPaths(harnessId, domain.baseDir);
    const promptsPath = path.join(harnessHome, 'prompts.yml');
    const entries = await collectPromptEntries(skillsDir);
    const existing = await readFileOrEmpty(promptsPath);

    if (entries !== undefined && entries.length > 0) {
      await writeIfChanged(promptsPath, injectPromptsRegion(existing, renderPromptEntries(entries)));
      continue;
    }

    // No skills remain: strip our region, deleting the file when nothing foreign survives. A file we never owned (no
    // region) is left untouched.
    if (!hasPromptsRegion(existing)) {
      continue;
    }
    const stripped = removePromptsRegion(existing);
    await (stripped.trim() === '' ? rm(promptsPath, { force: true }) : writeIfChanged(promptsPath, stripped));
  }
}

/** Lists the Rovo Dev `prompts.yml` paths a sync of `domain` would reconcile — one per targeted Rovo Dev harness. */
function resolvePromptsYmlPaths(harnessIds: ReadonlyArray<HarnessId>, domain: SyncDomain): ReadonlyArray<string> {
  return harnessIds
    .filter((harnessId) => harnessId === 'rovo')
    .map((harnessId) => path.join(resolveHarnessPaths(harnessId, domain.baseDir).harnessHome, 'prompts.yml'));
}

/**
 * Attributes each deployed rulebook, skill, and subagent to the source it resolved from, flagging any source-resolved
 * artifact whose slug also exists in the library as shadowing it. The library probe runs only for source-resolved
 * artifacts — a library-resolved artifact cannot shadow the library — and is batched across all of them.
 */
async function buildResolutionReport(
  resolver: SourceResolver,
  rulebooks: ReadonlyArray<ResolvedRulebook>,
  skills: ReadonlyArray<ResolvedSkill>,
  subagents: ReadonlyArray<ResolvedSubagent>,
): Promise<ReadonlyArray<ResolutionEntry>> {
  const artifacts: Array<{ type: ArtifactType; slug: string; source: string | undefined }> = Array.from(
    rulebooks,
    (rulebook) => ({ type: 'rulebook', slug: rulebook.slug, source: rulebook.source }),
  );
  for (const skill of skills) {
    artifacts.push({ type: 'skill', slug: skill.slug, source: skill.source });
  }
  for (const subagent of subagents) {
    artifacts.push({ type: 'subagent', slug: subagent.slug, source: subagent.source });
  }
  return Promise.all(
    artifacts.map(async (artifact) => ({
      ...artifact,
      shadowsLibrary:
        artifact.source !== undefined && (await hasLibraryArtifact(resolver, artifact.type, artifact.slug)),
    })),
  );
}

/**
 * Builds a memoized reader of the subagent frontmatter overlay, keyed on the harness and the content root a subagent
 * resolved from. Memoized because every subagent from one source reads the same overlay, and the pre-write render
 * gate reads each of them a second time.
 */
function createOverlayLoader(): ResolveOverlay {
  const cache = new Map<string, Promise<string>>();
  return (harnessId, contentRoot) => {
    const key = `${harnessId}\u{0}${contentRoot}`;
    const cached = cache.get(key);
    if (cached !== undefined) {
      return cached;
    }
    const loading = loadHarnessOverlay(contentRoot, HARNESSES[harnessId]);
    cache.set(key, loading);
    return loading;
  };
}

/**
 * Resolves one harness's project-local subagents dir together with the per-harness inputs the deploy transform needs:
 * the link anchor, the home-dir segment, and the harness id. Passing `projectRoot` as the base keeps delivery
 * project-scoped, matching the skill passes.
 */
function resolveSubagentTarget(
  harnessId: HarnessId,
  projectRoot: string,
  rulebooks: RulebookInvocationCatalog,
  guidanceHookFills: GuidanceHookFills | undefined,
): HarnessSubagentTarget {
  const harnessConfig = HARNESSES[harnessId];
  return {
    harnessId,
    subagentsDir: resolveHarnessPaths(harnessId, projectRoot).subagentsDir,
    deployContext: {
      guidanceFileName: harnessConfig.guidanceFileName,
      homeDir: harnessConfig.homeDir,
      harnessId: harnessConfig.id,
      skillSigil: harnessConfig.skillSigil,
      subagentSigil: harnessConfig.subagentSigil,
      rulebooks,
      guidanceHookFills,
    },
  };
}

/**
 * Resolves one harness's project-local skills dir together with the per-harness inputs the skill transform needs: the
 * link anchor, the home-dir segment, and the harness ID. Passing `projectRoot` as the base keeps delivery
 * project-scoped.
 */
function resolveSkillTarget(
  harnessId: HarnessId,
  projectRoot: string,
  rulebooks: RulebookInvocationCatalog,
  guidanceHookFills: GuidanceHookFills | undefined,
): HarnessSkillTarget {
  const harnessConfig = HARNESSES[harnessId];
  return {
    harnessId,
    skillsDir: resolveHarnessPaths(harnessId, projectRoot).skillsDir,
    deployContext: {
      guidanceFileName: harnessConfig.guidanceFileName,
      homeDir: harnessConfig.homeDir,
      harnessId: harnessConfig.id,
      skillSigil: harnessConfig.skillSigil,
      subagentSigil: harnessConfig.subagentSigil,
      rulebooks,
      guidanceHookFills,
    },
  };
}

// endregion | Helpers
