import { type Dirent, existsSync } from 'node:fs';
import { mkdir, readdir, readFile, rm, rmdir } from 'node:fs/promises';
import { homedir } from 'node:os';
import path from 'node:path';
import process from 'node:process';

import { appendAmbientRegion, classifyAmbientRegion, injectAmbientRegion } from '../../lib/ambient-region.ts';
import { makeArtifactMarker } from '../../lib/artifact-marker.ts';
import { ARTIFACT_TYPE_VALUES, type ArtifactType } from '../../lib/artifact-types.ts';
import { resolveDeclaration } from '../../lib/codeassembly-manifest.ts';
import { resolveContentDir } from '../../lib/content-resolver.ts';
import {
  createSourceResolver,
  describeSearchedLocations,
  hasLibraryArtifact,
  type SourceResolver,
} from '../../lib/content-sources.ts';
import { type DirectArtifacts, resolveClosure } from '../../lib/dependency-resolver.ts';
import { findCrossNamespaceCollisions, findSkillNameCollisions } from '../../lib/deploy-collisions.ts';
import { readDirEntries, readFileOrEmpty, writeIfChanged } from '../../lib/fs-helpers.ts';
import { checkGitIgnored } from '../../lib/git-ignore.ts';
import type { GuidanceHookFill, GuidanceHookFills } from '../../lib/guidance-hooks.ts';
import { listGuidanceHooks } from '../../lib/guidance-hooks.ts';
import { HARNESSES, resolveAmbientHostPath, resolveHarnessPaths } from '../../lib/harness.ts';
import { loadHarnessOverlay } from '../../lib/harness-overlay.ts';
import { recordHomeProvenance } from '../../lib/home-provenance.ts';
import { assertDesignatedWriter } from '../../lib/home-writer-guard.ts';
import { enumerateCatalogSlugs } from '../../lib/library-catalog.ts';
import {
  createContentRootLinkAnchor,
  createSkillLinkAnchor,
  type LinkAnchorContext,
  SOURCE_SUPPORT_DIR,
} from '../../lib/link-anchor.ts';
import { findUndeclaredGuidancePackages, resolvePackageSources } from '../../lib/package-sources.ts';
import type { ResolveLinkAnchor } from '../../lib/path-rewriter.ts';
import { collectPromptEntries, renderPromptEntries } from '../../lib/prompts-yml.ts';
import { hasPromptsRegion, injectPromptsRegion, removePromptsRegion } from '../../lib/prompts-yml-region.ts';
import { type ResolvedRulebook, resolveRulebook } from '../../lib/rulebook-deploy.ts';
import { extractRulebookSkillSlug, renderSkillFile } from '../../lib/rulebook-skill.ts';
import { renderRulebookBody, type RulebookRenderContext } from '../../lib/rulebook-transform.ts';
import { resolveRunningPackageRoot } from '../../lib/running-package.ts';
import { extractInstalledSlugs, injectRulebook, removeRulebook } from '../../lib/sentinel-inliner.ts';
import { deploySkill, resolveDeclaredSkill, type ResolvedSkill, skillTargetsHarness } from '../../lib/skill-deploy.ts';
import { type RenderedSkillEntry, renderSkillDirectory, type SkillDeployContext } from '../../lib/skill-transform.ts';
import { describeSourceNameProblem, describeSourceProblem } from '../../lib/source-validation.ts';
import {
  deploySubagent,
  renderSubagent,
  resolveDeclaredSubagent,
  type ResolvedSubagent,
  type SubagentDeployContext,
} from '../../lib/subagent-deploy.ts';
import {
  deploySourceSupport,
  listUndeclaredSourceSupport,
  renderSourceSupport,
  retractUndeclaredSourceSupport,
  type SourceSupportOutcome,
} from '../../lib/support-deploy.ts';
import { type ResolvedHarnessTargets, resolveTargetHarnesses } from '../../lib/target-harnesses.ts';
import { loadToolMapping } from '../../lib/tool-name-rewriter.ts';
import { isEnoent, isMissingFile } from '../../lib/type-guards.ts';
import type { AmbientHostKind, HarnessId, InstallOptions } from '../../lib/types.ts';

/** The line an ambient region opens with, so a reader who finds generated guidance knows an edit there is lost. */
const ambientRegionNote =
  '<!-- Generated by `codeassembly sync` from the rulebooks named below. Edits inside this region are overwritten. -->';

const skillMarker = makeArtifactMarker('skill');
const subagentMarker = makeArtifactMarker('subagent');

/**
 * One deployed artifact's resolution outcome: its type and slug, the source it resolved from (`undefined` = library),
 * and whether it masks a same-slug library artifact. Drives both the dry-run resolution report and the real-run shadow
 * warning.
 */
export interface ResolutionEntry {
  readonly type: ArtifactType;
  readonly slug: string;
  readonly source: string | undefined;
  readonly shadowsLibrary: boolean;
}

/** One targeted harness's project-local subagents dir paired with the per-harness inputs the deploy transform needs. */
export interface HarnessSubagentTarget {
  readonly harnessId: HarnessId;
  readonly subagentsDir: string;
  /** Everything but the anchor, which the owning source decides and so is supplied per subagent. */
  readonly deployContext: Omit<SubagentDeployContext, 'anchor'>;
}

/** One targeted harness's ambient host, paired with the harness id whose paths its rulebook bodies render for. */
interface AmbientHostTarget {
  readonly harnessId: HarnessId;
  readonly hostPath: string;
}

/**
 * Builds one harness's rulebook render context. Threaded rather than rebuilt per call site so the pre-write gate,
 * ambient delivery, and skill delivery all render a rulebook body against the same anchor.
 */
type ResolveRulebookContext = (harnessId: HarnessId, supportNamespace: string | undefined) => RulebookRenderContext;

/**
 * Resolves the anchor inputs for one harness and one owning source (`undefined` = the built-in library). The owner is
 * a per-artifact input rather than a per-harness one, because only it distinguishes a link into a source's own support
 * tree from the same target written by a library artifact.
 */
type ResolveAnchorContext = (harnessId: HarnessId, supportNamespace: string | undefined) => LinkAnchorContext;

/**
 * One source's support entries rendered for one harness, paired with the namespace directory they deploy into and
 * what delivery will do there: write the entries, remove a namespace the source no longer fills, or nothing at all.
 * Carrying the verdict is what lets the preview describe the removals without re-deriving them from the tree that
 * delivery is about to change.
 */
export interface SourceSupportPlan {
  readonly sourcesRoot: string;
  readonly name: string;
  readonly destDir: string;
  readonly entries: ReadonlyArray<RenderedSkillEntry>;
  readonly kind: 'deliver' | 'retract' | 'none';
}

/** One targeted harness's id and project-local skills dir paired with the per-harness inputs the skill transform needs. */
export interface HarnessSkillTarget {
  readonly harnessId: HarnessId;
  readonly skillsDir: string;
  /** Everything but the anchor, which the owning source decides and so is supplied per skill. */
  readonly deployContext: Omit<SkillDeployContext, 'anchor'>;
}

/** A scope carrying no `codeassembly.yaml` to act on, and the tier whose remedy the report names. */
export interface MissingDeclaration {
  readonly kind: 'no-declaration';
  readonly declarationPath: string;
  readonly scope: 'global' | 'project';
}

/** What a sync resolved and what it did, or what it would have done under `--dry-run`. */
export type SyncOutcome = MissingDeclaration | { readonly kind: 'reconciled'; readonly plan: SyncPlan };

/**
 * Everything a sync resolved, and every write, retraction, and warning it produced. Both reports render from this one
 * plan, so a condition either can describe reaches the other in the same terms. The closing summary's counts are
 * derived from these same fields rather than carried alongside them, which is what keeps a count and the enumeration
 * it summarizes from disagreeing.
 */
export interface SyncPlan {
  readonly targets: ResolvedHarnessTargets;
  readonly resolutionReport: ReadonlyArray<ResolutionEntry>;
  readonly ambientHosts: ReadonlyArray<PlannedAmbientHost>;
  /** Hosts the run writes that git does not ignore, so machine-local guidance does not become a commit candidate. */
  readonly unignoredHosts: ReadonlyArray<string>;
  readonly retirements: ReadonlyArray<Retirement>;
  readonly resolved: ReadonlyArray<ResolvedRulebook>;
  readonly harnessSkillTargets: ReadonlyArray<HarnessSkillTarget>;
  readonly skillOrphansByDir: ReadonlyArray<{ skillsDir: string; orphans: ReadonlyArray<string> }>;
  readonly resolvedSkills: ReadonlyArray<ResolvedSkill>;
  readonly declaredSkillOrphansByDir: ReadonlyArray<{ skillsDir: string; orphans: ReadonlyArray<string> }>;
  readonly resolvedSubagents: ReadonlyArray<ResolvedSubagent>;
  readonly harnessSubagentTargets: ReadonlyArray<HarnessSubagentTarget>;
  readonly subagentOrphansByDir: ReadonlyArray<{ subagentsDir: string; orphans: ReadonlyArray<string> }>;
  /** One entry per source that would deliver support content, naming its namespace dir and how many files land there. */
  readonly sourceSupportPlans: ReadonlyArray<SourceSupportPlan>;
  /** Namespace paths under each target's support root that no declared source claims. */
  readonly sourceSupportRetractions: ReadonlyArray<string>;
  readonly promptsYmlPaths: ReadonlyArray<string>;
  /** Dependencies shipping guidance the project has not declared. */
  readonly undeclaredPackages: ReadonlyArray<string>;
}

/** A retired legacy output, and whether the host it names held nothing but retired blocks. */
export type Retirement =
  | { readonly kind: 'ambient-host'; readonly hostPath: string; readonly emptied: boolean }
  | { readonly kind: 'neutral-rulebooks'; readonly dir: string };

/** The one per-domain difference: the base dir to resolve and deploy under, and where ambient blocks land. */
export interface SyncDomain {
  readonly baseDir: string;
  /**
   * Which guidance file hosts this domain's ambient region. Both domains inject into a per-harness region; they
   * differ only in the host and in who creates it — `install` renders the harness-home region, while `sync` owns
   * the project-local one because `install` does not manage user-local files.
   */
  readonly ambient: AmbientHostKind;
  /**
   * Root that rendered links to this domain's own deployed trees are written under: `~` for the home domain, the
   * absolute project root for the project domain. Without it a project-deployed artifact addresses the home harness
   * dir, which a project sync never populates.
   */
  readonly anchorBase: string;
}

/**
 * Resolves a project's `codeassembly.yaml` scope chain and reconciles it into that project's harness dirs (the repo
 * domain). A thin wrapper over `reconcileDomain` that supplies the repo `SyncDomain`. An absent `codeassembly.yaml`
 * is a total no-op. The home directory decides targeting, through its declaration tier and the harnesses installed
 * under it.
 */
export async function syncCommand(
  options: InstallOptions,
  projectRoot: string = process.cwd(),
  contentDirOverride?: string,
  homeDir: string = homedir(),
): Promise<SyncOutcome> {
  if (path.resolve(projectRoot) === path.resolve(homeDir)) {
    throw new Error(
      'Refusing to run `sync` in the home directory: that would deploy the user-global tier through the project ' +
        'path. Run `sync --global` to sync the user-global tier into the home harness dirs.',
    );
  }
  return reconcileDomain(
    options,
    { baseDir: projectRoot, ambient: 'project-local', anchorBase: path.resolve(projectRoot) },
    homeDir,
    contentDirOverride,
  );
}

/**
 * Resolves the user-global `~/.agents/codeassembly.yaml` scope chain and reconciles it into the home harness dirs (the
 * home domain). A thin wrapper over `reconcileDomain` that supplies the home `SyncDomain`. Ambient blocks land in the
 * ambient region of each targeted harness's guidance file (e.g. `~/.claude/CLAUDE.md`), which the harness loads
 * mechanically; no agent-read host file is written. When the home declaration is absent, changes nothing and returns
 * the outcome naming `init --global` as the remedy.
 */
export async function syncGlobalCommand(
  options: InstallOptions,
  homeDir: string = homedir(),
  contentDirOverride?: string,
): Promise<SyncOutcome> {
  // Runs first, and before the dry-run gate: a preview must refuse wherever the real run would.
  await assertDesignatedWriter({
    command: 'sync --global',
    homeDir,
    packageRoot: resolveRunningPackageRoot(),
    shouldOverrideWriter: options.shouldOverrideWriter,
  });

  const declarationPath = path.join(homeDir, '.agents', 'codeassembly.yaml');
  if (!existsSync(declarationPath)) {
    return { kind: 'no-declaration', declarationPath, scope: 'global' };
  }
  const outcome = await reconcileDomain(
    options,
    { baseDir: homeDir, ambient: 'harness-home', anchorBase: '~' },
    homeDir,
    contentDirOverride,
  );
  const retirement = await retireAmbientHost(options, path.join(homeDir, '.agents', 'GLOBAL.md'), true);

  if (!options.dryRun) {
    await recordHomeProvenance('sync --global', homeDir);
  }

  if (retirement === undefined || outcome.kind !== 'reconciled') {
    return outcome;
  }
  return { ...outcome, plan: { ...outcome.plan, retirements: [...outcome.plan.retirements, retirement] } };
}

/**
 * Resolves the `codeassembly.yaml` scope chain under `domain.baseDir`, materializes each declared rulebook's neutral
 * body to `<baseDir>/.agents/rulebooks/<slug>.md`, delivers `ambient` rulebooks to `domain.ambient`'s target, writes
 * `skill` rulebooks as thin-wrapper skills into each targeted harness's skills dir, deploys declared skills and
 * subagents (the latter through the harness transform) into those harness dirs, and retracts anything no longer
 * declared. Installed state is derived from the filesystem, not a manifest, which keeps the command idempotent. An
 * absent `codeassembly.yaml` is a total no-op. Repo and home domains share this one reconciler, differing only in
 * the `SyncDomain` they pass.
 *
 * `homeDir` is a parameter rather than a `SyncDomain` field because it is the same directory in both domains: it
 * carries the user-global half of the `harnesses` chain and the harnesses targeting falls back to.
 */
async function reconcileDomain(
  options: InstallOptions,
  domain: SyncDomain,
  homeDir: string,
  contentDirOverride?: string,
): Promise<SyncOutcome> {
  const declaration = await resolveDeclaration({ cwd: domain.baseDir });
  if (declaration === undefined) {
    return {
      kind: 'no-declaration',
      declarationPath: path.join(domain.baseDir, '.agents', 'codeassembly.yaml'),
      scope: domain.ambient === 'harness-home' ? 'global' : 'project',
    };
  }

  const contentDir = contentDirOverride ?? resolveContentDir();

  // A declared package contributes both a source and a set of seeds: Its content dir joins the search order below the
  // hand-declared sources, so a hand-pointed local directory outranks a dependency, and everything it ships seeds the
  // closure — which is what makes naming the package the whole declaration.
  const packageSources = await resolvePackageSources(declaration.packages, domain.baseDir);
  const sources = [...declaration.sources, ...packageSources];

  // Resolution searches declared sources (highest precedence first) then the built-in library. Validate each declared
  // source up front so a missing or non-directory source fails the whole run — dry-run included — before any write.
  const resolver = createSourceResolver(sources, contentDir);
  await assertValidSources(sources);
  assertUsableSourceNames(sources);
  assertDistinctSourceNames(sources);

  // Enumerated after validation, so a package whose content dir is missing has already failed the run.
  const packageCatalogs = await Promise.all(packageSources.map((source) => enumerateCatalogSlugs(source.dir)));

  // Expand declared collections — and any artifact's own dependencies — into the deployable per-type sets before
  // resolving against the sources and library, so a declared collection deploys exactly its transitive closure.
  // Checked before the closure resolves so a typo names the hook that wrote it; seeding alone would report only that
  // some rulebook went missing.
  await assertBindingsResolve(declaration.guidanceHooks, resolver);

  const closure = await resolveClosure(
    mergeSeeds([
      {
        rulebook: declaration.rulebooks,
        skill: declaration.skills,
        subagent: declaration.subagents,
        collection: declaration.collections,
      },
      // A binding is a dependency edge: a bound rulebook deploys per its own `delivery:` without being declared twice.
      { rulebook: [...new Set(declaration.guidanceHooks.values().toArray().flat())] },
      ...packageCatalogs,
    ]),
    resolver,
  );
  const declaredRulebooks = closure.rulebooks;

  // Resolve and validate every declared rulebook, skill, and subagent before writing anything, so a missing library
  // file, invalid frontmatter, or a still-`install` artifact fails the whole run rather than leaving a partial sync.
  const resolved = await Promise.all(declaredRulebooks.map((slug) => resolveRulebook(slug, resolver)));
  assertNoSkillNameCollisions(resolved);
  assertBoundRulebooksDeclareNoHook(declaration.guidanceHooks, resolved);
  const resolvedSkills = await Promise.all(closure.skills.map((slug) => resolveDeclaredSkill(slug, resolver)));
  const resolvedSubagents = await Promise.all(closure.subagents.map((slug) => resolveDeclaredSubagent(slug, resolver)));

  // Maps each skill-delivery rulebook's stable slug to the directory its skill currently belongs in. Retraction
  // compares this against what each owned directory's marker reports, so a renamed skill retracts its old dir.
  const desiredSkillDirs = new Map(
    resolved.filter((rulebook) => rulebook.skill).map((rulebook) => [rulebook.slug, rulebook.skillName] as const),
  );
  const declaredSkillSet = new Set(resolvedSkills.map((skill) => skill.slug));

  // Rulebook skills and declared skills share the project-local skills dirs. A directory name claimed by both
  // delivery namespaces would clobber, so reject the overlap before any write.
  assertNoCrossNamespaceCollisions(desiredSkillDirs.values().toArray(), declaredSkillSet);

  // Every delivery pass below targets this one set of harnesses, and each renders its content for the harness it
  // lands on, so the set is resolved once and threaded rather than re-derived per pass.
  const targets = await resolveTargetHarnesses({ harness: options.harness, cwd: domain.baseDir, homeDir });
  const harnessIds = targets.harnessIds;

  // Resolved before every render gate, so the gates and the writes they guard cannot disagree about where a link
  // target lands. The deployed skill dirs it reads are settled above: `resolvedSkills` and `desiredSkillDirs` name
  // everything this run writes into a domain skills dir, and the collision gate has already proven them disjoint.
  const resolveAnchorContext: ResolveAnchorContext = (harnessId, supportNamespace) => {
    const config = HARNESSES[harnessId];
    return {
      supportNamespace,
      // Declared skills are filtered per harness because a skill may target only some; rulebook-delivered skill names
      // are not, because every skill-delivery rulebook is written to every targeted harness.
      deployedSkillDirs: new Set([
        ...resolvedSkills.filter((skill) => skillTargetsHarness(skill, harnessId)).map((skill) => skill.slug),
        ...desiredSkillDirs.values(),
      ]),
      domainBase: domain.anchorBase,
      homeDir: config.homeDir,
      skillsDirName: config.skillsDirName,
    };
  };

  const resolveRulebookContext: ResolveRulebookContext = (harnessId, supportNamespace) =>
    buildRulebookRenderContext(
      harnessId,
      resolved,
      createContentRootLinkAnchor(resolveAnchorContext(harnessId, supportNamespace)),
    );

  // Skill delivery targets project-local harness skills dirs, gated by detection (or `--harness`). Passing
  // `projectRoot` as the base is what keeps the skills project-scoped, and keeps tests out of the real home dir. Each
  // target carries the per-harness skill-transform inputs so declared-skill deployment applies include expansion and
  // tool-name/link rewriting, and the harness id each rulebook body renders for.
  // Rendered per harness, because a bound body carries that harness's link targets, sigils, and home dir. Built once
  // here so the skill pass and the subagent pass splice the same guidance.
  const fillsByHarness = new Map(
    harnessIds.map((harnessId) => [
      harnessId,
      buildGuidanceHookFills(declaration.guidanceHooks, resolved, harnessId, resolveRulebookContext),
    ]),
  );

  const harnessSkillTargets = await Promise.all(
    harnessIds.map((harnessId) =>
      resolveSkillTarget(harnessId, domain.baseDir, contentDir, fillsByHarness.get(harnessId)),
    ),
  );

  // Subagent delivery targets each harness's project-local subagents dir, loading that harness's overlay and tool
  // mapping so the deploy applies the same transform `install` would. Resolved separately from skills because the
  // transform is harness-specific, and subagents live in a distinct flat dir from skills.
  const declaredSubagentSet = new Set(resolvedSubagents.map((subagent) => subagent.slug));
  const harnessSubagentTargets = await Promise.all(
    harnessIds.map((harnessId) =>
      resolveSubagentTarget(harnessId, domain.baseDir, contentDir, fillsByHarness.get(harnessId)),
    ),
  );

  // A skill dir is sync-owned only when its `SKILL.md` carries the provenance marker; that gate is what keeps
  // hand-authored skills safe. An owned dir is an orphan when its marker slug no longer maps to that directory —
  // because the rulebook is no longer skill-delivered, or because its resolved skill name (and dir) changed.
  const skillOrphansByDir = await Promise.all(
    harnessSkillTargets.map(async ({ harnessId, skillsDir }) => ({
      harnessId,
      skillsDir,
      orphans: (await listOwnedSkills(skillsDir))
        .filter(({ dir, slug }) => desiredSkillDirs.get(slug) !== dir)
        .map(({ dir }) => dir),
    })),
  );
  // Declared-skill orphans reconcile per harness, reading only the declared-skill marker so the two namespaces never
  // consider each other's dirs. An owned declared-skill dir in a harness is an orphan once its slug is no longer among
  // the declared skills that target that harness — covering both an undeclared skill and one that dropped this harness.
  const declaredSkillOrphansByDir = await Promise.all(
    harnessSkillTargets.map(async ({ skillsDir, harnessId }) => {
      const targetedSlugs = new Set(
        resolvedSkills.filter((skill) => skillTargetsHarness(skill, harnessId)).map((skill) => skill.slug),
      );
      return {
        skillsDir,
        orphans: (await listOwnedDeclaredSkills(skillsDir))
          .filter(({ slug }) => !targetedSlugs.has(slug))
          .map(({ dir }) => dir),
      };
    }),
  );
  // Declared subagents reconcile file-based (flat `.md` files, not directories): An owned subagent file is one whose
  // content carries the `codeassembly-subagent:` marker. It is an orphan once its slug is no longer declared. A
  // marker-less hand-authored file is never claimed, so it survives untouched.
  const subagentOrphansByDir = await Promise.all(
    harnessSubagentTargets.map(async (target) => ({
      subagentsDir: target.subagentsDir,
      orphans: (await listOwnedSubagents(target.subagentsDir))
        .filter(({ slug }) => !declaredSubagentSet.has(slug))
        .map(({ file }) => file),
    })),
  );

  // Before any write or delete, fail closed on any skill or subagent target that already exists without this sync's
  // ownership marker — an install-managed or hand-authored file. The marker-gated retraction scans keep such files
  // from being deleted; this keeps them from being overwritten. Runs in dry-run too, so a preview surfaces the conflict.
  await assertNoForeignOwnedTargets(
    collectOwnedTargets(harnessSkillTargets, resolved, resolvedSkills, harnessSubagentTargets, resolvedSubagents),
  );

  // Render every declared skill against every targeted harness up front, so a broken include or an unmapped tool
  // placeholder fails the whole run — dry-run included — before any file is written. The rendered output is discarded
  // here; `deploySkill` re-renders it at write time.
  await assertDeclaredSkillsRender(harnessSkillTargets, resolvedSkills, resolveAnchorContext);

  // Same gate for each source's support entries, whose defects would otherwise surface only at the write below. The
  // rendered result is carried to the preview and the delivery pass rather than rendered again by each.
  const sourceSupportPlans = await renderSourceSupportPlans(harnessSkillTargets, sources, resolveAnchorContext);

  // Same gate for subagents, whose deploy is the last write pass: without it a render failure lands after the ambient
  // host and every skill file are already on disk.
  await assertDeclaredSubagentsRender(harnessSubagentTargets, resolvedSubagents, resolveAnchorContext);

  // Same gate for rulebooks: a link target the delivery pipeline cannot honor fails the run before either delivery
  // pass writes, rather than shipping a path that resolves to nothing.
  assertRulebooksRender(harnessIds, resolved, resolveRulebookContext);

  // Reject a sync-owned ambient host whose region is half-written before anything is written, dry-run included.
  // Appending beside a stray marker is the one path in this command that can destroy hand-authored content.
  const ambientHosts = resolveAmbientHosts(harnessIds, domain);
  await assertAmbientHostsWritable(ambientHosts, domain, resolved);

  // Attribute each deployed artifact to the source it resolved from, flagging any that shadows a same-slug library
  // artifact. Built once, off the write path, and consumed by both the dry-run report and the real-run shadow warning.
  const resolutionReport = await buildResolutionReport(resolver, resolved, resolvedSkills, resolvedSubagents);

  // Derived before the paths part, so a dry run cannot describe an ambient host differently from the run it previews.
  const ambientHostPlans = await planAmbientHosts(ambientHosts, domain, resolved, resolveRulebookContext);

  // Advisory only, and gathered for both paths: a dry run that would create the host warns about it too.
  const unignoredHosts =
    domain.ambient === 'project-local' ? await findUnignoredHosts(domain.baseDir, ambientHostPlans) : [];

  const retirements = await retireRetiredOutputs(options, domain);

  const plan: SyncPlan = {
    targets,
    resolutionReport,
    ambientHosts: ambientHostPlans,
    unignoredHosts,
    retirements,
    resolved,
    harnessSkillTargets,
    skillOrphansByDir,
    resolvedSkills,
    declaredSkillOrphansByDir,
    resolvedSubagents,
    harnessSubagentTargets,
    subagentOrphansByDir,
    sourceSupportPlans,
    sourceSupportRetractions: await planSourceSupportRetractions(harnessSkillTargets, sourceSupportPlans),
    promptsYmlPaths: resolvePromptsYmlPaths(harnessIds, domain),
    // Otherwise a consumer has to learn a third party's catalog by hand to discover there is anything to adopt. This
    // is advice, not action: Nothing is deployed until the project declares the package.
    undeclaredPackages: await findUndeclaredGuidancePackages(
      [...declaration.packages, ...declaration.declinedPackages],
      domain.baseDir,
    ),
  };

  if (options.dryRun) {
    return { kind: 'reconciled', plan };
  }

  await deliverAmbient(ambientHostPlans);

  // Reconcile skill files per targeted harness: Retract sync-owned skill dirs that are no longer current, then
  // write every skill-delivery rulebook. Orphans were computed against the pre-write filesystem, so retracting
  // before writing lets a skill name freed by one rulebook be recreated for another in the same sync, instead
  // of the write being clobbered by a later retract.
  for (const { harnessId, skillsDir, orphans } of skillOrphansByDir) {
    for (const dir of orphans) {
      await rm(path.join(skillsDir, dir), { recursive: true, force: true });
    }
    for (const rulebook of resolved) {
      if (!rulebook.skill) {
        continue;
      }
      const skillDir = path.join(skillsDir, rulebook.skillName);
      await mkdir(skillDir, { recursive: true });
      await writeIfChanged(
        path.join(skillDir, 'SKILL.md'),
        renderSkillFile(
          rulebook.skillName,
          rulebook.slug,
          rulebook.description,
          renderRulebookBody(rulebook.body, rulebook.slug, resolveRulebookContext(harnessId, rulebook.source)),
        ),
      );
    }
  }

  // Reconcile declared skills per targeted harness, independently of the rulebook-skill pass above: Retract owned
  // declared-skill dirs no longer declared, then deploy each declared skill into `<skillsDir>/<slug>/`.
  await reconcileDeclaredSkills(harnessSkillTargets, declaredSkillOrphansByDir, resolvedSkills, resolveAnchorContext);

  // Deliver each source's support entries into its own namespace, then retract the namespaces no source claims.
  await reconcileSourceSupport(harnessSkillTargets, sourceSupportPlans);

  // Reconcile declared subagents per targeted harness, independently of the skill passes: Retract owned subagent
  // files no longer declared, then deploy each declared subagent as `<subagentsDir>/<slug>.md` with the harness
  // transform applied and the ownership marker stamped.
  await reconcileDeclaredSubagents(
    harnessSubagentTargets,
    subagentOrphansByDir,
    resolvedSubagents,
    resolveAnchorContext,
  );

  await refreshPromptsYml(harnessIds, domain);

  return { kind: 'reconciled', plan };
}

// region | Helpers

/**
 * Throws when any declared source path is missing, not a directory, or unreadable, so a bad source fails the whole
 * run (dry-run included) before any file is touched. The error names each offending source and what is wrong with it.
 */
async function assertValidSources(sources: ReadonlyArray<{ name: string; dir: string }>): Promise<void> {
  const invalid: Array<string> = [];
  for (const source of sources) {
    const problem = await describeSourceProblem(source.dir);
    if (problem !== undefined) {
      invalid.push(`"${source.name}" (${source.dir}): ${problem}`);
    }
  }
  if (invalid.length > 0) {
    throw new Error(
      `Invalid declared source(s): ${invalid.join('; ')}. Each source path must be an existing, readable directory.`,
    );
  }
}

/**
 * Throws when two declared sources share a name, which the hand-declared tier and the package tier can each satisfy
 * independently: names are unique within a tier, and nothing reconciles one tier's against the other's.
 *
 * A shared name would let both claim one support namespace, so the source that wins artifact resolution and the one
 * whose support files survive delivery are different sources, and links rendered for the first reach the second's
 * files. Failing here, before any write, forces the conflict to be resolved by renaming rather than by delivery order.
 */
function assertDistinctSourceNames(sources: ReadonlyArray<{ name: string; dir: string }>): void {
  const dirsByName = new Map<string, Array<string>>();
  for (const source of sources) {
    dirsByName.set(source.name, [...(dirsByName.get(source.name) ?? []), source.dir]);
  }

  const collisions = dirsByName
    .entries()
    .filter(([, dirs]) => dirs.length > 1)
    .map(([name, dirs]) => `"${name}" (${dirs.join(', ')})`)
    .toArray();

  if (collisions.length > 0) {
    throw new Error(
      `Declared source name(s) claimed more than once: ${collisions.join('; ')}. A source name is the directory its ` +
        'support files deploy under, so two sources cannot share one. Rename one of them.',
    );
  }
}

/**
 * Throws when a declared source's name cannot serve as the directory segments its support entries deploy under, so a
 * name that would escape its namespace fails the run — dry-run included — before any file is written. Every offending
 * name is reported together, so a declaration with two of them takes one fix rather than two runs.
 */
function assertUsableSourceNames(sources: ReadonlyArray<{ name: string; dir: string }>): void {
  const unusable = sources
    .map((source) => ({ source, problem: describeSourceNameProblem(source.name) }))
    .filter((entry) => entry.problem !== undefined)
    .map((entry) => `"${entry.source.name}": ${entry.problem}`);

  if (unusable.length > 0) {
    throw new Error(
      `Unusable declared source name(s): ${unusable.join('; ')}. A source name becomes a directory under the ` +
        'harness skills dir, so it must name one.',
    );
  }
}

/**
 * Concatenates per-type seed sets into the one set that seeds closure resolution. Deduping is deliberately left out:
 * `resolveClosure` already dedupes by slug as it walks, so a slug both declared directly and enumerated from a
 * package's catalog is visited once.
 */
function mergeSeeds(sets: ReadonlyArray<DirectArtifacts>): DirectArtifacts {
  const merged: Record<ArtifactType, Array<string>> = { rulebook: [], skill: [], subagent: [], collection: [] };
  for (const set of sets) {
    for (const type of ARTIFACT_TYPE_VALUES) {
      merged[type].push(...(set[type] ?? []));
    }
  }
  return merged;
}

/** A planned write whose destination must be sync-owned (or absent) before the write proceeds. */
interface OwnedTarget {
  readonly filePath: string;
  readonly isOwned: (content: string) => boolean;
}

/**
 * Throws when a guidance-hook binding names a rulebook that resolves from no declared source or the library, naming
 * both the slug and the hook that bound it. Seeding the closure would catch the same slug, but only as an anonymous
 * missing reference: the hook name is the half that says where to go and fix it.
 */
async function assertBindingsResolve(
  bindings: ReadonlyMap<string, ReadonlyArray<string>>,
  resolver: SourceResolver,
): Promise<void> {
  for (const [hook, slugs] of bindings) {
    for (const slug of slugs) {
      if ((await resolver.resolve('rulebook', slug)) === undefined) {
        throw new Error(
          `Guidance hook "${hook}" binds rulebook "${slug}", which was not found in any of: ` +
            describeSearchedLocations(resolver, 'rulebook', slug),
        );
      }
    }
  }
}

/**
 * Throws when a bound rulebook's own body declares a guidance hook. Bound guidance is spliced as rendered, so a hook
 * inside it has no pass left that could fill it. Checked here, against the unrendered body, because the rulebook
 * renderer strips the directive and the evidence is gone by the time a fill is built.
 */
function assertBoundRulebooksDeclareNoHook(
  bindings: ReadonlyMap<string, ReadonlyArray<string>>,
  resolved: ReadonlyArray<ResolvedRulebook>,
): void {
  const bySlug = indexRulebooksBySlug(resolved);
  for (const [hook, slugs] of bindings) {
    for (const slug of slugs) {
      const declared = listGuidanceHooks(readBoundRulebook(bySlug, slug, hook).body, `guidance/rulebooks/${slug}.md`);
      if (declared.length > 0) {
        const names = declared.map((declaration) => declaration.name).join(', ');
        throw new Error(
          `Rulebook "${slug}", bound to guidance hook "${hook}", declares a guidance hook of its own (${names}). ` +
            'Bound guidance is spliced as rendered, so nothing can fill a hook inside it: remove the directive, or ' +
            'bind a rulebook that carries none.',
        );
      }
    }
  }
}

/**
 * Renders one harness's guidance-hook fills: each bound rulebook's body through the rulebook renderer, keyed by the
 * hook it fills and ordered as the declaration bound it. Rendering here rather than at the splice is what makes the
 * spliced body position-independent, since link targets and invocation tokens are resolved before it moves.
 */
function buildGuidanceHookFills(
  bindings: ReadonlyMap<string, ReadonlyArray<string>>,
  resolved: ReadonlyArray<ResolvedRulebook>,
  harnessId: HarnessId,
  resolveRulebookContext: ResolveRulebookContext,
): GuidanceHookFills {
  const bySlug = indexRulebooksBySlug(resolved);
  const fills = new Map<string, ReadonlyArray<GuidanceHookFill>>();
  for (const [hook, slugs] of bindings) {
    fills.set(
      hook,
      slugs.map((slug) => {
        const rulebook = readBoundRulebook(bySlug, slug, hook);
        const context = resolveRulebookContext(harnessId, rulebook.source);
        return { slug, body: renderRulebookBody(rulebook.body, slug, context) };
      }),
    );
  }
  return fills;
}

/** Indexes resolved rulebooks by slug, so a binding reaches its body without rescanning the list per lookup. */
function indexRulebooksBySlug(resolved: ReadonlyArray<ResolvedRulebook>): ReadonlyMap<string, ResolvedRulebook> {
  return new Map(resolved.map((rulebook) => [rulebook.slug, rulebook]));
}

/**
 * Returns the resolved rulebook a binding names. A binding seeds the closure, so its absence here is a defect in this
 * command rather than in what the user declared, and it is reported as one.
 */
function readBoundRulebook(
  bySlug: ReadonlyMap<string, ResolvedRulebook>,
  slug: string,
  hook: string,
): ResolvedRulebook {
  const rulebook = bySlug.get(slug);
  if (rulebook === undefined) {
    throw new Error(`Rulebook "${slug}", bound to guidance hook "${hook}", did not reach the deploy closure.`);
  }
  return rulebook;
}

/**
 * Throws when any planned target already exists without this sync's ownership marker — an install-managed or
 * hand-authored file. Failing here, before any write or delete, is what keeps a same-named foreign file from being
 * overwritten; the marker-gated retraction scans separately keep it from being deleted. Absent targets are safe.
 */
async function assertNoForeignOwnedTargets(targets: ReadonlyArray<OwnedTarget>): Promise<void> {
  const foreign: Array<string> = [];
  for (const target of targets) {
    let content: string;
    try {
      content = await readFile(target.filePath, 'utf8');
    } catch (error: unknown) {
      if (isMissingFile(error)) {
        continue;
      }
      throw error;
    }
    if (!target.isOwned(content)) {
      foreign.push(target.filePath);
    }
  }
  if (foreign.length > 0) {
    throw new Error(
      `Refusing to overwrite ${foreign.length} file(s) not owned by sync (install-managed or hand-authored): ` +
        `${foreign.join(', ')}. Rename or remove them, or retire the conflicting install artifact, then re-run.`,
    );
  }
}

/**
 * Collects the skill and subagent destinations a sync would write, each paired with the predicate that recognizes its
 * own ownership marker, so the pre-write guard can reject any that already exist foreign-owned.
 */
function collectOwnedTargets(
  harnessSkillTargets: ReadonlyArray<HarnessSkillTarget>,
  resolved: ReadonlyArray<ResolvedRulebook>,
  resolvedSkills: ReadonlyArray<ResolvedSkill>,
  harnessSubagentTargets: ReadonlyArray<HarnessSubagentTarget>,
  resolvedSubagents: ReadonlyArray<ResolvedSubagent>,
): ReadonlyArray<OwnedTarget> {
  const targets: Array<OwnedTarget> = [];
  for (const { skillsDir, harnessId } of harnessSkillTargets) {
    for (const rulebook of resolved) {
      if (rulebook.skill) {
        targets.push({
          filePath: path.join(skillsDir, rulebook.skillName, 'SKILL.md'),
          isOwned: (content) => extractRulebookSkillSlug(content) !== undefined,
        });
      }
    }
    for (const skill of resolvedSkills) {
      if (!skillTargetsHarness(skill, harnessId)) {
        continue;
      }
      targets.push({
        filePath: path.join(skillsDir, skill.slug, 'SKILL.md'),
        isOwned: (content) => skillMarker.extractSlug(content) !== undefined,
      });
    }
  }
  for (const target of harnessSubagentTargets) {
    for (const subagent of resolvedSubagents) {
      targets.push({
        filePath: path.join(target.subagentsDir, `${subagent.slug}.md`),
        isOwned: (content) => subagentMarker.extractSlug(content) !== undefined,
      });
    }
  }
  return targets;
}

/**
 * Throws when a rulebook-skill directory name and a declared-skill directory name collide, which would let the two
 * delivery namespaces clobber each other in a shared project-local skills dir. Failing here, before any write,
 * forces the conflict to be resolved by renaming one side rather than letting the last write win.
 */
function assertNoCrossNamespaceCollisions(
  rulebookSkillDirs: ReadonlyArray<string>,
  declaredSkillSlugs: ReadonlySet<string>,
): void {
  const collisions = findCrossNamespaceCollisions(rulebookSkillDirs, declaredSkillSlugs);
  if (collisions.length > 0) {
    throw new Error(
      `Skill directory name collision across delivery namespaces: ${collisions.join(', ')} ` +
        'is delivered as both a rulebook skill and a declared skill. Rename one so they no longer share a directory.',
    );
  }
}

/**
 * Throws when two skill-delivery rulebooks resolve to the same skill name, which would share one directory and
 * clobber each other. Failing here, before any write, forces the conflict to be resolved with a `skill-name`
 * override rather than silently letting the last write win.
 */
function assertNoSkillNameCollisions(resolved: ReadonlyArray<ResolvedRulebook>): void {
  const collision = findSkillNameCollisions(resolved)[0];
  if (collision !== undefined) {
    throw new Error(
      `Skill name collision: rulebooks ${collision.slugs.join(', ')} all resolve to skill "${collision.skillName}". ` +
        'Give all but one a distinct `skill-name`.',
    );
  }
}

/**
 * Lists the declared skills sync owns under `skillsDir` as `{ dir, slug }` pairs — those whose `SKILL.md` carries the
 * declared-skill marker, paired with the slug recovered from it. Reads only the declared-skill marker, so it never
 * claims a rulebook-skill dir or a hand-authored skill. Returns an empty list when the directory is absent; entries
 * without a readable `SKILL.md` are skipped.
 */
async function listOwnedDeclaredSkills(skillsDir: string): Promise<ReadonlyArray<{ dir: string; slug: string }>> {
  let entries: ReadonlyArray<string>;
  try {
    entries = await readdir(skillsDir);
  } catch (error: unknown) {
    if (isEnoent(error)) {
      return [];
    }
    throw error;
  }

  const owned: Array<{ dir: string; slug: string }> = [];
  for (const entry of entries) {
    let content: string;
    try {
      content = await readFile(path.join(skillsDir, entry, 'SKILL.md'), 'utf8');
    } catch (error: unknown) {
      if (isMissingFile(error)) {
        continue;
      }
      throw error;
    }
    const slug = skillMarker.extractSlug(content);
    if (slug !== undefined) {
      owned.push({ dir: entry, slug });
    }
  }
  return owned;
}

/**
 * Lists the sync-owned skills under `skillsDir` as `{ dir, slug }` pairs — those whose `SKILL.md` carries the
 * rulebook provenance marker, paired with the slug recovered from it. The directory locates the skill on disk;
 * the slug is its stable identity, which the directory may no longer match. Returns an empty list when the
 * directory is absent. Entries without a readable `SKILL.md` (a marker-less hand-authored skill, a stray
 * `.DS_Store`) are skipped, never claimed for deletion.
 */
async function listOwnedSkills(skillsDir: string): Promise<ReadonlyArray<{ dir: string; slug: string }>> {
  let entries: ReadonlyArray<string>;
  try {
    entries = await readdir(skillsDir);
  } catch (error: unknown) {
    if (isEnoent(error)) {
      return [];
    }
    throw error;
  }

  const owned: Array<{ dir: string; slug: string }> = [];
  for (const entry of entries) {
    let content: string;
    try {
      content = await readFile(path.join(skillsDir, entry, 'SKILL.md'), 'utf8');
    } catch (error: unknown) {
      // Not a skill dir: the SKILL.md is absent, or the entry is a regular file (ENOTDIR on read-through).
      if (isMissingFile(error)) {
        continue;
      }
      throw error;
    }
    const slug = extractRulebookSkillSlug(content);
    if (slug !== undefined) {
      owned.push({ dir: entry, slug });
    }
  }
  return owned;
}

/**
 * Lists the sync-owned subagents under `subagentsDir` as `{ file, slug }` pairs — the flat `.md` files whose content
 * carries the `codeassembly-subagent:` ownership marker, paired with the slug recovered from it. Reads only that
 * marker, so a marker-less hand-authored file is never claimed. Returns an empty list when the directory is absent;
 * non-`.md` entries and directories are skipped.
 */
async function listOwnedSubagents(subagentsDir: string): Promise<ReadonlyArray<{ file: string; slug: string }>> {
  let entries: ReadonlyArray<Dirent>;
  try {
    entries = await readdir(subagentsDir, { withFileTypes: true });
  } catch (error: unknown) {
    if (isEnoent(error)) {
      return [];
    }
    throw error;
  }

  const owned: Array<{ file: string; slug: string }> = [];
  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith('.md')) {
      continue;
    }
    let content: string;
    try {
      content = await readFile(path.join(subagentsDir, entry.name), 'utf8');
    } catch (error: unknown) {
      // A `.md` symlink whose target is gone passes the `isFile()` filter (it follows links) but throws on read.
      if (isEnoent(error)) {
        continue;
      }
      throw error;
    }
    const slug = subagentMarker.extractSlug(content);
    if (slug !== undefined) {
      owned.push({ file: entry.name, slug });
    }
  }
  return owned;
}

/**
 * Retracts owned subagent files no longer declared, then deploys each declared subagent into every targeted harness's
 * subagents dir. Orphans were computed against the pre-write filesystem, so retracting before writing lets a slug
 * freed in one dir be re-created in the same sync rather than clobbered by a later retract.
 */
async function reconcileDeclaredSubagents(
  targets: ReadonlyArray<HarnessSubagentTarget>,
  orphansByDir: ReadonlyArray<{ subagentsDir: string; orphans: ReadonlyArray<string> }>,
  resolvedSubagents: ReadonlyArray<ResolvedSubagent>,
  resolveAnchorContext: ResolveAnchorContext,
): Promise<void> {
  for (const target of targets) {
    const orphans = orphansByDir.find((entry) => entry.subagentsDir === target.subagentsDir)?.orphans ?? [];
    for (const file of orphans) {
      await rm(path.join(target.subagentsDir, file), { force: true });
    }
    for (const subagent of resolvedSubagents) {
      await deploySubagent(subagent, path.join(target.subagentsDir, `${subagent.slug}.md`), {
        ...target.deployContext,
        anchor: createContentRootLinkAnchor(resolveAnchorContext(target.harnessId, subagent.source)),
      });
    }
  }
}

/**
 * Retracts owned declared-skill dirs no longer declared, then deploys each declared skill into every targeted harness's
 * skills dir with that harness's transform applied. Orphans were computed against the pre-write filesystem, so
 * retracting before writing lets a slug freed in one dir be re-created in the same sync rather than clobbered.
 */
async function reconcileDeclaredSkills(
  targets: ReadonlyArray<HarnessSkillTarget>,
  orphansByDir: ReadonlyArray<{ skillsDir: string; orphans: ReadonlyArray<string> }>,
  resolvedSkills: ReadonlyArray<ResolvedSkill>,
  resolveAnchorContext: ResolveAnchorContext,
): Promise<void> {
  for (const target of targets) {
    const orphans = orphansByDir.find((entry) => entry.skillsDir === target.skillsDir)?.orphans ?? [];
    for (const dir of orphans) {
      await rm(path.join(target.skillsDir, dir), { recursive: true, force: true });
    }
    for (const skill of resolvedSkills) {
      if (!skillTargetsHarness(skill, target.harnessId)) {
        continue;
      }
      await deploySkill(skill, path.join(target.skillsDir, skill.slug), {
        ...target.deployContext,
        anchor: createSkillLinkAnchor(resolveAnchorContext(target.harnessId, skill.source)),
      });
    }
  }
}

/**
 * Delivers each source's skill support entries into that source's namespace under every targeted harness's skills dir,
 * then retracts the namespaces no declared source claims. Delivery runs first so a source that dropped its last
 * support entry leaves an empty namespace root for the retraction to retire in the same pass.
 */
async function reconcileSourceSupport(
  targets: ReadonlyArray<HarnessSkillTarget>,
  plans: ReadonlyArray<SourceSupportPlan>,
): Promise<void> {
  for (const plan of plans) {
    await deploySourceSupport(plan.destDir, plan.entries);
  }
  // Rooted in the targets rather than the plans: a run that declares no source has no plans, and its support roots
  // are exactly the ones whose every namespace is now undeclared.
  for (const sourcesRoot of resolveSupportRoots(targets)) {
    await retractUndeclaredSourceSupport(sourcesRoot, resolveSupportOutcome(plans, sourcesRoot));
  }
}

/** Lists the support root each targeted harness keeps its per-source namespaces under. */
function resolveSupportRoots(targets: ReadonlyArray<HarnessSkillTarget>): ReadonlyArray<string> {
  return targets.map((target) => path.join(target.skillsDir, SOURCE_SUPPORT_DIR));
}

/** Groups one support root's plans into what delivery leaves there: the namespaces that hold content, and the rest. */
function resolveSupportOutcome(plans: ReadonlyArray<SourceSupportPlan>, sourcesRoot: string): SourceSupportOutcome {
  const rooted = plans.filter((plan) => plan.sourcesRoot === sourcesRoot);
  return {
    surviving: rooted.filter((plan) => plan.kind === 'deliver').map((plan) => plan.name),
    emptied: rooted.filter((plan) => plan.kind !== 'deliver').map((plan) => plan.name),
  };
}

/**
 * Renders every source's support entries for every targeted harness, pairing each result with where it deploys.
 *
 * Rendering is where a defect in a package's reference content surfaces, so calling this ahead of every write is what
 * fails the run — dry-run included — before anything lands. The gate, the dry-run preview, and the delivery pass all
 * read this one result, which is what keeps them from disagreeing about what a source ships and from rendering the
 * same content more than once.
 */
async function renderSourceSupportPlans(
  targets: ReadonlyArray<HarnessSkillTarget>,
  sources: ReadonlyArray<{ name: string; dir: string }>,
  resolveAnchorContext: ResolveAnchorContext,
): Promise<ReadonlyArray<SourceSupportPlan>> {
  const plans: Array<SourceSupportPlan> = [];
  for (const target of targets) {
    const sourcesRoot = path.join(target.skillsDir, SOURCE_SUPPORT_DIR);
    for (const source of sources) {
      const destDir = path.join(sourcesRoot, source.name);
      const entries = await renderSourceSupport(source.dir, {
        ...target.deployContext,
        anchor: createSkillLinkAnchor(resolveAnchorContext(target.harnessId, source.name)),
      });
      plans.push({
        sourcesRoot,
        name: source.name,
        destDir,
        entries,
        kind: resolveSupportVerdict(entries.length > 0, existsSync(destDir)),
      });
    }
  }
  return plans;
}

/** Names what delivery does at a namespace directory, given whether its source ships content and whether it exists. */
function resolveSupportVerdict(shipsContent: boolean, destExists: boolean): SourceSupportPlan['kind'] {
  if (shipsContent) {
    return 'deliver';
  }
  return destExists ? 'retract' : 'none';
}

/**
 * Lists the namespace paths a real run would retract, one per targeted harness's support root, judged against the tree
 * delivery leaves rather than the one on disk. The plans name both halves of that: which namespaces gain content and
 * which delivery empties.
 */
async function planSourceSupportRetractions(
  targets: ReadonlyArray<HarnessSkillTarget>,
  plans: ReadonlyArray<SourceSupportPlan>,
): Promise<ReadonlyArray<string>> {
  const retractions: Array<string> = [];
  for (const sourcesRoot of resolveSupportRoots(targets)) {
    retractions.push(...(await listUndeclaredSourceSupport(sourcesRoot, resolveSupportOutcome(plans, sourcesRoot))));
  }
  return retractions;
}

/**
 * Renders every declared skill against every targeted harness, discarding the output, so a broken include or an
 * unmapped tool placeholder throws before any file is written. The deploy pass re-renders at write time; this pass
 * exists only to fail the run closed, including under `--dry-run`.
 */
async function assertDeclaredSkillsRender(
  targets: ReadonlyArray<HarnessSkillTarget>,
  resolvedSkills: ReadonlyArray<ResolvedSkill>,
  resolveAnchorContext: ResolveAnchorContext,
): Promise<void> {
  for (const target of targets) {
    for (const skill of resolvedSkills) {
      if (!skillTargetsHarness(skill, target.harnessId)) {
        continue;
      }
      await renderSkillDirectory(skill.srcDir, skill.slug, skill.contentRoot, {
        ...target.deployContext,
        anchor: createSkillLinkAnchor(resolveAnchorContext(target.harnessId, skill.source)),
      });
    }
  }
}

/**
 * Renders every declared subagent against every targeted harness, discarding the output, so an unmapped tool
 * placeholder or a rulebook token throws before any file is written. `reconcileDeclaredSubagents` re-renders at write
 * time; this pass exists only to fail the run closed, including under `--dry-run`.
 */
async function assertDeclaredSubagentsRender(
  targets: ReadonlyArray<HarnessSubagentTarget>,
  resolvedSubagents: ReadonlyArray<ResolvedSubagent>,
  resolveAnchorContext: ResolveAnchorContext,
): Promise<void> {
  for (const target of targets) {
    for (const subagent of resolvedSubagents) {
      await renderSubagent(subagent, {
        ...target.deployContext,
        anchor: createContentRootLinkAnchor(resolveAnchorContext(target.harnessId, subagent.source)),
      });
    }
  }
}

/**
 * Renders every resolved rulebook against every targeted harness, discarding the output, so a link target the
 * delivery pipeline cannot honor throws before any file is written. Both delivery passes re-render at write time;
 * this pass exists only to fail the run closed, including under `--dry-run`.
 */
function assertRulebooksRender(
  harnessIds: ReadonlyArray<HarnessId>,
  resolved: ReadonlyArray<ResolvedRulebook>,
  resolveRulebookContext: ResolveRulebookContext,
): void {
  for (const harnessId of harnessIds) {
    for (const rulebook of resolved) {
      renderRulebookBody(rulebook.body, rulebook.slug, resolveRulebookContext(harnessId, rulebook.source));
    }
  }
}

/**
 * Carries out each ambient host's plan, regenerating the region's content wholesale (an empty ambient set empties an
 * existing region). Both domains share this one path, differing only in the host each targets and in who owns region
 * creation there.
 */
async function deliverAmbient(plans: ReadonlyArray<PlannedAmbientHost>): Promise<void> {
  for (const { hostPath, plan } of plans) {
    if (plan.kind === 'skip') {
      continue;
    }
    await writeIfChanged(hostPath, plan.content);
  }
}

/** A probed ambient host: its content when present, plus how its region stands. */
type AmbientHostState =
  { readonly status: 'missing' } | { readonly status: 'malformed' | 'no-region' | 'ready'; readonly content: string };

/** What a sync does to one ambient host: write the given content, or skip for the given reason. */
export type AmbientHostPlan =
  | { readonly kind: 'skip'; readonly reason: AmbientSkipReason }
  | { readonly kind: 'write'; readonly action: 'append' | 'create' | 'inject'; readonly content: string };

/** Why one ambient host is skipped. A stale install carries the probe status that names its remedy. */
export type AmbientSkipReason =
  | { readonly cause: 'damaged-region' }
  | { readonly cause: 'not-needed' }
  | { readonly cause: 'stale-install'; readonly status: 'malformed' | 'missing' | 'no-region' };

/** One targeted ambient host paired with the plan a sync carries out there. */
export interface PlannedAmbientHost {
  readonly hostPath: string;
  readonly plan: AmbientHostPlan;
}

/**
 * Decides what a sync does to one ambient host. The harness-home host is `install`'s to create, so anything but a
 * rendered region is skipped with the remedy named. The project-local host is sync's own, and is materialized only
 * when there is ambient content to carry: an absent host with nothing to deliver stays absent, matching how the
 * `prompts.yml` region and the legacy ambient host withdraw rather than persist empty.
 */
function planAmbientHost(hostKind: AmbientHostKind, host: AmbientHostState, body: string): AmbientHostPlan {
  if (host.status === 'ready') {
    return { kind: 'write', action: 'inject', content: injectAmbientRegion(host.content, body) };
  }
  if (hostKind === 'harness-home') {
    return { kind: 'skip', reason: { cause: 'stale-install', status: host.status } };
  }
  if (body === '') {
    return { kind: 'skip', reason: { cause: 'not-needed' } };
  }
  // A damaged region never reaches a write: `assertAmbientHostsWritable` has already failed the run.
  return host.status === 'malformed'
    ? { kind: 'skip', reason: { cause: 'damaged-region' } }
    : {
        kind: 'write',
        action: host.status === 'missing' ? 'create' : 'append',
        content: appendAmbientRegion(host.status === 'missing' ? '' : host.content, body),
      };
}

/** Pairs each targeted host with the plan a sync carries out there, derived once so both paths read the same one. */
async function planAmbientHosts(
  hosts: ReadonlyArray<AmbientHostTarget>,
  domain: SyncDomain,
  resolved: ReadonlyArray<ResolvedRulebook>,
  resolveRulebookContext: ResolveRulebookContext,
): Promise<ReadonlyArray<PlannedAmbientHost>> {
  return Promise.all(
    hosts.map(async ({ harnessId, hostPath }) => ({
      hostPath,
      plan: planAmbientHost(
        domain.ambient,
        await probeAmbientHost(hostPath),
        renderAmbientBody(resolved, harnessId, resolveRulebookContext),
      ),
    })),
  );
}

/**
 * The hosts a sync writes that git does not ignore, so machine-local guidance does not quietly become a commit
 * candidate. Purely advisory: an ignored host is omitted, and so is one the check cannot answer for — the project may
 * not be a repository at all, which is no reason to fail a sync. A host the run skips is never asked about.
 */
async function findUnignoredHosts(
  projectRoot: string,
  plans: ReadonlyArray<PlannedAmbientHost>,
): Promise<ReadonlyArray<string>> {
  const unignored: Array<string> = [];
  for (const { hostPath, plan } of plans) {
    if (plan.kind === 'write' && (await checkGitIgnored(projectRoot, hostPath)) === false) {
      unignored.push(hostPath);
    }
  }
  return unignored;
}

/** Probes an ambient host for its content and region state. */
async function probeAmbientHost(hostPath: string): Promise<AmbientHostState> {
  let content: string;
  try {
    content = await readFile(hostPath, 'utf8');
  } catch (error: unknown) {
    if (isMissingFile(error)) {
      return { status: 'missing' };
    }
    throw error;
  }
  switch (classifyAmbientRegion(content)) {
    case 'complete':
      return { status: 'ready', content };
    case 'malformed':
      return { status: 'malformed', content };
    case 'absent':
      return { status: 'no-region', content };
  }
}

/**
 * Throws when a host `sync` would write already carries a damaged region — an unmatched marker, or more than one.
 * Only the sync-owned project-local host can be appended to, so only it needs the guard; the harness-home path skips
 * such a file with a warning instead. Runs before any write so a dry-run surfaces the conflict with nothing changed.
 */
async function assertAmbientHostsWritable(
  hosts: ReadonlyArray<AmbientHostTarget>,
  domain: SyncDomain,
  resolved: ReadonlyArray<ResolvedRulebook>,
): Promise<void> {
  // Asks whether anything would be delivered, which is a property of the declaration alone. Rendering could answer it
  // too, but rendering can now fail on a bad link, and this guard is about region damage rather than link validity.
  if (domain.ambient !== 'project-local' || resolved.every((rulebook) => !rulebook.ambient)) {
    return;
  }
  const malformed: Array<string> = [];
  for (const { hostPath } of hosts) {
    if ((await probeAmbientHost(hostPath)).status === 'malformed') {
      malformed.push(hostPath);
    }
  }
  if (malformed.length > 0) {
    throw new Error(
      `Refusing to deliver ambient guidance into ${malformed.length} file(s) carrying a damaged ambient region ` +
        `(an unmatched marker, or more than one region): ${malformed.join(', ')}. Repair the codeassembly-ambient ` +
        'markers, then re-run.',
    );
  }
}

/**
 * Retires a former ambient host: removes the sync-owned rulebook blocks it carries and writes back the stripped
 * remainder, so hand-authored content survives. Ambient delivery targets the harness regions now, and a lingering
 * copy would present stale guidance as current. `deleteWhenEmpty` deletes a host left holding nothing — right for
 * one sync created itself, wrong for a hand-authored file like the project's own `AGENTS.md`, which is never
 * deleted. A missing host, and one carrying nothing to retire, are both no-ops.
 */
async function retireAmbientHost(
  options: InstallOptions,
  hostPath: string,
  deleteWhenEmpty: boolean,
): Promise<Retirement | undefined> {
  let content: string;
  try {
    content = await readFile(hostPath, 'utf8');
  } catch (error: unknown) {
    if (isMissingFile(error)) {
      return undefined;
    }
    throw error;
  }

  let stripped = content;
  for (const slug of extractInstalledSlugs(content)) {
    stripped = removeRulebook(stripped, slug);
  }
  const deletable = deleteWhenEmpty && stripped.trim() === '';
  if (stripped === content && !deletable) {
    return undefined;
  }

  if (!options.dryRun) {
    await (deletable ? rm(hostPath, { force: true }) : writeIfChanged(hostPath, stripped));
  }
  return { kind: 'ambient-host', hostPath, emptied: deletable };
}

/**
 * Retires the neutral rulebook tree at `<baseDir>/.agents/rulebooks/`. Nothing reads it, so it is removed rather than
 * maintained. Only the `.md` files sync materialized are deleted, and the directory itself only once nothing else
 * remains in it, so anything a user placed alongside them survives. A missing directory is a no-op.
 */
async function retireNeutralRulebooks(options: InstallOptions, baseDir: string): Promise<Retirement | undefined> {
  const neutralDir = path.join(baseDir, '.agents', 'rulebooks');
  if (!existsSync(neutralDir)) {
    return undefined;
  }

  if (!options.dryRun) {
    const entries = await readDirEntries(neutralDir);
    for (const entry of entries) {
      if (entry.isFile() && entry.name.endsWith('.md')) {
        await rm(path.join(neutralDir, entry.name), { force: true });
      }
    }
    if ((await readDirEntries(neutralDir)).length === 0) {
      await rmdir(neutralDir);
    }
  }
  return { kind: 'neutral-rulebooks', dir: neutralDir };
}

/**
 * Retires the outputs this domain no longer produces: the neutral rulebook tree in both domains, and, in the project
 * domain, the rulebook blocks the hand-authored project guidance used to host. Runs on every sync that has a
 * declaration to act on, so a project picks the retirement up on its next run rather than needing a migration step.
 *
 * Both guidance locations are swept. A project that renames `.agents/PROJECT.md` to the repository-root `AGENTS.md`
 * before its next sync would otherwise carry the stale blocks into the new location for good.
 */
async function retireRetiredOutputs(options: InstallOptions, domain: SyncDomain): Promise<ReadonlyArray<Retirement>> {
  const legacyHosts =
    domain.ambient === 'project-local'
      ? [path.join(domain.baseDir, '.agents', 'PROJECT.md'), path.join(domain.baseDir, 'AGENTS.md')]
      : [];
  const retirements = [await retireNeutralRulebooks(options, domain.baseDir)];
  for (const hostPath of legacyHosts) {
    retirements.push(await retireAmbientHost(options, hostPath, false));
  }
  return retirements.filter((retirement) => retirement !== undefined);
}

/**
 * Renders the ambient rulebooks as concatenated sentinel blocks beneath the generated-region note — the wholesale
 * content of one harness's ambient region. The context is one harness's, so the same rulebook yields that harness's
 * own absolute paths. An empty result stays empty: the note belongs to generated content, and callers read emptiness
 * as "nothing to deliver here".
 */
function renderAmbientBody(
  resolved: ReadonlyArray<ResolvedRulebook>,
  harnessId: HarnessId,
  resolveRulebookContext: ResolveRulebookContext,
): string {
  let body = '';
  for (const rulebook of resolved) {
    if (!rulebook.ambient) {
      continue;
    }
    const context = resolveRulebookContext(harnessId, rulebook.source);
    body = injectRulebook(body, rulebook.slug, renderRulebookBody(rulebook.body, rulebook.slug, context));
  }
  // Prepend rather than seed the loop: seeding would route the note through `injectRulebook`, which separates it from
  // the first block with a blank line and would leave the note standing as the whole body when nothing is ambient.
  return body === '' ? '' : `${ambientRegionNote}\n${body}`;
}

/**
 * The per-harness inputs a rulebook render depends on: the harness config's own segments and sigils, the anchor its
 * link targets resolve through, and the deployed rulebooks indexed by slug, so a `{rulebook:<slug>}` token renders the
 * skill name its target deploys under.
 */
function buildRulebookRenderContext(
  harnessId: HarnessId,
  resolved: ReadonlyArray<ResolvedRulebook>,
  anchor: ResolveLinkAnchor,
): RulebookRenderContext {
  const config = HARNESSES[harnessId];
  return {
    anchor,
    homeDir: config.homeDir,
    harnessId: config.id,
    skillSigil: config.skillSigil,
    subagentSigil: config.subagentSigil,
    rulebooks: new Map(
      resolved.map((rulebook) => [rulebook.slug, { skillName: rulebook.skillName, skill: rulebook.skill }]),
    ),
  };
}

/**
 * Lists the guidance files whose ambient regions a sync of `domain` targets — one per targeted harness, each paired
 * with the harness id its content is rendered for.
 */
function resolveAmbientHosts(
  harnessIds: ReadonlyArray<HarnessId>,
  domain: SyncDomain,
): ReadonlyArray<AmbientHostTarget> {
  return harnessIds.map((harnessId) => ({
    harnessId,
    hostPath: resolveAmbientHostPath(harnessId, domain.ambient, domain.baseDir),
  }));
}

/**
 * Reconciles the Rovo Dev `prompts.yml` index so it lists the user-invocable skills currently in the harness skills
 * dir. The deployed skills are projected into a codeassembly-owned region merged into the shared file, preserving any
 * foreign entries; when no skills remain, the region is stripped — and the file deleted when nothing foreign is left. A
 * no-op for non-Rovo Dev harnesses and for a file carrying no codeassembly region. Both domains share this one path, so
 * the home file is merged rather than whole-file overwritten, matching the repo file's non-clobbering shape.
 */
async function refreshPromptsYml(harnessIds: ReadonlyArray<HarnessId>, domain: SyncDomain): Promise<void> {
  for (const harnessId of harnessIds) {
    if (harnessId !== 'rovo') {
      continue;
    }
    const { harnessHome, skillsDir } = resolveHarnessPaths(harnessId, domain.baseDir);
    const promptsPath = path.join(harnessHome, 'prompts.yml');
    const entries = await collectPromptEntries(skillsDir);
    const existing = await readFileOrEmpty(promptsPath);

    if (entries !== undefined && entries.length > 0) {
      await writeIfChanged(promptsPath, injectPromptsRegion(existing, renderPromptEntries(entries)));
      continue;
    }

    // No skills remain: strip our region, deleting the file when nothing foreign survives. A file we never owned (no
    // region) is left untouched.
    if (!hasPromptsRegion(existing)) {
      continue;
    }
    const stripped = removePromptsRegion(existing);
    await (stripped.trim() === '' ? rm(promptsPath, { force: true }) : writeIfChanged(promptsPath, stripped));
  }
}

/** Lists the Rovo Dev `prompts.yml` paths a sync of `domain` would reconcile — one per targeted Rovo Dev harness. */
function resolvePromptsYmlPaths(harnessIds: ReadonlyArray<HarnessId>, domain: SyncDomain): ReadonlyArray<string> {
  return harnessIds
    .filter((harnessId) => harnessId === 'rovo')
    .map((harnessId) => path.join(resolveHarnessPaths(harnessId, domain.baseDir).harnessHome, 'prompts.yml'));
}

/**
 * Attributes each deployed rulebook, skill, and subagent to the source it resolved from, flagging any source-resolved
 * artifact whose slug also exists in the library as shadowing it. The library probe runs only for source-resolved
 * artifacts — a library-resolved artifact cannot shadow the library — and is batched across all of them.
 */
async function buildResolutionReport(
  resolver: SourceResolver,
  rulebooks: ReadonlyArray<ResolvedRulebook>,
  skills: ReadonlyArray<ResolvedSkill>,
  subagents: ReadonlyArray<ResolvedSubagent>,
): Promise<ReadonlyArray<ResolutionEntry>> {
  const artifacts: Array<{ type: ArtifactType; slug: string; source: string | undefined }> = Array.from(
    rulebooks,
    (rulebook) => ({ type: 'rulebook', slug: rulebook.slug, source: rulebook.source }),
  );
  for (const skill of skills) {
    artifacts.push({ type: 'skill', slug: skill.slug, source: skill.source });
  }
  for (const subagent of subagents) {
    artifacts.push({ type: 'subagent', slug: subagent.slug, source: subagent.source });
  }
  return Promise.all(
    artifacts.map(async (artifact) => ({
      ...artifact,
      shadowsLibrary:
        artifact.source !== undefined && (await hasLibraryArtifact(resolver, artifact.type, artifact.slug)),
    })),
  );
}

/**
 * Resolves one harness's project-local subagents dir together with the per-harness inputs the deploy transform needs:
 * the harness overlay YAML, its tool-name mapping, the link anchor, the home-dir segment, and the harness id. Passing
 * `projectRoot` as the base keeps delivery project-scoped, matching the skill passes.
 */
async function resolveSubagentTarget(
  harnessId: HarnessId,
  projectRoot: string,
  contentDir: string,
  guidanceHookFills: GuidanceHookFills | undefined,
): Promise<HarnessSubagentTarget> {
  const harnessConfig = HARNESSES[harnessId];
  const overlayYaml = await loadHarnessOverlay(contentDir, harnessConfig);
  return {
    harnessId,
    subagentsDir: resolveHarnessPaths(harnessId, projectRoot).subagentsDir,
    deployContext: {
      overlayYaml,
      toolMapping: loadToolMapping(overlayYaml),
      homeDir: harnessConfig.homeDir,
      harnessId: harnessConfig.id,
      skillSigil: harnessConfig.skillSigil,
      subagentSigil: harnessConfig.subagentSigil,
      guidanceHookFills,
    },
  };
}

/**
 * Resolves one harness's project-local skills dir together with the per-harness inputs the skill transform needs: the
 * tool-name mapping (from the harness overlay), the link anchor, the home-dir segment, and the harness id.
 * Passing `projectRoot` as the base keeps delivery project-scoped.
 */
async function resolveSkillTarget(
  harnessId: HarnessId,
  projectRoot: string,
  contentDir: string,
  guidanceHookFills: GuidanceHookFills | undefined,
): Promise<HarnessSkillTarget> {
  const harnessConfig = HARNESSES[harnessId];
  const overlayYaml = await loadHarnessOverlay(contentDir, harnessConfig);
  return {
    harnessId,
    skillsDir: resolveHarnessPaths(harnessId, projectRoot).skillsDir,
    deployContext: {
      toolMapping: loadToolMapping(overlayYaml),
      homeDir: harnessConfig.homeDir,
      harnessId: harnessConfig.id,
      skillSigil: harnessConfig.skillSigil,
      subagentSigil: harnessConfig.subagentSigil,
      guidanceHookFills,
    },
  };
}

// endregion | Helpers
