#!/usr/bin/env bash
# Emit canonical artifact-frontmatter fields as YAML (default) or JSON.
#
# Reads `.agents/{sanitized-branch}.branch-manifest.json` (produced on demand by the bundled `derive-session-context`
# helper) for session-level fields and runs git for the rest. Skills consume the
# output to populate the universal portion of their artifact frontmatter without repeating the underlying shell
# logic. When the manifest is absent, the script invokes the bundled deriver to create it; no precondition
# applies to callers (main agents, subagents, and bash scripts can all rely on the same fast path).
#
# Usage:
#   resolve-frontmatter.sh --skill NAME --interactive true|false [...]
#   resolve-frontmatter.sh --format json
#   resolve-frontmatter.sh --help
#
# Flags:
#   --skill NAME              provenance.skill value (required in yaml mode).
#   --interactive true|false  provenance.isInteractive value (required in yaml mode).
#   --model ID                provenance.model value (optional).
#   --extra KEY=VALUE         Append a scalar extension key (repeatable).
#                             Values may contain `=`; split on the first `=`.
#   --extra-list KEY=v1,v2,…  Append a flow-list extension key (repeatable).
#                             Values are split on `,`.
#   --override KEY=VALUE      Force a canonical/provenance field to VALUE.
#                             Empty VALUE force-omits the key.
#   --format yaml|json        Output format (default `yaml`).
#   --help, -h                Show usage and exit 0.
#
# Output (yaml mode, stdout): A complete YAML frontmatter block including
# `---` delimiters, followed by the seal marker line that identifies the file
# as a point-in-time record. Field order:
#
#   provenance:
#     skill, timestamp, baseSha, isInteractive, model     (camelCase)
#   ticket_id, ticket_ref, branch, commit, pr, run_id     (snake_case)
#   {--extra / --extra-list extensions in insertion order}
#
# Output (json mode, stdout): a single JSON object, backward-compatible
# with prior `--format json` (default) callers. Keys: branch, commit,
# baseSha, pr, ticket_id, ticket_ref, scm, timestamp, run_id.
#
# Omission rules (both formats): any key whose resolved value is empty is
# omitted entirely. `--override KEY=` with empty value force-omits even
# when the script resolved a value.
#
# The `pr` field is not resolved by this script. It is populated only when a
# caller passes `--override pr=<url>`; PR-aware skills supply the URL they hold.
#
# Exit codes:
#   0  Success.
#   1  Git could not read the repository or resolve the branch, missing required commands (`jq`, `git`),
#      required-arg violation in yaml mode, or the bundled `derive-session-context` helper itself failed.

set -euo pipefail

readonly PROG="$(basename "$0")"

# Marks the artifact as a record rather than a working file. It is emitted into every artifact so the prohibition is
# present in the file an agent has open, rather than only in the standing guidance it may not have loaded.
readonly SEAL_MARKER='<!-- Sealed record. Do not edit this file to match anything downstream, and do not report its divergence from current state. -->'

show_usage() {
  local exit_code="${1:-1}"
  cat <<EOF
Usage:
  $PROG --skill NAME --interactive true|false [--model ID]
       [--extra KEY=VALUE ...] [--extra-list KEY=v1,v2,... ...]
       [--override KEY=VALUE ...] [--format yaml|json]
  $PROG --format json
  $PROG --help

Emit canonical artifact-frontmatter fields as YAML (default) or JSON.
See script header for field list, ordering, and omission semantics.
EOF
  exit "$exit_code"
}

# Main flow
main() {
  # -- Argument parsing --
  local format="yaml"
  local skill="" model=""
  local interactive=""
  local interactive_set=false
  declare -a extra_keys=()
  declare -A extra_values=()
  declare -A extra_kinds=()
  declare -A overrides=()

  while [[ "$#" -gt 0 ]]; do
    case "$1" in
    --help | -h)
      show_usage 0
      ;;
    --format)
      [[ "$#" -ge 2 ]] || fail "missing value for --format"
      format="$2"
      shift 2
      ;;
    --skill)
      [[ "$#" -ge 2 ]] || fail "missing value for --skill"
      skill="$2"
      shift 2
      ;;
    --interactive)
      [[ "$#" -ge 2 ]] || fail "missing value for --interactive"
      interactive="$2"
      interactive_set=true
      shift 2
      ;;
    --model)
      [[ "$#" -ge 2 ]] || fail "missing value for --model"
      model="$2"
      shift 2
      ;;
    --extra)
      [[ "$#" -ge 2 ]] || fail "missing value for --extra"
      add_extra "scalar" "$2" extra_keys extra_values extra_kinds
      shift 2
      ;;
    --extra-list)
      [[ "$#" -ge 2 ]] || fail "missing value for --extra-list"
      add_extra "list" "$2" extra_keys extra_values extra_kinds
      shift 2
      ;;
    --override)
      [[ "$#" -ge 2 ]] || fail "missing value for --override"
      add_override "$2" overrides
      shift 2
      ;;
    *)
      echo "$PROG: Unexpected argument: $1" >&2
      show_usage 1
      ;;
    esac
  done

  case "$format" in
  yaml | json) ;;
  *) fail "unknown --format: $format (expected yaml|json)" ;;
  esac

  if [[ "$format" == "yaml" ]]; then
    [[ -n "$skill" ]] || fail "--skill is required in yaml mode"
    [[ "$interactive_set" == "true" ]] || fail "--interactive is required in yaml mode"
    case "$interactive" in
    true | false) ;;
    *) fail "--interactive must be true or false (got: $interactive)" ;;
    esac
  fi

  # -- Resolve session-level values --
  require_commands jq git

  # Probe readability before resolving the branch, so an unreadable repository is named as such
  # rather than reported as an unresolvable branch.
  local branch git_err
  if ! git_err="$(git rev-parse --git-dir 2>&1 >/dev/null)"; then
    fail "cannot read the git repository: $git_err"
  fi
  if ! branch=$(current_branch); then
    git_err="$(git rev-parse --abbrev-ref HEAD 2>&1 >/dev/null || true)"
    fail "git could not resolve the current branch: $git_err"
  fi

  local manifest_path
  manifest_path=$(resolve_manifest_path "$branch") || fail "could not resolve repo root for manifest lookup"

  local manifest
  if ! manifest=$(read_manifest "$branch"); then
    if ! manifest=$(derive_manifest); then
      fail "could not read or derive branch manifest"
    fi
  fi

  local commit
  commit=$(git rev-parse --short HEAD 2>/dev/null) || fail "could not resolve HEAD commit"

  local scm ticket_id ticket_ref default_branch
  # Read `scm`, falling back to the legacy `platform` key so a pre-rename branch manifest still
  # resolves the right VCS host (this path validates only JSON well-formedness, so it would not
  # otherwise trigger a recompose). The fallback is temporary; a separate ticket covers its removal.
  scm=$(jq -r '.scm // .platform // "github"' <<<"$manifest")
  ticket_id=$(jq -r '.ticket_id // ""' <<<"$manifest")
  ticket_ref=$(jq -r '.ticket_ref // ""' <<<"$manifest")
  default_branch=$(jq -r '.default_branch // "origin/main"' <<<"$manifest")

  local base_sha pr_url run_id timestamp
  base_sha=$(resolve_base_sha "$default_branch")
  pr_url=""
  run_id=$(resolve_run_id)
  timestamp=$(date -u +%Y-%m-%dT%H:%M:%SZ)

  # -- Apply overrides --
  branch=$(apply_override "branch" "$branch" overrides)
  commit=$(apply_override "commit" "$commit" overrides)
  base_sha=$(apply_override "baseSha" "$base_sha" overrides)
  pr_url=$(apply_override "pr" "$pr_url" overrides)
  ticket_id=$(apply_override "ticket_id" "$ticket_id" overrides)
  ticket_ref=$(apply_override "ticket_ref" "$ticket_ref" overrides)
  scm=$(apply_override "scm" "$scm" overrides)
  timestamp=$(apply_override "timestamp" "$timestamp" overrides)
  run_id=$(apply_override "run_id" "$run_id" overrides)

  if [[ "$format" == "json" ]]; then
    emit_json "$branch" "$commit" "$base_sha" "$pr_url" \
      "$ticket_id" "$ticket_ref" "$scm" "$timestamp" "$run_id"
  else
    emit_yaml \
      "$skill" "$timestamp" "$base_sha" "$interactive" "$model" \
      "$ticket_id" "$ticket_ref" "$branch" "$commit" "$pr_url" "$run_id" \
      extra_keys extra_values extra_kinds
  fi
}

# Parses a `KEY=VALUE` argument into the caller's `key` and `value` variables.
# The `flag` argument is used only for error messages. Fails when `=` is missing or the key portion is empty.
parse_key_value() {
  local arg="$1" flag="$2"
  local -n key_out="$3"
  local -n value_out="$4"
  if [[ "$arg" != *"="* ]]; then
    fail "$flag argument missing '=': $arg"
  fi
  key_out="${arg%%=*}"
  value_out="${arg#*=}"
  [[ -n "$key_out" ]] || fail "$flag argument has empty key"
}

# Appends an extension key/value to the caller's ordered list. Splits the
# argument once on the first `=`. `kind` is either `scalar` or `list`.
add_extra() {
  local kind="$1" arg="$2"
  local -n keys_ref="$3"
  local -n values_ref="$4"
  local -n kinds_ref="$5"
  local key value
  parse_key_value "$arg" "--extra/--extra-list" key value
  if [[ -z "${kinds_ref[$key]:-}" ]]; then
    keys_ref+=("$key")
  else
    warn "duplicate --extra/--extra-list key '$key': replacing previous value"
  fi
  values_ref["$key"]="$value"
  kinds_ref["$key"]="$kind"
}

# Records an override key=value. Empty value force-omits the key on emit.
add_override() {
  local arg="$1"
  local -n overrides_ref="$2"
  local key value
  parse_key_value "$arg" "--override" key value
  overrides_ref["$key"]="$value"
}

# Returns the overridden value when the key has been overridden, otherwise the resolved value.
# The empty-string override force-omits.
apply_override() {
  local key="$1" resolved="$2"
  local -n overrides_ref="$3"
  if [[ -n "${overrides_ref[$key]+set}" ]]; then
    printf '%s' "${overrides_ref[$key]}"
  else
    printf '%s' "$resolved"
  fi
}

# Prints short SHA of `default_branch` (e.g., `origin/main`) or empty if unresolvable.
# Under a shallow clone or a missing remote, the output is silently empty.
resolve_base_sha() {
  local ref="$1"
  git rev-parse --short "$ref" 2>/dev/null || true
}

# Resolves the active run ID by reading the breadcrumb written by the orchestrate engine at
# `.claude/tmp/active-run-dir`. Empty when no orchestrated run is active.
resolve_run_id() {
  local breadcrumb=".claude/tmp/active-run-dir"
  [[ -r "$breadcrumb" ]] || return 0
  local run_dir
  run_dir=$(<"$breadcrumb")
  basename "$run_dir"
}

# Gets the current branch name. Returns non-zero outside a git repository.
current_branch() {
  git rev-parse --abbrev-ref HEAD 2>/dev/null
}

# Resolves the absolute path to the branch manifest for the given branch.
# Anchors at the repo root via `git rev-parse --show-toplevel`, so the lookup is independent of the caller's cwd.
# Inside a git worktree, this returns the worktree's `.agents/` path, matching where the bundled
# `derive-session-context` helper writes the manifest. Returns non-zero outside a git repository.
resolve_manifest_path() {
  local branch="$1"
  local sanitized repo_root
  sanitized=$(sanitize_branch "$branch")
  repo_root=$(git rev-parse --show-toplevel 2>/dev/null) || return 1
  printf '%s/.agents/%s.branch-manifest.json' "$repo_root" "$sanitized"
}

# Reads the branch manifest for the given branch. Echoes the JSON content.
# Returns non-zero when the manifest is missing, the path cannot be resolved, or the file content
# is not valid JSON. Treating corrupt content as a cache miss lets the caller fall through to
# `derive_manifest`, which recomposes from scratch, matching the recovery behavior on the TS side.
read_manifest() {
  local branch="$1"
  local path content
  path=$(resolve_manifest_path "$branch") || return 1
  [[ -r "$path" ]] || return 1
  content=$(cat "$path")
  jq empty <<<"$content" 2>/dev/null || return 1
  printf '%s\n' "$content"
}

# Invokes the bundled `derive-session-context` helper to compose the branch manifest on demand.
# Echoes the JSON manifest emitted on the helper's stdout. On failure, the helper's stderr is
# passed through verbatim to the caller's stderr and the function returns non-zero.
#
# Bundle location: `../skills/derive-session-context/derive-session-context.mjs`, anchored relative
# to this script's own install path (e.g., `~/.claude/scripts/resolve-frontmatter.sh` -> bundle at
# `~/.claude/skills/derive-session-context/derive-session-context.mjs`). The install layout shared
# by Claude Code and Rovo Dev makes this relative-pair invariant. Tests that source this script
# rather than executing it directly can set `RESOLVE_FRONTMATTER_BUNDLE_PATH` to point at an
# alternate location.
derive_manifest() {
  local bundle_path
  bundle_path="$(resolve_bundle_path)"
  if [[ ! -r "$bundle_path" ]]; then
    echo "$PROG: bundled deriver not found at $bundle_path" >&2
    return 1
  fi
  if ! command -v node >/dev/null 2>&1; then
    echo "$PROG: 'node' command not found on PATH; cannot run bundled deriver at $bundle_path" >&2
    return 1
  fi
  # Anchor the deriver's cwd at the repo root so its manifest write goes to the same path
  # `read_manifest` looks at (`{repo_root}/.agents/{branch}.branch-manifest.json`). Without this,
  # a call from a subdirectory would write to `{subdir}/.agents/` while the reader looks at the
  # repo root, causing every call to re-invoke the deriver and leaving stale manifests in
  # unintended subdirectories.
  local repo_root
  repo_root=$(git rev-parse --show-toplevel 2>/dev/null) || {
    echo "$PROG: could not resolve repo root for deriver invocation" >&2
    return 1
  }
  # Tests can set RESOLVE_FRONTMATTER_BUNDLE_ARGS to pass extra args to the deriver (e.g.,
  # `--home /tmp/xyz` to isolate the global preferences lookup from the developer's real home).
  # In production no extra args are needed beyond `--cwd`.
  if [[ -n "${RESOLVE_FRONTMATTER_BUNDLE_ARGS:-}" ]]; then
    # shellcheck disable=SC2086 -- intentional word-splitting of the args string.
    node "$bundle_path" --cwd "$repo_root" $RESOLVE_FRONTMATTER_BUNDLE_ARGS
  else
    node "$bundle_path" --cwd "$repo_root"
  fi
}

# Resolves the absolute path to the bundled `derive-session-context.mjs`.
# Honors `RESOLVE_FRONTMATTER_BUNDLE_PATH` when set (used by shellspec tests that source this
# script rather than executing it directly); otherwise computes the path relative to this script's
# own install location.
resolve_bundle_path() {
  if [[ -n "${RESOLVE_FRONTMATTER_BUNDLE_PATH:-}" ]]; then
    printf '%s' "$RESOLVE_FRONTMATTER_BUNDLE_PATH"
    return 0
  fi
  local source_path script_dir
  source_path="${BASH_SOURCE[0]:-$0}"
  script_dir="$(cd "$(dirname "$source_path")" && pwd)"
  printf '%s/../skills/derive-session-context/derive-session-context.mjs' "$script_dir"
}

# Sanitizes a branch name for filesystem use: Replaces `/` with `-` and trims any trailing `-` characters.
# Mirrors the sanitization performed by the bundled `derive-session-context` helper; the two must agree
# on the manifest filename. Loops the trailing-hyphen strip rather than using `${branch%%-}` (which only
# strips one) so a branch like `feat//` produces `feat` in both implementations.
sanitize_branch() {
  local branch="$1"
  branch="${branch//\//-}"
  while [[ "$branch" == *- ]]; do
    branch="${branch%-}"
  done
  printf '%s' "$branch"
}

# Constructs the JSON output from resolved values.
# Optional fields are omitted (rather than emitted as null or empty) so consumers can rely on `has(field)` semantics.
emit_json() {
  local branch="$1" commit="$2" base_sha="$3" pr_url="$4"
  local ticket_id="$5" ticket_ref="$6" scm="$7" timestamp="$8" run_id="$9"

  jq -n \
    --arg branch "$branch" \
    --arg commit "$commit" \
    --arg base_sha "$base_sha" \
    --arg pr "$pr_url" \
    --arg ticket_id "$ticket_id" \
    --arg ticket_ref "$ticket_ref" \
    --arg scm "$scm" \
    --arg timestamp "$timestamp" \
    --arg run_id "$run_id" \
    '
    {
      branch: $branch,
      commit: $commit,
      scm: $scm,
      timestamp: $timestamp
    }
    + (if $base_sha   == "" then {} else { baseSha:    $base_sha   } end)
    + (if $pr         == "" then {} else { pr:         $pr         } end)
    + (if $ticket_id  == "" then {} else { ticket_id:  $ticket_id  } end)
    + (if $ticket_ref == "" then {} else { ticket_ref: $ticket_ref } end)
    + (if $run_id     == "" then {} else { run_id:     $run_id     } end)
    '
}

# Emits the canonical YAML frontmatter block, including `---` delimiters. Empty values are omitted.
# Field order is fixed: Provenance block, canonical top-level fields, caller-supplied extensions in insertion order.
emit_yaml() {
  local skill="$1" timestamp="$2" base_sha="$3" interactive="$4" model="$5"
  local ticket_id="$6" ticket_ref="$7" branch="$8" commit="$9" pr_url="${10}" run_id="${11}"
  local -n yaml_extra_keys="${12}"
  local -n yaml_extra_values="${13}"
  local -n yaml_extra_kinds="${14}"

  printf '%s\n' "---"

  # Provenance block
  printf '%s\n' "provenance:"
  emit_yaml_indented_scalar "skill" "$skill"
  emit_yaml_indented_scalar "timestamp" "$timestamp"
  [[ -n "$base_sha" ]] && emit_yaml_indented_scalar "baseSha" "$base_sha"
  # isInteractive is a boolean; emit unquoted true|false.
  printf '  %s: %s\n' "isInteractive" "$interactive"
  [[ -n "$model" ]] && emit_yaml_indented_scalar "model" "$model"

  # Canonical top-level fields
  [[ -n "$ticket_id" ]] && emit_yaml_scalar "ticket_id" "$ticket_id"
  [[ -n "$ticket_ref" ]] && emit_yaml_scalar "ticket_ref" "$ticket_ref"
  emit_yaml_scalar "branch" "$branch"
  emit_yaml_scalar "commit" "$commit"
  [[ -n "$pr_url" ]] && emit_yaml_scalar "pr" "$pr_url"
  [[ -n "$run_id" ]] && emit_yaml_scalar "run_id" "$run_id"

  # Extension fields in insertion order
  local key kind value
  for key in "${yaml_extra_keys[@]+"${yaml_extra_keys[@]}"}"; do
    value="${yaml_extra_values[$key]}"
    kind="${yaml_extra_kinds[$key]}"
    if [[ "$kind" == "list" ]]; then
      # Flow-list extensions intentionally emit `key: []` for empty values
      # (see `emit_yaml_flow_list`); only scalar extensions are subject to the canonical-field omission rule.
      emit_yaml_flow_list "$key" "$value"
    else
      [[ -n "$value" ]] || continue
      emit_yaml_scalar "$key" "$value"
    fi
  done

  printf '%s\n' "---"
  printf '%s\n' "$SEAL_MARKER"
}

# Emit a top-level YAML `key: value` line, auto-quoting the value as needed.
emit_yaml_scalar() {
  local key="$1" value="$2"
  printf '%s: %s\n' "$key" "$(yaml_quote "$value")"
}

# Emit an indented YAML `key: value` line inside the provenance block.
emit_yaml_indented_scalar() {
  local key="$1" value="$2"
  printf '  %s: %s\n' "$key" "$(yaml_quote "$value")"
}

# Emits a top-level YAML flow list: `key: [v1, v2, v3]`.
# Empty value emits an empty flow list `key: []`. Elements are split on `,` and each is passed through `yaml_quote`.
emit_yaml_flow_list() {
  local key="$1" raw="$2"
  if [[ -z "$raw" ]]; then
    printf '%s: []\n' "$key"
    return
  fi
  local IFS=','
  # Disable globbing around the word-split so that list elements containing glob metacharacters (`*`, `?`, `[...]`)
  # are not expanded against the filesystem before `yaml_quote` sees them.
  set -f
  # shellcheck disable=SC2206
  local -a parts=($raw)
  set +f
  local out="" i
  for ((i = 0; i < ${#parts[@]}; i++)); do
    if [[ "$i" -gt 0 ]]; then
      out+=", "
    fi
    out+="$(yaml_quote "${parts[$i]}")"
  done
  printf '%s: [%s]\n' "$key" "$out"
}

# Returns the value either bare or single-quoted depending on YAML auto-quoting rules.
# The predicate quotes when the value
# - contains any of the unsafe glyphs (`# : [ ] { } , & * ! | > < ? % @ \` ` `),
# - has leading or trailing whitespace,
# - is empty, or
# - begins with `-` / `?` / `:`.
# Embedded single quotes are doubled inside the quoted form.
yaml_quote() {
  local v="$1"
  if needs_yaml_quoting "$v"; then
    local escaped="${v//\'/\'\'}"
    printf "'%s'" "$escaped"
  else
    printf '%s' "$v"
  fi
}

# Decides whether `v` needs single-quote wrapping. Returns 0 (true) when quoting is required, 1 otherwise.
#
# YAML parses `:` as a key indicator only when followed by whitespace or end-of-value,
# so URLs like `https://...` are safe bare. `#` is always treated as a comment introducer in YAML 1.1/1.2 (the spec is
# permissive about the preceding context), so we quote any value containing `#`.
needs_yaml_quoting() {
  local v="$1"
  # Empty values must be quoted.
  [[ -z "$v" ]] && return 0
  # Leading or trailing whitespace.
  [[ "$v" =~ ^[[:space:]] ]] && return 0
  [[ "$v" =~ [[:space:]]$ ]] && return 0
  # Leading sigils that YAML interprets specially. `?` as a leading
  # character is handled by the glyphs-anywhere case below.
  case "$v" in
  -* | :*) return 0 ;;
  esac
  # Colon followed by whitespace anywhere is a key indicator.
  [[ "$v" =~ :[[:space:]] ]] && return 0
  # Trailing colon is the value-end form of a key indicator.
  [[ "$v" == *: ]] && return 0
  # Glyphs anywhere in the value that require quoting.
  case "$v" in
  *'#'* | *'['* | *']'* | *'{'* | *'}'* | \
    *','* | *'&'* | *'*'* | *'!'* | *'|'* | *'>'* | *'<'* | \
    *'?'* | *'%'* | *'@'* | *'`'* | *"'"* | *'"'*)
    return 0
    ;;
  esac
  # Values that look like YAML booleans/null or numbers stay bare per the current predicate.
  # The predicate's value space is the schema's canonical fields and known extensions;
  # expand here if a future extension introduces ambiguity.
  return 1
}

# Require each named command to be on PATH. Exits 1 with a clear message when one is missing.
require_commands() {
  local cmd
  for cmd in "$@"; do
    command -v "$cmd" >/dev/null 2>&1 || fail "required command not found: $cmd"
  done
}

# Print an error message to stderr and exit 1.
fail() {
  echo "$PROG: $1" >&2
  exit 1
}

# Prints a non-fatal warning to stderr.
# Used for soft-failure conditions where the script should continue with degraded behavior (e.g., a duplicate
# optional-extension key that overwrites an earlier value).
warn() {
  echo "$PROG: warning: $1" >&2
}

# Guard against execution when sourced (e.g., from shellspec tests).
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  main "$@"
fi
